### ISSUE TITLE
Always use `forwardRef` to prevent circular dependencies

### ISSUE THREAD

**Issue by royhadad** [nestjs/nest#10006]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Circular dependency is one of the greatest pains in NestJS and can be solved using `forwardRef` in most (or all?) cases.

### Describe the solution you'd like

I would like to have either a plugin or a config option, that will add `forwardRef` in all imports arrays (modules initialization) and class constructors, this way the developer will never have to worry about circular dependencies.

*That being said*, is this even a good idea? When is using `forwardRef` NOT a good idea? why should one not always use it?

### Teachability, documentation, adoption, migration strategy

It can be added to Nest's docs page about circular dependency.
https://docs.nestjs.com/fundamentals/circular-dependency

### What is the motivation / use case for changing the behavior?

Circular dependency is a major pain in Nest, wasting hours of debugging for developers.

**Comment by BartoszRak** [comment]
Isn't it like a circular dependency issue turns your eyes that maybe you messed up things from the code architecture perspective and it's just a red light🔴 for you? And then you have a choice - look and see why you have a circular dependency and where or if it is intended or you wanna just ignore it you could use `forwardRef`. 🤔 

If we could state that circular dependencies anywhere at any level shouldn't be the common thing you see then adding an option to resolve them automatically by adding `forwardRef` automatically where it is required looks like making it easier going into bad decisions/design. 🤔  

I use `nestjs` privately and commercially since it started to rocketing up into the sky and taking over raw `express`-based apps - I ran into circular dependency a few times in history in some projects - and in 100% cases that was the fault of design, so things were adjusted.

Docs: `While circular dependencies should be avoided where possible, you can't always do so. In such cases, Nest enables resolving circular dependencies between providers in two ways. ` 

Just thoughts - for me it looks a little bit like a feature that will give people an idea that is common/fine and they should use it. This would be bad from my perspective - for me personally `nestjs` by itself gives a recommendation on how you should create an application in a good manner and would be nice if it stays like that.

...but maybe It would be an only somehow helpful way for really thought and really unique situations with no choices available. So idk. 👐

**Comment by magicmatatjahu** [comment]
+ for the previous comment, circular references in 99% is a bad design of the application.

On the other hand, when it comes to technical ability to use by default `forwardRef`, it is not possible without using babel or ts transformers. Why? To understand this we need to understand how `forwardRef`s work in Nest, Angular or other technologies where we have to deal with so-called lazy references.

As an example: If class A uses class B and B uses A then we have this code:

```ts
// a.ts
import { B } from './b';

export class A {
  constructor(private readonly b: B) {}
}
```


```ts
// b.ts
import { A } from './a';

export class B {
  constructor(private readonly a: A) {}
}
```

classes in JS are not hoisted like functions, so if JS try to load code to the memory and execute it, then it loads first A (or B, depends on case), see that have `B` in constructor, which is not loaded, so it "loads" `undefined` instead for class B reference. NestJS handles that problem in such a way that it wraps references to B by closure:

```ts
forwardRef(() => B)
```

and that reference to B is "lazy".  Then when NestJS tries to resolve dependencies of class A (when all JS code is loaded to the memory), checks if given argument is forwardRef or not and if yes, resolve that lazy reference.

Only possibility to handle circular references automatically is creating TS transformer plugin to wrap all modules in imports and all arguments in ctors in transformation stage to JS.

**Comment by kamilmysliwiec** [comment]
Thanks for chiming in @magicmatatjahu @BartoszRak!

Using `forwardRef` is typically considered a bad practice, and overusing it is definitely a code smell. Therefore, there're no plans to implement such a feature in the foreseeable future.
