### ISSUE TITLE
Node engine version requirement

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#101]
Can someone tell me what's the lowest version of the node engine ver requirement?
When I look at the http://node.green it looks like the 6.11.0 might be enough. But 7.10.0 looks more promising (because of async/await features). So there are any suggestion?

Btw maybe it's time to add in **package.json**:
```json
  "engines": {
    "node": ">=min_ver_req"
  }
```

**Comment by kamilmysliwiec** [comment]
Hi @cojack,
Thanks for the suggestion, definitely needed.

**Comment by d3viant0ne** [comment]
Personally, given this is relatively new and there are no existing support requirements it would probably be beneficial to set it and 8 ( the soon to be LTS ).

Dropping older node versions is always cumbersome for maintainers ( we still have to support 4.3 in Webpack ). I would personally push the minimum out as far as possible and start as far ahead of the game as possible. Once it's set you are going to be tied to that minimum for quite a while.

Also, while I understand you point about async/await. It's unwise to set a min support version to a node development version as amongst other things, it doesn't get updated once the even number release drops.

**Comment by saskodh** [comment]
Having high version might prevent many projects from setting up iterative migration to Nest from Express or any other Node.js framework. The Typescript compiler supports targets down to es3 :), so this helps in supporting lower Node.js version.

**Comment by d3viant0ne** [comment]
NodeJS themselves don't support versions you are talking about, 4.x is in maintenance which is End Of Life in April 2018.

Lower NodeJS versions should not be supported, particularly versions that NodeJS themselves don't support. Setting minimum NodeJS versions is easy these days, follow the NodeJS LTS release schedule - https://github.com/nodejs/Release to the letter & without exception.

It sets a very clear set of expectations that is inline with the rest of the ecosystem.

> The Typescript compiler supports targets down to es3

- If you take a moment to look through the dependencies of Nest, it's absolute minimum is controlled by it's dependencies not how far down you can transpile your JavaScript.
- Just because you can do something, doesn't mean you should. As I said above, once you set a president, it is detrimental to change it. 

4.x should not be considered, even if it were possible.
6.x LTS versions should be supported, that's `nodejs > 6.9.0`
8.x LTS versions should be supported, `exact starting version tbd '~8.8'`

**Comment by saskodh** [comment]
@d3viant0ne, I totally agree with you, the thing with the es3 target was just a point maker. :) 
I was also thinking 6.x or considering 4.x if possible.

**Comment by d3viant0ne** [comment]
4.x is a nightmare. 

- Some versions work, some don't. 
- More than a few bugs that aren't going to be fixed.
- Ever decreasing feature parity 
- Huge performance hit
- NPM 5 issues with earlier versions
- It's a tragic mess on Windows
- On & on ...

By the time something is actually done on this side, it's going to be in maintenance. By the time it may matter, it's going to be E.O.L.

On the consumer side, upgrading from Node 4 to Node 6 is trivial. It's supported in every PaaS that has lambdas & you are gaining features not dropping them.

The simple truth is Node v4 was their digging out of a hole release & for what they had to accomplish, they did a commendable job but Node as an org has moved on. People should have been off of Node 4 already or at least have it planned, enabling the slow adoption rate while hamstringing a project is a mistake.

Simple enough solution. Don't set the engines until v8.0 hits LTS & then set the precedent that both LTS versions are supported & the project moves with the LTS schedule.

From the perspective of a maintainer ( we are just now getting away from 4.x in Webpack ) it's been a constant source of aggravation as well as being extremely limiting during development.

**Comment by kamilmysliwiec** [comment]
Thanks everyone for your help and guidance. Min node version is set to >= 6.11.0 now.
