### ISSUE TITLE
InjectionToken

### ISSUE THREAD

**Issue by LimarenkoDenis** [nestjs/nest#1019]
Hi, First of all, thanks for an awesome framework, we have been using Nestjs for production since it released )

## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
for now, it works like this 
<pre><code>
@NgModule({
  components: [{provide: SOME_DOMAIN_TOKEN, useValue: SOME_DEMAIN_VALUE}]
})
class AppModule {}

@Controller('*')
class AppController {
  constructor(@Inject(TOKEN) domain: string) {}
}
</code></pre>

## Expected behavior

Angular has InjectionToken
so it looks like this
<pre><code>
import { InjectionToken } from '@angular/core';

export const DOMAIN: string = environment.host.api.url;
export const DOMAIN_TOKEN: InjectionToken<string> = new InjectionToken(DOMAIN)

providers: [{ provide: CRESTOOKEN_DOMAIN_TOKEN, useValue: CRESTOOKEN_DOMAIN },]
</code></pre>

NestJs version: latest

**Comment by BrunnerLivio** [comment]
The [InjectionToken does surprisingly not do much in Angular 5.2.11](https://github.com/angular/angular/blob/5.2.11/packages/core/src/di/injection_token.ts). Seems like it is only a small wrapper so it does not directly expose the string. That should not be too hard to implement I suppose. The injection token can get more useful in the future. For example with Angular 6 (I think) they've introduced an [optional setting for injection tokens](https://angular.io/api/core/InjectionToken#constructor). But first we should focus on implementing the InjectionToken of 5.2.11 because the `providedIn`-feature would need tons of work.

**Comment by kamilmysliwiec** [comment]
The `InjectionToken` is nothing more than a simple wrapper around literal string values. As soon as you follow best practices, and you don't hardcode magic strings across your codebases, they're worthless from Nest perspective. Keep them in a dedicated place, export as constant values, and all will be fine. 

In terms of the `providedIn`, there is no plan to implement it in the future. Basically, we just don't need that on the backend side, since dead code elimination (aka tree-shaking) is useless for us.
