### ISSUE TITLE
Responses in XML

### ISSUE THREAD

**Issue by dribro** [nestjs/nest#1023]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

Hi, 

## What is the motivation
I need to have my API respond in XML as well as in JSON, as to respond to clients with legacy software.

## Current behavior
I added an interceptor, which, along with js2xmlparser which worked well enough:

```typescript
  intercept(context: ExecutionContext, call$: Observable<T>): Observable<any> {
    const request = context.switchToHttp().getRequest();
    const wantsXML: boolean = !! request.query.xml;
    return call$.pipe(
      map(results => wantsXML
        ? js2xmlparser.parse('response', new ResponseDto(results))
        : new ResponseDto(results)),
    );
  }
```

However when an exception is thrown this interceptor isn't called, it is called if I add to the ``catchError`` to the return
```typescript
  intercept(context: ExecutionContext, call$: Observable<T>): Observable<any> {
    const request = context.switchToHttp().getRequest();
    const wantsXML: boolean = !! request.query.xml;
    return call$.pipe(
      catchError(err => throwError(
        new HttpException(new ResponseDto(err.message, err.status), err.status)),
      ),
      map(results => wantsXML
        ? js2xmlparser.parse('response', new ResponseDto(results))
        : new ResponseDto(results)),
    );
  }
```

The issue with this is I can't control whether or not the error is thrown in xml.

## Expected behavior
Is there a way have a global path prefix, lets say /xml, in which all responses are XML?
I'm using fastify right now, but i'll be willing to switch to express if it could make this happen.

## Environment
- Nest version: 5.2.2
- Node Version: 8.11.3
- Platform: Linux 4.9.93

Thank you in advance.
It's been a pleasure to use this framework so far. 👍

**Comment by kamilmysliwiec** [comment]
Very neat solution @dribro 👍 

*However when an exception is thrown this interceptor isn't called, it is called if I add to the catchError to the return*

You've got 2 possible solutions:
1. Instead of throwing an error, simply map your exception to the XML representation inside the `catchError` operator
2. Create an exception filter which, depending on the query parameters, transforms (or not) your error to XML.
The second sounds somewhat cleaner I believe.

*Is there a way have a global path prefix, lets say /xml, in which all responses are XML?*

Unluckily, no. All handlers would have to be deduplicated anyway. Your idea with `xml` query parameter looks like a best middleground.
