### ISSUE TITLE
Underlying HttpServer is of type `any`

### ISSUE THREAD

**Issue by royhadad** [nestjs/nest#10480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`app.listen()` and `app.getHttpServer()` return the underlying HttpServer, but regarding types - the returned type is `any`.
Is there a way we can improve this type? 
Currently, I'm doing this, which feels unsafe:
![Screen Shot 2022-10-30 at 17 17 07](https://user-images.githubusercontent.com/39004075/198886464-5dd0da1c-6a78-4e84-b486-a99293af87c2.png)

### Minimum reproduction code

https://codesandbox.io/s/ecstatic-sanderson-xpxxfv

### Steps to reproduce

1. go to the codesandbox link
2. hover over the `server` const.
3. see it's of type `any`

### Expected behavior

I expect server to have a safer type, perhaps `{ Server } from 'https'`?
maybe something else? Open for suggestions

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [X] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [X] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.6

### Packages versions

```json
    "@nestjs/core": "8.0.6",
```

### Node.js version

16.14.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

Relevant source code block:
https://github.com/nestjs/nest/blob/21bd8c37364a2a2591e3de9bfb88d32d09431438/packages/common/interfaces/nest-application.interface.ts#L57

**Comment by micalevisk** [comment]
Let's use the `express` adapter as an example:

https://github.com/nestjs/nest/blob/21bd8c37364a2a2591e3de9bfb88d32d09431438/packages/platform-express/adapters/express-adapter.ts#L186-L193

https://github.com/nestjs/nest/blob/21bd8c37364a2a2591e3de9bfb88d32d09431438/packages/platform-express/adapters/express-adapter.ts#L118-L119

as you can see above, we can't define a static type for the return of `listen` because it could be either  
`import { Server } from 'https'` or  
`import { Server } from 'http'`  
which is defined at runtime.

**Comment by micalevisk** [comment]
nvm _lol_

I just found that the `Server` is the same regardless of the http module being used:

- nodejs docs on `server.listen` of `https`: https://nodejs.org/api/https.html#serverlisten
- nodejs docs on `server.listen` of `http`: https://nodejs.org/api/http.html#serverlisten

both of them points to [server.listen](https://nodejs.org/api/net.html#serverlisten) from `net` module, which return [net.Server](https://nodejs.org/api/net.html#class-netserver).

So we could replace that `any` with `net.Server` since  
`server instanceof net.Server === true`.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10481

**Comment by royhadad** [comment]
Great! do we want to make the same adjustment in other places as well? (e.g. fastify)

**Comment by micalevisk** [comment]
I thought that the `listen` on fastify adatper always return `undefined` due to the typings defined below

https://github.com/nestjs/nest/blob/60d286d22e49951494d6ec959097e169faeb7a0b/packages/platform-fastify/adapters/fastify-adapter.ts#L222-L228

but I just tested it and it returns the same Server instance. I'll update that too then.

![image](https://user-images.githubusercontent.com/13461315/199108923-e51b06b4-9018-4f30-b0d2-1fe0a47c74ef.png)

**Comment by micalevisk** [comment]
I'm getting `Type 'void' is not assignable to type 'Server'` because `instance.listen` returns `void` even tho `await app.listen(port, callback)` return `Server` :thinking: I might be missing something

https://github.com/nestjs/nest/blob/60d286d22e49951494d6ec959097e169faeb7a0b/packages/platform-fastify/adapters/fastify-adapter.ts#L237

**Comment by royhadad** [comment]
Well, as you've stated yourself, the actual object is different from the type definition, it makes sense that you get a type error. Using the `as` keyword could potentially solve this, I guess.

**Comment by micalevisk** [comment]
yeah, I need to figure out why the type of `this.instance.listen()` is `void`. Feel free to investigate that please
