### ISSUE TITLE
[Discussion] Need more informations on contribution guide

### ISSUE THREAD

**Issue by lauthieb** [nestjs/nest#1073]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Today, I want to contribute to Nest. So I read the CONTRIBUTING.md and I didn't find any information about the commands to execute (npm link etc.) to contribute on NestJS.

## Expected behavior

I would appreciate to have a real developer guide with examples to help me contribute to NestJS.

## What is the motivation / use case for changing the behavior?

I think with a real guide and a presentation of the different packages available on the framework, it would be much easier for developers to contribute to this project.

## Environment

Nest version: 5.3.6

 
For Tooling issues:
- Node version: 10.10.0
- Platform:  Mac

**Comment by BrunnerLivio** [comment]
> I would appreciate to have a real developer guide with examples to help me contribute to NestJS.

Agree. There is not much information how you actually locally build, run and test nest locally.
I think we could improve and adapt a similar Contributing guideline as [yarn](https://yarnpkg.com/en/org/contributing/) since it is super simple and straight forward. 

> a presentation of the different packages available on the framework

A dependency graph similar to the one [I drew for a different issue](https://camo.githubusercontent.com/107fac910a47a32de2e476f125910c7a1938f9c4/68747470733a2f2f692e696d6775722e636f6d2f304c50674f36392e706e67) would be nice. Since I am a super lazy, DevOps-loving-guy, I do not want to redraw such a graph for a every release. I've found [npm-dependencies.com](http://npm-dependencies.com) which is [open source](https://github.com/TypeFox/npm-dependency-graph), but does not have a good developer interface as far as I know.
It generates beautiful graphs though (ignore `@nestjs/terminus` & `@nestjs/websocket`). 

![Dependency Graph](https://i.imgur.com/AtRBoVK.png)

**Comment by ahrnee** [comment]
Yes - contributor developer documentation would be great.  [CONTRIBUTING.md](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md) has a reference to "developer documentation", but the link is dead (https://github.com/nestjs/nest/blob/master/docs/DEVELOPER.md) 
:(

**An Example of the Need**
I pulled the source to try and create a PR with a minor update.  When I run "npm install", it automatically triggers a gulp build step, which fails with multiple error messages (examples below), and makes me think I am missing something critical.  Not sure what to do from here.

**Example of the build errors**
```
packages\core\adapters\express-adapter.ts(123,28): error TS2339: Property 'prefix' does not exist on type 'ServeStaticOptions'.
packages\core\adapters\express-adapter.ts(124,31): error TS2339: Property 'prefix' does not exist on type 'ServeStaticOptions'.
packages\core\injector\injector.ts(2,3): error TS2305: Module '"/nest/node_modules/@nestjs/common/constants"' has no exported member 'OPTIONAL_DEPS_METADATA'.
packages\core\injector\module.ts(8,39): error TS2307: Cannot find module '@nestjs/common/utils/random-string-generator.util'.
packages\core\nest-application-context.ts(5,3): error TS2305: Module '"/nest/node_modules/@nestjs/common/index"' has no exported member 'OnApplicationBootstrap'.
packages\core\scanner.ts(14,39): error TS2307: Cannot find module '@nestjs/common/utils/random-string-generator.util'.
```

**Comment by BrunnerLivio** [comment]
Lets wait until #1060 is merged with the new developer.md file. It will change the processes anyway. 
@ahrnee are you on latest? Maybe remove the node_modules folder and run npm install again.

**Comment by kamilmysliwiec** [comment]
@ahrnee the issue is that you need to build packages **twice**. Errors will disappear then.

**Comment by ahrnee** [comment]
Yep - building packages multiple times took care of the issue (three times was the lucky number).  Thanks @BrunnerLivio and @kamilmysliwiec for the follow-up.

**Comment by patricknazar** [comment]
@kamilmysliwiec Lines 83-275 are not visible on github or in vs-code markdown preview. Presumably other markdown renderers too.

    

https://github.com/nestjs/nest/blame/ceabe7418a343617687d346bd8670ec018f12429/CONTRIBUTING.md#L81

this is breaking those lines. As a result your link above doesn't work.
