### ISSUE TITLE
HTTP in-flight request type

### ISSUE THREAD

**Issue by mlshv** [nestjs/nest#10805]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

[`HttpArgumentHost.getRequest()`](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/features/arguments-host.interface.ts#L12) returns `any` for some reason

### Describe the solution you'd like

The method returns `any` type but it's an HTTP request, so it should be typed accordingly

### Teachability, documentation, adoption, migration strategy

I couldn't google how people normally type it, all the examples i've found were using `any` type. Some of them had `instanceof` checks for certain properties but majority of them were written in JS style without trying to type anything.

### What is the motivation / use case for changing the behavior?

The motivation is to make it possible to utilize autocomplete on the request object and provide some level of type safety

**Comment by jmcdo29** [comment]
It's either an `IncomingMessage` (i.e. Express's `Request`) or it's a wrapper of an `IncomingMessage` (i.e. Fastify's `FastifyRequest`). To accommodate for this, the `getRequest()` method is generic so you can do `host.switchToHttp().getRequest<express.Request>()` and now Typescript knows it returns an `express.Request` typed object. Because there's very little overlap of `Request` and `FastifyRequest`, plus there can be other adapters created for Nest, it's hard to say "This will always be an `IncomingMessage` instance"

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
