### ISSUE TITLE
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

### ISSUE THREAD

**Issue by morbargig** [nestjs/nest#10827]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/10808#issuecomment-1373518231_
      
Hi I can give all the details needed 
so if you can please reopen the bug report, I will make the bug report more clean and give all the Information needed. 

I already once asked to go to the discord group and I not want to install unnecessary app for it.
GitHub is a fine platform and if you don't respect it is not my problem.

Please reopen the bug, so I can fill the missing information.
I'm working in a very big enterprise, and we are for now using your tool.
So a bit of help can be very useful.

It is not ok to just automatically close bug reports.

You did such i great work with nest for a long time,
but literally there are more bugs than ever.

In my company, we would like to keep using nest, so please be more patient.
And open discord to all my team is not a possible for the nest chat.

I have been working with nest for a while and i sure that it can be solved very easily.
This package @nestjs/platform-express using express, but it's needs to reflect it so PNPM will understand installing it correctly or if not to export the types from express core package. 

This bug prevents developers who use PNPM from using nest.

**Comment by Tony133** [comment]
Hi @morbargig, I recommend that you leave a minimal reproduction of a cloneable git repository if you can, so that the core team can evaluate the problem you reported. This is the only way for the NestJS Core Team to better investigate and assess the problem; most likely the information provided was insufficient to assess the problem.
Hower if you have already identified the point yourself how to solve the problem directly create a PR(Pull Request) for it.

**Comment by morbargig** [comment]
@Tony133 
ok, so, can you please reopen the last bug report? And I will make sure to fix it right away.

**Comment by Tony133** [comment]
@morbargig, I don't have permissions to do that unfortunately, because I am not part of the NestJS Core Team I am only a Contributor and Moderator of the NestJS Community where I help in my spare time NestJS because I think it has great potential as a framework.

However if you have already identified the point how to solve the problem, create a Pull Request and in the PR write all the explanations of why you are making this change. 
Sometimes it is enough even creating a PR directly without creating an issue is enough if you have already identified how to solve the problem.

**Comment by morbargig** [comment]
@Tony133 thanks you very much 
to be honest, I don't think I have the solution yet.
But I clearly can explain it, and if you have a free time and good attention I would like to get helped by you and maybe release pr to fix it with no time.

Let me know of your thoughts 🙏

**Comment by Tony133** [comment]
@morbargig, you should describe all the steps you did in order to replicate the problem or create a minimal reproduction in a cloneable git with the error. These are more useful steps, but I think you could also open a post on the nestjs forum on Discord, because I think this issue will be closed without minimal reproduction.

**Comment by kamilmysliwiec** [comment]
Your issue isn't related to NestJS. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
