### ISSUE TITLE
Constructor parameter decorators should allow `undefined` as the type of `key`

### ISSUE THREAD

**Issue by DanielRosenwasser** [nestjs/nest#10959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

TypeScript 5.0 introduces some tightening on decorator type-checking. This is basically a bug fix, but it affects any decorator used on constructor parameters.

```ts
export declare const Inject:
  (entity: Function) =>
    (target: object, key: string | symbol, index?: number) => void;

export class Foo {}

export class C {
  constructor(@Inject(Foo) x: any) {}
}
```

Here, the decorator function returned by `Inject` says it takes a `string | symbol` for its `key` parameter; however, if the usage above is supposed to be valid, then this declaration always been incorrect. Constructor parameters always receive `undefined` for their `key`.

TypeScript 5.0 enforces checking on this, and users of existing decorator libraries like NestJS will receive an error like the following:

```
Unable to resolve signature of parameter decorator when called as an expression.
  Argument of type 'undefined' is not assignable to parameter of type 'string | symbol'
```

More details are available on the TypeScript repo at https://github.com/microsoft/TypeScript/issues/52435

### Minimum reproduction code

https://www.typescriptlang.org/play?ts=5.0.0-dev.20230126#code/JYWwDg9gTgLgBAbzgSQHYCsCmBjeBfOAMyghDgCIABVTAZxnVoHptSQJVyBuAWACh+2ADYBDWrTgBhRPzhy4rVPSgBXXNAAUlNFlwaAyjCjBUAcwCURCBABccZSYuI8-PEA

### Steps to reproduce

Try any example of `@Inject` on a constructor parameter with `typescript@next`.

### Expected behavior

Nest should update its declaration to allow `undefined` as a key type.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Packages versions

9.2.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
I just created a PR for this issue https://github.com/nestjs/nest/pull/10970

Also, on a side note, thank you (and the entire TypeScript team) for allowing us to keep using the original TS-decorators implementation in v5. Switching to the JS decorators (current proposal) would drastically degrade DX since it currently doesn't support param-based decorators + `emitDecoratorMetadata`. Both features are essential not only for the NestJS framework (and its ecosystem) but for some other,  popular TS libraries too (be it `typeorm`, `class-transformer`, `class-validator` etc., each one having +1M downloads/week). I hope we can postpone the migration for the foreseeable future given how impactful (in a negative sense) it would be until there's a full feature parity between those two implementations.
