### ISSUE TITLE
Interceptor for any provider method

### ISSUE THREAD

**Issue by yukukotani** [nestjs/nest#10973]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, interceptors can only apply to controllers.

It would be useful if interceptors could apply to any provider method for per-method logging or something.

### Describe the solution you'd like

Wrap provider instance with [Proxy](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

### Teachability, documentation, adoption, migration strategy

```ts
@Injectable()
export class LoggingInterceptor implements NestInterceptor {
  // MethodDescriptor may contain metadata like method name
  intercept(desc: MethodDescriptor, next: CallHandler): Observable<any> {
    console.log(`${desc.name}: Before...`);

    const now = Date.now();
    return next.handle().pipe(tap(() => console.log(`${desc.name}: After... ${Date.now() - now}ms`)));
  }
}
```

```ts
@Injectable()
export class MathUsecase {
  constructor() {}

  @UseInterceptor(LoggingInterceptor)
  doubleNumber(num: number): number {
     return num * 2;
  }
}
```

### What is the motivation / use case for changing the behavior?

Same as the current interceptor, but per method.

**Comment by jmcdo29** [comment]
> It would be useful if interceptors could apply to any provider method for per-method logging or something.

You can create your own decorator to handle something like this. [Ogma](https://ogma.jaymcdoniel.dev/en/nestjs/service/#log-and-logall-decorators) has support for this.

There's no plans to make providers work with interceptors or any other enhancers. They work at the controller level because that is where the control of logic changes from framework to dev. Wrapping all the providers in a `Proxy` could have unintended side effects as well.
