### ISSUE TITLE
Types mismatch for *microservices* and *core* modules 

### ISSUE THREAD

**Issue by bacloud23** [nestjs/nest#11195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hi,
I'm having version 9

    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.0",
    "@nestjs/swagger": "^6.2.1",

and following doc recipe for adding Redis transport, 

```
const app = await NestFactory.createMicroservice<MicroserviceOptions>(
    AppModule,
    {
      transport: Transport.REDIS,
    },
  );
```

Other methods are no longer present:

`app.getUrl`
`app.enableVersioning`
`app.listen`

> Property 'enableVersioning' does not exist on type 'INestMicroservice'.

Also Swagger methods seem not to accept the new `app`. 

> Argument of type 'INestMicroservice' is not assignable to parameter of type 'INestApplication'.

Am I messing something  ?

Thanks a lot for your consideration !!

### Minimum reproduction code

https://github.com/bacloud23/testing-microservices-versions

### Steps to reproduce

just `npm install`  

### Expected behavior

no errors I guess following the [example](https://docs.nestjs.com/microservices/redis)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### Other package

@nestjs/microservices

### NestJS version

9

### Packages versions

```json
    "@nestjs/common": "^9.0.0",
    "@nestjs/core": "^9.0.0",
    "@nestjs/microservices": "^9.0.0",
    "@nestjs/platform-express": "^9.0.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0"
```

### Node.js version

v16.17.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
It's almost like `INestMicroservice` and `INestApplication` are two totally different interfaces with different methods.

This is the expected behavior. Microservices don't have the same versioning idea as REST applications, nor do you usually need to call to their running address directly, that's usually handled by the microservice broker. `listen` should still exist, but it should be an async method with no parameters. 

If you are looking to _add_ a redis microservice to your REST application, take a look at the [hybrid application docs](https://docs.nestjs.com/faq/hybrid-application).
