### ISSUE TITLE
Incorrect/misleading behavior of INestApplicationContext.select()

### ISSUE THREAD

**Issue by craigotis** [nestjs/nest#11273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

See [this repo](https://github.com/craigotis/nestjs-select) for easy reproduction.

What we're seeing is that `.select(...).get(...)` will _walk back up_ the tree to find any provide that matches the requested type, and that it isn't finding the module-scoped instance that we'd like it to.

Please also note that if we use `get(..., { strict: true })`, we're unable to locate the specific provider instance at all.

I've also been reviewing this behavior on [the Discord](https://discord.com/channels/520622812742811698/1083776376731091124).

### Minimum reproduction code

https://github.com/craigotis/nestjs-select

### Steps to reproduce

```
npm i
npm run test:e2e
```

### Expected behavior

All the tests should pass.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

9.3.9

### Packages versions

```
➜  nestjs-select git:(main) npx nest info

 _   _             _      ___  _____  _____  _     _____
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/


[System Information]
OS Version     : macOS Unknown
NodeJS Version : v18.3.0
NPM Version    : 8.11.0

[Nest CLI]
Nest CLI Version : 9.2.0

[Nest Platform Information]
platform-express version : 9.3.9
schematics version       : 9.0.4
testing version          : 9.3.9
common version           : 9.3.9
axios version            : 2.0.0
core version             : 9.3.9
cli version              : 9.2.0
```

### Node.js version

18.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
For `INestApplicationContext`, `strict` is set to `false` by default (contrary to the `ModuleRef` class), which means using `select` without setting `strict` to `true` won't have any impact. Now, if you set `strict` to `true`, you must walk through the entire tree up to the module that registers a given provider so `select(GoogleModule)` is not sufficient if you're also not selecting `HttpModule`.

What you would need in this case is: 

```
.select(GoogleModule).select(HttpModule.register({
  baseURL: 'https://www.google.com',
}))
```

because `HttpModule` !== `HttpModule.register({ baseURL ... })`

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
