### ISSUE TITLE
Why @nestjs/core requires a peerDependency of @nestjs/microservice?

### ISSUE THREAD

**Issue by alexjoverm** [nestjs/nest#116]
I've just thought that microservice is only required if you use microservices... Why `core` depends on `microservice`?

**Comment by d3viant0ne** [comment]
There are a couple of places where there are circular dependency issues that need to be sorted out.

**Comment by saskodh** [comment]
Also the websockets module is a peer dependency and the app could not be started w/o them, even though the project doesn't use any of them.

**Comment by wbhob** [comment]
As a general design idea, I think `@nestjs/common` should be eliminated, and here's why:

Everything inside of each package should only depend on Core. By putting interfaces and the like in Common, every package has two dependencies that could have been just one. This isn't a problem, just a quirk for developers who need to remember where something was located: Core or Common.

To that end, Core should not depend on any other Nest package, because that could lead to circular dependency issues down the line. Core should be architected in such a way, where Microservices and Sockets are independent modules that individually extend on Core. Here's an example:

```NestFactory.implement(MicroserviceFactory)```

or something along those lines. That way, anyone can develop adapters simliar to sockets or microservices, and they can all easily be plugged into Core. And, of course, Core won't have to depend on @nestjs/microservices or @nestjs/websockets

**Comment by wbhob** [comment]
@saskodh this could be causing some of the issues:
https://github.com/nestjs/nest/blob/dc7869b38f3cdc293028e4cca69623be8446efc3/src/core/nest-application.ts#L36

**Comment by wbhob** [comment]
Update: I’m working on a PR to eliminate this circular dependency

**Comment by wbhob** [comment]
I've opened #212 to address circular dependency. Looking for reviewers and commits to turn CI green!

**Comment by kamilmysliwiec** [comment]
After latest release the codependency between packages is removed - it's possible to use `core` without both `microservices` and `websockets` package installed. The dependencies have been eliminated without any breaking changes 🙂
