### ISSUE TITLE
migrate towards ESM modules

### ISSUE THREAD

**Issue by yuntian001** [nestjs/nest#11897]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I hope nest will migrate to ESM modules and would like to ask about the specific migration planning。

### Describe the solution you'd like

The default example uses esm

### Teachability, documentation, adoption, migration strategy

The default example uses esm

### What is the motivation / use case for changing the behavior?

When I write the test file, `await import(pathToFileURL(this.dbConfig).href)` is not supported. I want to be able to migrate ESM modules. To get top-level support for import()，And ESM is backward compatible with commonjs, which is very friendly.

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/pull/8736

**Comment by yuntian001** [comment]
> [第8736章](https://github.com/nestjs/nest/pull/8736)

It has not responded for two years. Is there any official plan

**Comment by jmcdo29** [comment]
Kamil agreed with the owners of the fastify repo, it's still premature

**Comment by albjeremias** [comment]
im so confused about this. nestjs is really not thinking of implementing ESM ?

**Comment by micalevisk** [comment]
@albjeremias migrating any package to ESM is not a easy task. There are no good reasons to do that so far (specially now that Node.js is making the usage of ESM packages from CJS apps easier). ESM is good but CJS is still good enough for libs.

**Comment by thw0rted** [comment]
I do wish they'd stop closing the "please migrate to ESM" issues every time, and just keep one open to track status.  I've probably looked at a dozen related (mostly closed) issues, and I think the last thing I saw was that **property decorators** have not been finalized yet, so Nest still needs a bundler, so why not stick to CJS.  The other argument I see made frequently is that your app runs the same whether Nest puts it through a bundler or not, and the last pain point (using ESM-only libraries) should now be resolved with TS 5.8 / tsconfig "node20" module format on node 22+, where `require(ESM)` provides interop.

I think I'd like to eventually get all the bundlers and transpilers out of my workflow just so I know what actually runs in the engine, but that's definitely a taste/preference thing rather than a practical complaint.
