### ISSUE TITLE
Type definitions for ParameterDecorator missing

### ISSUE THREAD

**Issue by kolbma** [nestjs/nest#1210]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

@Req() req has any type.

## Expected behavior

Maybe it is possible that we get here a correct Request type.
Also for the other Decorators.

## What is the motivation / use case for changing the behavior?

TypeScript is all about types. And nest says it is a TypeScript Framework. 
I miss many definitions.

## Environment

<pre><code>
Nest version: 5.3.14

</code></pre>

**Comment by kamilmysliwiec** [comment]
Nest is a platform-agnostic framework (you can use it with either fastify or express). We can't force you to use particular typings (just pick whatever you prefer, for example, install `@types/express`)

**Comment by kolbma** [comment]
@kamilmysliwiec  Then use Interfaces to implement types. I think you didn't understand.
You say nest is TypeScript Framework. But all over the place in nest there are any-types.
Every JS Framework can provide any-types.

**Comment by kamilmysliwiec** [comment]
I think you don't understand what I'm talking about. Both `@Res()` and `@Req()` are **different** depending on the TYPE of library used underneath which YOU can select on your own. Fastify and express has **different** types. We can't use interfaces and override original typings because choice belongs to you. Please, get familiar with the framework and then make judgments.

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec
May this could be fixed in 6.0.0? When express & fastify get extracted into separate modules, these modules could expose their own implementation of the Req/Res decorator and therefore its own type? I do not know how the Req decorator is currently implemented, so correct me if this would not (easily) be possible?

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec
Cool! 😎

> Decorator might be shared, it's not tied to any platform
Makes sense there is a common interface for this, but maybe each platform module inherits the shared implementation of the @nestjs/core Req decorator in a custom implementation.
The downside would be that users had to migrate by updating the import path of Req.

**Comment by kolbma** [comment]
@kamilmysliwiec Oh boy.

**Comment by hgezim** [comment]
I completely agree with initial request here. It's super odd to be working on [this tutorial](https://docs.nestjs.com/controllers) and type `res.<Ctrl+Space>` and get nothing.
