### ISSUE TITLE
strong typing metadata for `Reflector` service

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#12101]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

when using `Reflector#get`/`Reflector#getAll` and so on, the return type is `any` for good reasons.

A bad way (as stated in the book [Effective TypeScript](https://effectivetypescript.com/) p. 165) to circumvent that is by letting the dev hard define a type arg that will be used as the type of such returned value. Although better than `any`, doing that is basically the same as using type assertions. Also, if that type arg, we now have to write code that could be duplicated in the codebase and could easily be out of sync.

### Describe the solution you'd like

instead of  
`this.reflector.get<string[]>('roles', context.getHandler())`  
we now will just use  
`this.reflector.get('roles', context.getHandler())`  

---

Leverage on the same API as in `ConfigService` from `@nestjs/config` by adding a type arg to the `Reflector` class instead. Like this:

![image](https://github.com/nestjs/nest/assets/13461315/e77c02a3-c57c-4ba3-bd72-2a3d584aa8fd)

This is safer at type level while also kinda helps on enforcing the developer to write well-defined properties to later retrieve via reflection

### Teachability, documentation, adoption, migration strategy

minor change to the docs https://docs.nestjs.com/fundamentals/execution-context#reflection-and-metadata to mention on this capability

### What is the motivation / use case for changing the behavior?

- make Nestjs built-in providers more type-safe
- improve DX (for those there are familiar with typescript generics) by tied coupling the available metadata keys with their intended values

**Comment by jmcdo29** [comment]
If we take this approach, we could then advocate for keeping an interface of metadata keys to type so that devs could then do `Reflector<Metadata>`. We could also make a `NestMetadata` interface that could be intersected in the `Reflector` generic and provide a typesafe interface face all of the keys to values that the `Reflector` could return, at least based on the keys we can well define. 

I'm all for this. We'll see what Kamil thinks. If this can also be taken care of in a backwards compatible way, that would be even better

**Comment by kamilmysliwiec** [comment]
> A bad way (as stated in the book [Effective TypeScript](https://effectivetypescript.com/) p. 165) to circumvent that is by letting the dev hard define a type arg that will be used as the type of such returned value. Although better than any, doing that is basically the same as using type assertions. Also, if that type arg, we now have to write code that could be duplicated in the codebase and could easily be out of sync.

This really depends on the context (_where_ and under what circumstances that type argument is going to be used). 

> If we take this approach, we could then advocate for keeping an interface of metadata keys to type so that devs could then do Reflector<Metadata>

I feel like this could be an anti-pattern due to the decentralized nature of metadata. I mean, I'm not saying that having the interface is bad per se, I just feel like having a **global** interface with **all existing metadata keys** might be. 

Just thinking out loud here but what if we exposed a new, experimental `createTypesafeDecorator`? Something along these lines:

```ts
export const Roles = createTypesafeDecorator<string[]>((...roles) => roles);
```

and then make Reflector support the following call signature:

```ts
// get or getByDecorator 
const roles = this.reflector.get(Roles, class Noop {}) // roles type will be auto-inferred as `string[]`
```

**Comment by jmcdo29** [comment]
> I feel like this could be an anti-pattern due to the decentralized nature of metadata.

Perhaps so. I do think it would be nice to have a way to track what metadata keys should return type wise, but maybe a centralized interface isn't the way to go about it.

> Just thinking out loud here but what if we exposed a new, experimental createTypesafeDecorator?

This might be cool. There'd need to be some sort of way to specify if it's a method decorator, class decorator, maybe param decorator, or whatever combination, so that the resulting decorator is as typesafe as it can be. However, passing the decorator to `reflector.get` does seem like a pretty cool idea. Or at least a new method on `Reflector`. 

I think both approaches have their merits, the interface probably being less work and quicker wins, but the typesafe decorator probably being more newcomer friendly in the long run. :thinking:

**Comment by micalevisk** [comment]
thinking better now, this proposed API doesn't solves the underlying issue with `Reflector` because even with that generic type arg there will be easy way to ensure that such metadata is in fact present. I'll see how to take the `createTypesafeDecorator`-ish then.

**Comment by kamilmysliwiec** [comment]
This PR introduces a quite similar feature https://github.com/nestjs/nest/pull/12107, check it out :)
