### ISSUE TITLE
Can not catch the MQTT client when the broker goes down

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/nest#12201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

At the moment, I have the following code:

```ts
await this.client.emit('testFailure', 5).subscribe({
  next: () => {
    console.log('sent!!');
  },
  error: (err) => {
     console.log('emit err', err); // issue
  },
});
```

Initially, the app works fine and I see the `sent!` log. But when I stop mqtt broker (e.g. removing the port mapping from docker-compose.yml file and re-run docker-compose), then I can't catch the error.

The **important point** is, if I remove the port mapping before running the application, I can see the error message. So the code seems to be fine.

### Minimum reproduction code

https://github.com/vahidvdn/nest-mqtt-issue

### Steps to reproduce

1. `npm install`
2. `docker-compose -d --build`
3. `npm run start:dev`
4. Now you see the sent message every 3 seconds
5. Remove line 7 in docker-compose file (`- 1883:1883`)
6. `docker-compose -d`
7. You don't see 'err' message

### Expected behavior

I should see `emit err` message in console.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.0.0

### Packages versions

```json
"@nestjs/common": "^10.0.0",
"@nestjs/core": "^10.0.0",
"@nestjs/microservices": "^10.1.3",
"@nestjs/platform-express": "^10.0.0",
"mqtt": "^5.0.2",
"reflect-metadata": "^0.1.13",
"rxjs": "^7.8.1"

```

### Node.js version

19.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by vahidvdn** [comment]
The port line was commented in the `docker-compose` file of the repo, so you need to check again. (first run application with the correct port)

@kamilmysliwiec any idea for this?

**Comment by vahidvdn** [comment]
Apparently, it's the default behavior of `mqtt-async`. Not sure if I can close this issue or not.

But in NestJS `mqtt` is being used under the hood, not `mqtt-async`. So for now I keep it open, in case someone has an idea.

**Comment by penguin011** [comment]
The issue you've described involves the inability to catch an error when the MQTT broker becomes unavailable.

From the information provided, it looks like the problem might be due to the behavior of the MQTT library you're using (`mqtt` package) and how it interacts with the NestJS framework. The error you're encountering might be related to how the MQTT client handles errors and whether those errors are properly propagated to the NestJS code.

Based on the comments and updates you've posted, it appears that you initially suspected the issue might be with `mqtt-async`, but then you realized that NestJS uses `mqtt` under the hood. You've also mentioned that the issue persists even after the port line in the docker-compose file has been uncommented.

Since this issue involves a specific codebase and its interaction with external libraries, it might be difficult to diagnose the problem without access to the complete code and context. If you believe this is a bug or an unexpected behavior in NestJS or the MQTT library, you could consider the following steps:

1. **Check for Similar Issues:** Search for similar issues in the official repositories of the libraries you're using (NestJS and MQTT). It's possible that someone else might have encountered and reported a similar problem.

2. **Isolate the Issue:** Try to isolate the issue further. Simplify your code to the minimum required to reproduce the problem. This will help you narrow down the potential causes.

3. **Contact Library Maintainers:** If you're confident that this is a bug or an issue with the libraries themselves, you can consider opening an issue in the GitHub repositories of the libraries (`nestjs/nest` and `mqttjs/MQTT.js`). Provide detailed information, including the steps to reproduce the issue and your code snippets.

4. **Consider Workarounds:** While waiting for a response from the library maintainers, you could try implementing a workaround in your code. This might involve custom error handling or using different methods to interact with the MQTT client.

5. **Upgrade Libraries:** Make sure you're using the latest versions of the libraries. Sometimes, issues are already resolved in newer releases.

6. **Temporary Solution:** If you believe that the issue might be related to the behavior of the MQTT library under certain conditions, you might need to consider implementing custom error handling or retries in your code to handle scenarios where the MQTT broker becomes unavailable.

**Comment by vahidvdn** [comment]
@penguin011 Thanks for your response.

The first thing is that the repo with minimum code is already provided, you can check out the `app.controller` that has a very simple `client.send` section.


The second thing is, so far I realized it's the expected behavior since there is a [timeout section](https://docs.nestjs.com/microservices/basics#handling-timeouts) in the docs.

This means it's not supposed to throw an error when the broker is down. For now, I keep it open, maybe more ideas we get regarding this. Otherwise, the maintainers can close the issue.

**Comment by carlosallexandre** [comment]
Hey @vahidvdn, is everything ok?

I didn't see this as an error from NestJS neither MQTT. When the broker goes down the MQTT raise the ECONNREFUSED error. At the `ClientMqtt` implementation [(here)](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-mqtt.ts#L97), you can see that the error is not logged. However, you can implement a custom client like below to handle the way you want:
```ts
// app.module.ts

import { Module } from '@nestjs/common';
import { ClientMqtt, ClientsModule, Transport } from '@nestjs/microservices';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { MqttClient } from '@nestjs/microservices/external/mqtt-client.interface';

class CustomMqttClient extends ClientMqtt {
  public handleError(client: MqttClient) {
    client.addListener('error', (err: any) => {
      this.logger.error(err);
      // If you close the connection, you will catch the error at app.controller
      // client.end(true);
    });
  }
}

@Module({
  imports: [
    ClientsModule.register([
      {
        name: 'MQTT_SERVICE',
        options: {
          url: 'mqtt://localhost:1883:',
          rejectUnauthorized: false,
        },
        // transport: Transport.MQTT,
        customClass: CustomMqttClient,
      },
    ]),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by vahidvdn** [comment]
Thanks @carlosallexandre Even though the way you purposed is very useful for global error handling, I wanted to do it in one specific client call. Btw I guess [timeout](https://docs.nestjs.com/microservices/basics#handling-timeouts) with the combination of `.subscribte({ next, error })`  is almost the same thing that I wanted to do

For now, I don't see any specific reason to keep this issue open. I guess I can close this.
