### ISSUE TITLE
SWC compiler doesn't work on windows, but does on MacOS

### ISSUE THREAD

**Issue by Mnigos** [nestjs/nest#12214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
$ nest start --watch
>  SWC  Running...
Successfully compiled: 103 files with swc (103.89ms)
Watching for file changes.

⠋  TSC  Initializing type checker...Error: Cannot find module './src/modules/app'
Require stack:
- /Users/igormakowski/Documents/repositories/rigtch/rigtch-music-api/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/igormakowski/Documents/repositories/rigtch/rigtch-music-api/dist/main.js:10:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
✔  TSC  Initializing type checker...
>  TSC  Found 0 issues.
```

### Minimum reproduction code

https://github.com/KirianCaumes/nestjs-bug-swc-import

### Steps to reproduce

1. npm install
2. yarn start:dev

### Expected behavior

Should work on both windows and macos.

```
$ nest start --watch
>  SWC  Running...
Successfully compiled: 103 files with swc (190.43ms)
Watching for file changes.

⠋  TSC  Initializing type checker...[Nest] 69201  - 08/10/2023, 1:51:49 PM     LOG [NestFactory] Starting Nest application...
```

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [x] Other (see below)

### Other package

@swc/cli, @swc/core

### NestJS version

10.1.3

### Packages versions

```json
{
"dependencies": {
    "@nestjs/axios": "3.0.0",
    "@nestjs/common": "^10.1.3",
    "@nestjs/config": "3.0.0",
    "@nestjs/core": "^10.1.3",
    "@nestjs/jwt": "10.1.0",
    "@nestjs/passport": "10.0.0",
    "@nestjs/platform-express": "^10.1.3",
    "@nestjs/swagger": "7.1.8",
    "@vitest/coverage-v8": "0.34.1",
    "axios": "1.4.0",
    "class-transformer": "0.5.1",
    "class-validator": "0.14.0",
    "cookie-parser": "1.4.6",
    "joi": "17.9.2",
    "pactum": "3.4.1",
    "passport": "0.6.0",
    "passport-jwt": "4.0.1",
    "passport-spotify": "2.0.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.8.1"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.7.1",
    "@commitlint/config-conventional": "^17.7.0",
    "@commitlint/types": "^17.4.4",
    "@nestjs/cli": "^10.1.11",
    "@nestjs/schematics": "^10.0.2",
    "@nestjs/testing": "^10.1.3",
    "@stryker-mutator/core": "7.1.1",
    "@stryker-mutator/jest-runner": "7.1.1",
    "@swc/cli": "0.1.62",
    "@swc/core": "1.3.75",
    "@types/cookie-parser": "1.4.3",
    "@types/express": "^4.17.17",
    "@types/node": "^20.4.9",
    "@types/passport-jwt": "3.0.9",
    "@types/passport-spotify": "2.0.1",
    "@types/supertest": "^2.0.12",
    "@typescript-eslint/eslint-plugin": "^6.3.0",
    "@typescript-eslint/parser": "^6.3.0",
    "eslint": "^8.46.0",
    "eslint-config-prettier": "^9.0.0",
    "eslint-import-resolver-typescript": "^3.6.0",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-import": "^2.28.0",
    "eslint-plugin-import-helpers": "^1.3.1",
    "eslint-plugin-nestjs": "^1.2.3",
    "eslint-plugin-prettier": "^5.0.0",
    "eslint-plugin-sonarjs": "^0.20.0",
    "eslint-plugin-unicorn": "^48.0.1",
    "husky": "^8.0.3",
    "lint-staged": "^13.2.3",
    "node-mocks-http": "1.12.2",
    "prettier": "^3.0.1",
    "source-map-support": "^0.5.21",
    "ts-loader": "^9.4.4",
    "ts-node": "^10.9.1",
    "tsconfig-paths": "4.2.0",
    "typescript": "^5.1.6",
    "unplugin-swc": "1.3.2",
    "vitest": "0.34.1",
    "vitest-mock-extended": "1.2.0"
  }
}
```

### Node.js version

18.12.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

### Other

`.swcrc`
```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "sourceMaps": true,
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": true
    },
    "baseUrl": "./"
  },
  "minify": false
}
```
`nest-cli.json`
```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "builder": "swc",
    "typeCheck": true,
    "tsConfigPath": "tsconfig.json"
  }
}
```

**Comment by Mnigos** [comment]
related:
- https://github.com/nestjs/nest/issues/11937
- https://github.com/swc-project/swc/issues/7603

**Comment by micalevisk** [comment]
after cloning that repo, I'm getting this on Linux:

![image](https://github.com/nestjs/nest/assets/13461315/ed59e26c-6f4b-4a15-9255-d5daacdaac1e)

**Comment by kamilmysliwiec** [comment]
That's, unfortunately, something we can't really fix on our own - SWC struggles with absolute path imports & path aliasing on Windows so I'd highly recommend avoiding using them in your Nest applications. SWC maintainers claim that this issue is fixed https://github.com/swc-project/swc/issues/7603 but it really isn't

**Comment by kamilmysliwiec** [comment]
Let's wait for SWC fix then

**Comment by harm-less** [comment]
Still one of the few issues that have been closed but that can still be commented on 👌 

It seems a solution to the issue has gotten a bit traction lately. So to anyone interested in following this more closely I'd suggest following this issue: https://github.com/swc-project/swc/issues/7806#issuecomment-1682804980

The workaround to anyone still having the problem at the moment is to add the same paths from your tsconfig file into your `.swcrc` file as well. But with the paths pointing to your dist folder. This is what it could look like in the end:

`tsconfig.json`
```json
{
	"compilerOptions": {
		...

		"paths": {
			"@core/*": ["src/app/core/*"],
			"@services/*": ["src/app/services/*"],
			"@entities/*": ["src/app/entities/*"],
			"@modules/*": ["src/app/modules/*"],
			"@graphql/*": ["src/app/api/graphql/*"],
			"@rest/*": ["src/app/api/rest/*"],
			"@factories/*": ["src/factories/*"],
			"@seeds/*": ["src/seeds/*"],
			"@test/*": ["src/test/*"]
		}
	},
	...
}
```

`.swcrc`
```json
{
	"$schema": "https://json.schemastore.org/swcrc",
	"sourceMaps": true,
	"jsc": {
		"parser": {
			"syntax": "typescript",
			"decorators": true,
			"dynamicImport": true
		},
		"transform": {
			"legacyDecorator": true,
			"decoratorMetadata": true
		},
		"baseUrl": "./",
		"paths": {
			"@core/*": ["dist/core/*"]
		}
	}
}
```

Of course eventually I assume the issue will have been fixed in SWC and those paths can be removed yet again.

**Comment by moeinrahimi1** [comment]
out of no where this error happened to me in production:
5.757 thread '<unnamed>' panicked at 'base_dir(`./`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other words, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc_ecma_transforms_module-0.177.21/src/path.rs:121:13
5.757 failed to handle: base_dir(`./`) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly. This cannot be deduced by SWC itself because SWC is a transpiler and it does not try to resolve project details. In other words, SWC does not know which directory should be used as a base directory. It can be deduced if `.swcrc` is used, but if not, there are many candidates. e.g. the directory containing `package.json`, or the current working directory. Because of that, the caller (typically the developer of the JavaScript package) should specify it. If you see this error, please report an issue to the package author.

i disabled swc and changed compiler to tsc
