### ISSUE TITLE
Devtools error: GET is not allowed for the request

### ISSUE THREAD

**Issue by vahidvdn** [nestjs/nest#12351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After setting up the devtools, as soon as I open `localhost:8000` I see the following error:

```
GET is not allowed for the request
```

### Minimum reproduction code

https://github.com/vahidvdn/nest10

### Steps to reproduce

1. Run the app
2. Open `localhost:8000` in the browser

### Expected behavior

To see the devtoolsdev tools

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

"@nestjs/devtools-integration": "^0.1.5",

### NestJS version

10.0.0

### Packages versions

```json
"@nestjs/common": "^10.0.0",
"@nestjs/core": "^10.0.0",
"@nestjs/devtools-integration": "^0.1.5",
"@nestjs/platform-express": "^10.0.0",
"nestjs-cashify": "^2.1.0",
"reflect-metadata": "^0.1.13",
"rxjs": "^7.8.1"
```

### Node.js version

19.4.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Tony133** [comment]
Hi @vahidvdn, 

"localhost:8000", what is it referring to? to the Devtools endpoint or your app? because Devtools works through the platform you don't have to connect via browsers to the enpoint, but you need to login with a github, gitlab or bitbucket account first ( see screenshot ) and then once you start app, on devtools platform you will find an endpoint that doesn't refer to your app, but it is an enpoint where devtools uses to collect the graph,etc of your app.

<img width="1002" alt="258920764-63401b4a-34f2-406a-aef0-e396ec76afb8" src="https://github.com/nestjs/nest/assets/11542387/a67ca031-689b-49ec-b1c8-5dd11212100d">

**Comment by vahidvdn** [comment]
@Tony133 Thank you. I was testing in the browser. So it was a misunderstanding from my end.

Therefore, closing the issue
