### ISSUE TITLE
Barrel import order affects application

### ISSUE THREAD

**Issue by SimonDiazAbad** [nestjs/nest#12391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was following a microservices tutorial, so I had a common file with the injection token name `AUTH_SERVICE` of the microservices. When registering the microservices transporters, the imported injection token is defined, but when injecting the `ClientProxy` of said microservice on another file via the token, it is `undefined`.

### Minimum reproduction code

https://github.com/SimonDiazAbad/nestjs-bug-minimum-reproduction

### Steps to reproduce

1. pnpm install
2. docker-compose up

### Expected behavior

`AUTH_SERVICE` should be defined in every filed it is imported.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### NestJS version

10.2.5

### Packages versions

"dependencies": {
    "@nestjs/common": "^10.2.5",
    "@nestjs/config": "^3.1.1",
    "@nestjs/core": "^10.2.5",
    "@nestjs/microservices": "^10.2.5",
    "@nestjs/platform-express": "^10.2.5",
    "express": "^4.18.2",
    "joi": "^17.10.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.8.1"
  },

### Node.js version

18.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Other

The file where the `AUTH_SERVICE` import is undefined is `libs/common/src/auth/jwt-auth.guard.ts`

#### Log error
`Error: Nest can't resolve dependencies of the JwtAuthGuard (?). Please make sure that the argument dependency at index [0] is available in the ReservationsModule context.`

#### Fixes
1. Invert the exports in `libs/common/src/auth/jwt-auth.guard.ts`
2. Import `AUTH_SERVICE` directly from `libs/common/src/constants/index.ts`

I tried to minify this from my project, sorry if it wasn't enough. I also updated @nestjs libraries and the issue persists.

#### Environment
- WSL2: latests version
- Ubuntu 22.04.02 LTS: latests version with updated packages
- Docker Desktop: latest version

**Comment by SimonDiazAbad** [comment]
I want to add that this issue has been previously mentioned here #1181 and I doesn't happen in a simple barebones NodeJS environment.

**Comment by micalevisk** [comment]
I believe that's expected due to circular imports that you might have introduced when using barrel files. That's a limitation that the fw cannot solve solely. You must resolve the circularity or use forwardRef, I guess

**Comment by jmcdo29** [comment]
This is a side effect of circular file imports, and we have a warning about this [in our docs](https://docs.nestjs.com/faq/common-errors#cannot-resolve-dependency-error). Essentially, a imports b imports c imports a. It might not be that they all depend on each other, but due to the way barrel files and the import statements work.

In your example, you have `libs/common/src/auth/jwt-auth.guard.ts` import from `@apps/common` which points to `libs/common/src/index.ts`, but that `index.ts` points to `libs/common/src/auth/index.ts` and `libs/common/src/constants/index.ts`, and `libs/common/src/auth/index.ts` points at `libs/common/src/auth/jwt-auth.guard.ts`, so you have this file pointing at itself for imports, and an infinite resolution is being attempted by Node which eventually returns `undefined`. It _happens_ to work if you flip the order because the `constants` import is being resolved first, but that infinite resolution is still lurking under the hood waiting to rear up again.

You should **always** exercise caution with barrel imports to make sure you do not create any of these infinite file import chains, as they can lead to difficult to debug situations. This is not a problem of the framework, but a side effect of how Node itself works. Circular imports are generally non-deterministic, which is why Nest offers the `forwardRef` approach of dealing with these to the best of its abilitiy
