### ISSUE TITLE
prefix option for serverStaticAssets not working

### ISSUE THREAD

**Issue by karimsqualli** [nestjs/nest#1293]
## I'm submitting a

[ ] Regression 
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

setting prefix of `useStaticAssets` do not add prefix to static folder url

```
 app.useStaticAssets(join(__dirname, '..', 'public'), {
    index: false,
    redirect: false,
    prefix: 'public'
  });
```

`localhost:3000/public/image.jpeg ` give 404 error, if i remove the `prefix` key from `useStaticAssets` options, and try this link  `localhost:3000/image.jpeg `, it is working correctly

**Comment by kamilmysliwiec** [comment]
Could you share a reproduction repository (+ details about your Nest version)

**Comment by seanmcilvenna** [comment]
This is an issue for me, as well. I don't think this should have been closed.
I have this: 

```
  app.useStaticAssets(path.join(__dirname, '/../client'));
  app.useStaticAssets(path.join(__dirname, '/../igs'), { prefix: '/igs' });
```

When I go to /igs it does not work. Is this not what "prefix" is used for?

**Comment by seanmcilvenna** [comment]
Nevermind... I discovered that it IS working.
It seems that if the directory does not exist on the server, express.js does not create a route for it.
In my case "../igs" did not yet exist. I was expecting to get a 404, but instead if just bypassed the route entirely and redirected me back to / due to a catch-all I have implemented.
