### ISSUE TITLE
Add custom exception on Versioning

### ISSUE THREAD

**Issue by maioradv** [nestjs/nest#13302]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When you use a wrong version or request for a route that is not availabe for your version the system throws a 404 exception

### Describe the solution you'd like

any way to customize the exception that versioning throws

### Teachability, documentation, adoption, migration strategy

usting a custom intereceptor for example

### What is the motivation / use case for changing the behavior?

returning a 404 is just a different kind of error then a mismatched version, handling the error in a proper way is base for a simple debug

**Comment by kamilmysliwiec** [comment]
> When you use a wrong version or request for a route that is not availabe for your version the system throws a 404 exception

It throws 404 because the route does not exist.

If you have, let's say, version 1 and the `/users` endpoint then the `/v1/users` endpoint is registered. If you call `/v2/users` then you get 404 as there's no `/v2/users` route. If we wanted to have a custom error instead, then we'd have to register an additional route (with a regular expression/pattern in the path) for every single versioned route in the project. 

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
