### ISSUE TITLE
Need a solution for scaffolding entites for existing tables

### ISSUE THREAD

**Issue by mgkrishna10** [nestjs/nest#13932]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

As a new person who is using **NESTJS** predominatly coming from **Spring Boot** background, I am finding difficulty in migrating some of code from spring boot to nestjs. In that process I have to spend more time in writing/editing boilerplate code even though scaffolding is generating the required files. 

### Describe the solution you'd like

.

### Teachability, documentation, adoption, migration strategy

.

### What is the motivation / use case for changing the behavior?

My motivation is solely to bring ease of writing entites for existing database

**Comment by micalevisk** [comment]
Hi! You didn't describe what's the solution you're looking for, so we can't help you much.

But in nodejs ecosystem we have a lot of approaches for 'table entities'. In order to keep nestjs flexible enough and reduce the maintenance burden, the default NestJS schematics (`@nestjs/chematics` package) won't have means to generate those entities.

As mentioned in the docs site, you can supply your own schematics collection to NestJS's CLI. And I believe that this should solve your scaffolding issues
