### ISSUE TITLE
@nestjs/microservices should handle RabbitMQ bindings and auto-generated queues

### ISSUE THREAD

**Issue by pitazzo** [nestjs/nest#13931]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The behavior of `@nestjs/microservices` while creating a new microservice app does not match the behavior expected to the regular `amqplib` package. So far, for a configuration as this, I've encountered this mismatch in two situations:

```
  const app = await NestFactory.createMicroservice(AppModule, {
    transport: Transport.RMQ,
    options: {
      urls: ['amqp://localhost:5672'],
      queue: '',
      queueOptions: {
        exclusive: true,
      },
      noAck: false,
      exchange: 'a.b.c',
      routingKey: 'x.y.*.z',
    },
  });
  await app.listen();
```

- Passing an empty string as queue name won't create an exclusive queue with a name in the form `amq.gen-cf6fXOViIyb...`, instead creates one called `default`.
- Specifying `exchange` and `routingKey` should bind the queue to the exchange, and that does not happen.

### Describe the solution you'd like

For the given situations:
- The queues should be named in the expected format
- The binding should automatically happen

### Teachability, documentation, adoption, migration strategy

- In the RabbitMQ docs should be covered in detail which parameters can be passes to the `options` object.
- Final behavior should be the same as described [here](https://www.rabbitmq.com/tutorials/tutorial-three-javascript).

### What is the motivation / use case for changing the behavior?

With the current behavior, some basic features of RabbitMQ can be achieved out of the box. Instead, some manual tweaking is needed.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? @pitazzo

**Comment by EeeasyCode** [comment]
@pitazzo @kamilmysliwiec 
Hi, there! Would it be acceptable for me to contribute a PR to address this issue? I’m a student with a lot of time and a deep love for NestJS, so I’m eager to take on this challenge.

Currently, I’ve identified the cause of the issue where the queue name defaults to “default,” and I’ve managed to resolve it. However, I’m not entirely confident in the code quality of my solution. Below is part of my ongoing problem-solving process!
AS-IS
```typescript
public async setupChannel(channel: Channel, resolve: Function) {
    const prefetchCount =
      this.getOptionsProp(this.options, 'prefetchCount') ||
      RQM_DEFAULT_PREFETCH_COUNT;
    const isGlobalPrefetchCount =
      this.getOptionsProp(this.options, 'isGlobalPrefetchCount') ||
      RQM_DEFAULT_IS_GLOBAL_PREFETCH_COUNT;

    if (!this.noAssert) {
      await channel.assertQueue(this.queue, this.queueOptions);
    }
    await channel.prefetch(prefetchCount, isGlobalPrefetchCount);
    await this.consumeChannel(channel);
    resolve();
  }
```
The reason the queue name was set to “default” was due to <code>this.queue = RQM_DEFAULT_QUEUE</code>, where <code>RQM_DEFAULT_QUEUE = 'default'</code>. This caused the queue to be created with <code>await channel.assertQueue('default', this.queueOptions);</code> instead of dynamically generating a unique queue name with <code>await channel.assertQueue('', this.queueOptions);</code>.

TO-BE
```typescript
// packages/microservices/client/client-rmq.ts

public async setupChannel(channel: Channel, resolve: Function) {
    const prefetchCount =
      this.getOptionsProp(this.options, 'prefetchCount') ||
      RQM_DEFAULT_PREFETCH_COUNT;
    const isGlobalPrefetchCount =
      this.getOptionsProp(this.options, 'isGlobalPrefetchCount') ||
      RQM_DEFAULT_IS_GLOBAL_PREFETCH_COUNT;

    if (this.queue === RQM_DEFAULT_QUEUE) {
      const assertQueue = await channel.assertQueue('', this.queueOptions);
      this.queue = assertQueue.queue;
    } else {
      if (!this.noAssert) {
        await channel.assertQueue(this.queue, this.queueOptions);
      }
    }

    await channel.prefetch(prefetchCount, isGlobalPrefetchCount);
    await this.consumeChannel(channel);
    resolve();
  }

```

Success TestCode
```typescript
describe('Queue Auto-Generation', () => {
    it('should automatically generate a queue name if queue is empty', async () => {
      const client = new ClientRMQ({
        queue: '',
      });

      await client.connect();
      expect(client['queue']).to.match(/^amq\.gen/);
    });
  });
```

<img width="404" alt="image" src="https://github.com/user-attachments/assets/415fdc2f-b123-4cf2-8cba-5652f2e15b8c">

**Comment by EeeasyCode** [comment]
I have identified the root cause of all issues as of 3:07 AM on November 11th (KST) and successfully tested the fixes for the NestJS microservices issue locally. The changes are now functioning as expected. May I proceed with contributing a PR for this issue?

<img width="495" alt="스크린샷 2024-11-11 오전 3 08 25" src="https://github.com/user-attachments/assets/61a83ad3-39d9-4636-be3a-24618ba30dce">
<img width="608" alt="스크린샷 2024-11-11 오전 3 08 48" src="https://github.com/user-attachments/assets/5fd5a739-b2cc-4db7-923e-5bdf36db9cff">
<img width="639" alt="스크린샷 2024-11-11 오전 3 08 54" src="https://github.com/user-attachments/assets/d08fef3c-4bbd-40cb-82c2-6c9d0d5232f6">

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/14129

**Comment by matheusb-comp** [comment]
@kamilmysliwiec The autogenerated queue name issue still exists. From what I understood, the problem is [this constant](https://github.com/nestjs/nest/blob/5fd9e2ecb4f4890df4afe0bc4a1210225875df9b/packages/microservices/constants.ts#L17).

In the PR #14129 it was changed to an empty string, but apparently it was changed back to `'default'` on PR #14142 [here](https://github.com/nestjs/nest/pull/14142/files#diff-f38c65cbec5a1efe09118f4ed9ec65ee80a1cd563dc554569cd2e3871594742aL36).

**Comment by EeeasyCode** [comment]
@kamilmysliwiec @micalevisk @matheusb-comp 

https://github.com/nestjs/nest/pull/15250

Hello, I’m the contributor who previously worked on resolving the related issue. I’ve submitted this PR to address a follow-up problem. I would be grateful if you could kindly review it at your convenience. Thank you!
