### ISSUE TITLE
Interceptor doesn't work with `StreamableFile`

### ISSUE THREAD

**Issue by amitalkobi** [nestjs/nest#13949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Interceptor ([timeout](https://github.com/amitalkobi/nestjs-timeout-interceptor/blob/ffdeeccb5469e4bb18f529346cfcf277580e07f2/src/timeout.interceptor.ts#L13)) doesn't early return the response when the controller method returns a `StreamableFile`.

### Minimum reproduction code

https://github.com/amitalkobi/nestjs-timeout-interceptor/blob/ffdeeccb5469e4bb18f529346cfcf277580e07f2/src/fooController.ts#L31

### Steps to reproduce

1. Start the app in dev mode
2. Visit http://localhost:3000/foo/file
The foo/file endpoint takes 3 seconds to resolve while the [timeout interceptor](https://github.com/amitalkobi/nestjs-timeout-interceptor/blob/ffdeeccb5469e4bb18f529346cfcf277580e07f2/src/timeout.interceptor.ts#L13) sets a timeout of 10 ms
3. File is unexpectedly downloaded 

### Expected behavior

A response with code 408 should be returned.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

10.4.1

### Packages versions

```json

```

### Node.js version

20.15

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by jmcdo29** [comment]
I believe the reason here is due to _when_ the data is being read by the `StreamableFile`. Because it's an AsyncGenerator, it is being read in realtime _after_ the interceptor finishes, so the 10ms timeout can't be taken into effect. I'm not sure if there would be a way to modify this behavior, other than loading the data of the generator first and _then_ passing it to the `StreamableFile`, but that kinda goes against the idea behind streaming the response in the first place
