### ISSUE TITLE
Add example for GraphQL Relay

### ISSUE THREAD

**Issue by igo** [nestjs/nest#1395]
Please add example how to do a GraphQL for Relay with connections, edges, nodes, totalCount...
https://facebook.github.io/relay/docs/en/graphql-server-specification.html

**Comment by Simonpedro** [comment]
Have you figured out any pattern to implement Relay specification?

**Comment by ceefour** [comment]
Some community projects:

* [`nestjs-graphql-relay` npm package](https://www.npmjs.com/package/nestjs-graphql-relay) (https://github.com/piic/nestjs-plugins#readme) by @piic
* https://github.com/kazekyo/nestjs-graphql-relay example by @kazekyo

**Comment by ceefour** [comment]
Since NestJS recently incorporated its own GraphQL library (instead of using [type-graphql](https://github.com/MichalLytek/type-graphql)), I think NestJS should also explicitly support Relay connections. Most likely in the spirit of https://github.com/wemaintain/auto-relay by @wemaintain (reference: https://github.com/MichalLytek/type-graphql/issues/142#issuecomment-582132843).

**Comment by ceefour** [comment]
This is my approach inspired by (but not using the entire) https://www.npmjs.com/package/nestjs-graphql-relay:

**nestjs-graphql-relay.ts**

```ts
import { Field, ObjectType, Int } from '@nestjs/graphql';
import * as Relay from 'graphql-relay';

@ObjectType({ isAbstract: true })
export abstract class Aggregate {
  @Field(() => Int)
  readonly count: number;
}

@ObjectType()
export class PageInfo implements Relay.PageInfo {
  @Field(() => Boolean, { nullable: true })
  hasNextPage?: boolean | null;
  @Field(() => Boolean, { nullable: true })
  hasPreviousPage?: boolean | null;
  @Field(() => String, { nullable: true })
  startCursor?: Relay.ConnectionCursor | null;
  @Field(() => String, { nullable: true })
  endCursor?: Relay.ConnectionCursor | null;
}
```

**project.resolver.ts**

```ts
import { Resolver, Args, Query, ID, Mutation, Field, ObjectType, ResolveField, Parent, Int } from '@nestjs/graphql';
import { Project } from './project.entity';
import { ProjectService } from './project.service';
import { Edge, Connection, ConnectionCursor } from 'graphql-relay';
import { PageInfo, Aggregate } from './nestjs-graphql-relay';

@ObjectType({isAbstract: true})
abstract class ProjectsEdge implements Edge<Project> {
  @Field(() => Project)
  readonly node!: Project;

  @Field()
  readonly cursor!: ConnectionCursor;
}

@ObjectType()
export class ProjectsConnection implements Connection<Project> {
  @Field()
  readonly pageInfo!: PageInfo;

  @Field(() => [ProjectsEdge])
  readonly edges!: Edge<Project>[];

  @Field(() => Aggregate, {nullable: true})
  readonly aggregate?: Aggregate;
}

@Resolver(() => Project)
export class ProjectResolver {

  constructor(
    private readonly projectService: ProjectService,
  ) {}

  @Query(returns => ProjectsConnection)
  async projects(): Promise<ProjectsConnection> {
    const edges = (await this.projectService.findAll())
      .map(_ => ({node: _, cursor: _.id} as ProjectsEdge));
    const startCursor = edges.length >= 1 ? edges[0].cursor : undefined;
    const endCursor = edges.length >= 1 ? edges[edges.length - 1].cursor : undefined;
    return {
      pageInfo: {hasPreviousPage: false, hasNextPage: false, startCursor, endCursor},
      edges};
  }
}
```

**Comment by steinroe** [comment]
I just came across this repo: https://github.com/rogerballard/nestjs-relay

Looks really interesting, did anyone try this out?

**Comment by calmonr** [comment]
@steinroe I really liked this one and how it's implemented (starred), the only problem tho is that it doesn't actually helps you paginate on your database.

If you want to use the `nestjs-relay` with a database pagination you just have to use something like that [connectionFromRepository](https://github.com/calmonr/typegraphql-relay/blob/main/src/relay/connection.factory.ts) instead of using `connectionFromArray` (`graphql-relay`). That was how I implemented on [typegraphql-relay](https://github.com/calmonr/typegraphql-relay).

I'm currently changing a few things as I plan on adding more features to the boilerplate but time is not helping me much (busy times).

**Comment by steinroe** [comment]
Just as a note: We opted for [query-nestjs ](https://doug-martin.github.io/nestjs-query/), because we do not need a 100% relay-conform implementation and rather just sophisticated query methods with sorting, filtering and pagination. The package provides those out-of-the-box, along with a lot of other great features. It increases developer efficiency a lot, especially in early stages of development.

**Comment by egru** [comment]
I've been banging my head trying to figure out the root node queries when I implement a node interface. My resolver just complains when I return an object that implements a node.

```{
  "errors": [
    {
      "message": "Return type for \"Node\" cannot be resolved. If you did not pass a custom implementation (the \"resolveType\" function), you must return an instance of a class instead of a plain JavaScript object."
    }
  ],
  "data": {
    "node": null
  }
}

I've looked at https://github.com/kazekyo/nestjs-graphql-relay, https://github.com/calmonr/typegraphql-relay, and https://github.com/rogerballard/nestjs-relay which all implement the node interface in roughly the same way, but man, I can't get it working.

**Comment by calmonr** [comment]
@egru How is your resolver for `node` defined?

https://github.com/calmonr/typegraphql-relay/blob/f22319ba542aaa998cbd4c6b359dd843888dbd12/src/relay/node.resolver.ts#L45-L55

**Comment by egru** [comment]
Here's the resolver:
```javascript
@Resolver(() => Node)
export class NodesResolver {
  constructor(private readonly nodeService: NodesService) {}

  @Query(() => Node, { nullable: true })
  node(@Args({ name: 'id', type: () => ID }) id: string): Promise<Node | undefined | null> {
    const globalId = fromGlobalId(id);
    switch (globalId.type) {
      case 'User':
        return this.nodeService.findUser(globalId.id);
      case 'Product':
        return this.nodeService.findProduct(globalId.id);
      default:
        break;
    }
    return null;
  }
}
```
And here's the interface
```javascript
@InterfaceType()
export abstract class Node {
  @Field(() => ID)
  id: string;
}
```

**Comment by calmonr** [comment]
@egru I think that you should post your entire code, this way more people might try to help you out. You can use gist for that or create a repository with the problem.

**Comment by egru** [comment]
@calmonr sure, here's a quick repo that has the issue https://github.com/egru/nestjs-graphql-relay

**Comment by valentingc** [comment]
> @calmonr sure, here's a quick repo that has the issue https://github.com/egru/nestjs-graphql-relay

I guess the problem is that TypeORM in this case does not properly instantiate a class instance but rather a plain JS object. I could reproduce the error myself in my repository - I encountered it with TypeORM in combination with MongoDB.
My solution for this problem was to manually override the resolveType function of the InterfaceType like so:
```
@InterfaceType({
  resolveType: (value) => {
    if ('username' in value) {
      return User;
    }
    // and so on ...
  },
})
export abstract class Node {
  @Field(() => ID)
  id: string;
}
```
It's a bit painful but sadly I got no other solution right now, without making everything much more complex.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
