### ISSUE TITLE
type narrowing `context` parameter on `createParamDecorator`'s callback

### ISSUE THREAD

**Issue by micalevisk** [nestjs/nest#14093]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

![demo](https://github.com/user-attachments/assets/99ca9767-7bf3-4bf6-8774-706543179b0d)

the type of `context` parameter of `createParamDecorator`'s callback is always `any`

### Describe the solution you'd like

narrowing that parameter type to `ExecutionContext`

I'm not 100% sure but it looks like `context` is always `ExecutionContextHost` which implements`ExecutionContext`.

https://github.com/nestjs/nest/blob/7843db3984af97e98b5486ad142fd5bcf438a3f2/packages/core/helpers/context-utils.ts#L77-L85

### Teachability, documentation, adoption, migration strategy

add a mention in the migration guide (v10 to v11)

### What is the motivation / use case for changing the behavior?

since NestJS itself is written in typescript, I think that we could avoid using `any` whenever it makes sense. This would help people to write their code without needing to check out the docs site

**Comment by EeeasyCode** [comment]
Can I contribute to this issue?

**Comment by micalevisk** [comment]
@EeeasyCode Sure. But I'm waiting Kamil's feedback first

**Comment by EeeasyCode** [comment]
@micalevisk Well noted with thanks!

**Comment by EeeasyCode** [comment]
@micalevisk 
I’ve proactively implemented modifications related to this issue, anticipating potential feedback from Kamil. I would greatly appreciate any feedback you can provide [on this PR](https://github.com/nestjs/nest/pull/14126).

Testing has shown that the ctx parameter in createParamDecorator is now properly typed as ExecutionContext, rather than any, ensuring enhanced type safety. 

<img width="773" alt="image" src="https://github.com/user-attachments/assets/eb29e243-1043-4028-beb8-1ca03665ec52">
