### ISSUE TITLE
[Mqtt]The rule of topic is too strict that I can not use topic like "xx/xx/+" 

### ISSUE THREAD

**Issue by phper-chen** [nestjs/nest#1420]
## Current behavior

For example, I subscribe to a topic to communicate with all devices, such as "aaa/bbb/+", "+" represents the number of each device, and then handles the business logic of each device based on the business represented by "+". However, nest often adds the suffix "ack" to my topic, which leads me have no way to handle such a scene.

## Expected behavior

I think nest should release the topic rules, otherwise I can't use or migrate old projects to nest

**Comment by phper-chen** [comment]
I think this framework is very good, but the author's attitude towards the document is a bit lazy, and the questions raised by everyone are not positive. The result is that the audience is getting less and less, and you have created this framework in vain.

**Comment by kamilmysliwiec** [comment]
The way to publish and subscribe to events without extra suffixes (both `res` and `ack`) will be provided in the next major release (6.0.0) #1350

**Comment by phper-chen** [comment]
> The way to publish and subscribe to events without extra suffixes (both `res` and `ack`) will be provided in the next major release (6.0.0) #1350

Thanks, I just think you need more people to help you maintain this framework.😄

**Comment by kamilmysliwiec** [comment]
So far I cannot even work full-time on this framework. Gathering sponsors is very difficult in the OpenSource world :)

**Comment by phper-chen** [comment]
> So far I cannot even work full-time on this framework. Gathering sponsors is very difficult in the OpenSource world :)

Can only expect more people with good skills to contribute to the “nestjs”.⛽️

**Comment by shekohex** [comment]
@phper-chen 
We already exists, behind the scenes 😅 as Kamil said before.
We just need some how a plan, something to organize what we need to do, who will handle this task, and so on.
Kamil already doing pretty awesome, we are just asking him to organize that.

**Comment by appsolutegeek** [comment]
@phper-chen You could always get involved yourself or raise bugs/feature requests so that somebody can pick them up.

You need to realise that people do this in their free time. Google is not behind this. If it doesn't meet what you need then don't use it. Nobody is forcing you.

I think your comments were not very conducive, what we don't want is for the framework to disappear - I love it.

Sometimes it takes time to get a solution, search in the forums. Its what I do.

I personally want this framework to grow - IMHO its better than anything else out their - BUT its open source.
