### ISSUE TITLE
Reuse the connection of a microservice transport in a client or client proxy

### ISSUE THREAD

**Issue by pedroCore** [nestjs/nest#14268]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

In the current microservice implementation we need to define a transport to connect and subscribe to use the @MessagePattern and the @EventPattern. But most use cases implies bi-directional communication with the same broker or peer which we need to create and register a Client that creates a second connection.

Transport use cases:
- MQTT
- Kafka
- Redis
- ...

Tested with MQTT connected to an EMQX instance.
The current way around this is to completely ignore the @nestjs/microservice and create my own abstraction or live with two redundant connections, which in scenarios with TLS termination, JWT authorization and thousands of devices connected is no good.

### Describe the solution you'd like

Implementation of a way to optionally reuse the same connection used by the NestFactory.createMicroservice in the client registration

### Teachability, documentation, adoption, migration strategy

I would say to:

1. Modify the `MicroserviceOptions` to accept a property  (`connectionKey` or` id`) to identify the connection
2. Internally define a way to use the connection created by the NestFactory.createMicroservice<MicroserviceOptions>(
3. Modify the `ClientsModuleOptions` to accept a property (`reuseFromCore`) to bind to the microservice base connection defined by the `connectionKey` or` id`

I don't know if this is that simple or if it violates some of the architectural stand points defined.

### What is the motivation / use case for changing the behavior?

Boosting performance and reduce connection redundancy in bi-directional communication between the microservice and potential brokers.

**Comment by iiAku** [comment]
This should land in next major release of nest.js the unwrap might help you achieve this.
At work we struggled a little bit initialy to extract the connection in order to reuse the same from microservice, we needed that for healthcheck on kafka, making sure we were able to validate the ongoing being used connection is still healthy.

To do so we leverage custom strategies, see: https://docs.nestjs.com/microservices/custom-transport
Then for instance for Kafka you can extends/expose what you need as the properties (consumer/producer) are protected so basically you can expose them
see: https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-kafka.ts

I presume this is doable for other transports and again it will land very soon in the upcomming nestjs version 11.x (https://github.com/nestjs/nest/tree/11.0.0).

**Comment by kamilmysliwiec** [comment]
You can achieve that using custom strategies (as @iiAku mentioned above) and potentially with the `unwrap` feature too, which is set to be introduced in v11 (see v11 PR for more details).

Beyond that, there are no current plans to implement additional functionality.
