### ISSUE TITLE
Documentation for scaling websocket gateways horizontally 

### ISSUE THREAD

**Issue by JeetChaudhari** [nestjs/nest#1442]
## I'm submitting a...
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[*] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

Please add documentation on how to horizontally scale web socket implemented using gateways with Nest.

**Comment by mickz18** [comment]
Are you looking to  [Redis adapter](https://docs.nestjs.com/websockets/adapter) to interconnect several app instance ?

**Comment by Destreyf** [comment]
@JeetChaudhari 

In order to handle websockets and scale horizontally you'd have to use a different adapter and for the websocket gateway to be aware of connections to other hosts, as @cojack states scaling can be done a layer up, but this doesn't take into account how to communicate across multiple instances (a requirement **IMO** for scaling websockets).

The best way to do this **IMO** is to use the redis adapter that @mickz18 has mentioned, this requires you to have a redis server setup that all of your websocket gateways can talk to, this isn't specific to nestjs and some common knowledge for socket.io  & redis could go a long way to helping understand how to accomplish this.

@marcus-sa i am unsure why there was a thumbs down without a simple response pointing to the documentation, i understand that this is out of scope for nestjs as having a general understanding of socket.io (or other socket libraries) and sharing information via some pub/sub mechanism (redis for example) would be required to accomplish this in a sane way.

**Comment by kamilmysliwiec** [comment]
Just use Redis adapter as has been shown here https://docs.nestjs.com/websockets/adapter

**Comment by JeetChaudhari** [comment]
@mickz18 @Destreyf @kamilmysliwiec Thank you for the response, I was looking for redis adapter and how to set up. It seems I missed the adapter section in docs. Thank you for pointing out.
