### ISSUE TITLE
Catastrophic looping reconnect/fails with RabbitMQ ClientProxy (ClientRMQ) griding system to death

### ISSUE THREAD

**Issue by patricknazar** [nestjs/nest#1571]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When using ClientProxy with RabbitMQ, if the initial connect has been made and an exclusive queue has been created and the broker breaks the connection, the client will reconnect and create an endless loop of errors like `operation basic.consume caused a channel exception not_found: no queue 'amq.gen-fYW37X8urhlAvZ1dIugkog' in vhost '/'`. It will reconnect and happen over and over.

## Expected behavior

Well seeing as exclusive queues are destroyed once the connection ends, I'm not too sure. One option might be to just create a new queue and forget about the previous responses, or change the way the reply queues are made altogether but I'm not sure about how to go about this. One thing is for sure it's a serious problem and grinds my system down to a halt and overloads logs.

## Minimal reproduction of the problem with instructions

It's hard to reproduce automatically. The problem can be manually shown with rabbitmq:3-management docker image and by using the web interface and force disconnecting a client connection.

## What is the motivation / use case for changing the behavior?

In my real application one microservice was using ClientProxy to talk to a queue and if that microservice jammed up and didn't respond fast enough rabbitmq would sever it's connection and upon ClientProxy reconnect the cascade of hell would start. It is trying to consume a reply queue which couldn't possibly be there, which makes rabbitmq kill the channel and it loops over again. It's really bad.

## Environment

<pre><code>
Nest version: 5.4.0, that code hasn't changed in latest version

 
For Tooling issues:
- Node version: 8.15.0  
- Platform:  Linux 

Others:
RabbitMQ 3.7.11
ampq-connection-manager 2.2.0
amqplib 0.5.2

</code></pre>

**Comment by WonderPanda** [comment]
Please share the configuration for the microservice that is causing issues (whatever you're passing to `NestFactory.createMicroservice()`). 

`amq.gen-fYW37X8urhlAvZ1dIugkog` looks like an auto generated queue name which seems strange.

**Comment by patricknazar** [comment]
It isn't strange, it's the way the reply queue works. [This line in ClientRMQ](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-rmq.ts#L115) creates it. It is an exclusive queue which will only live during the connection. And as the connection is severed the queue disappears yet upon reconnect it tries to consume that queue again (impossible). There is a fundamental flaw here. As for my configuration isn't nothing special, just:

```
{
    urls: [`amqp://rabbitmq:5672`],
    queue: 'my_service',
    queueOptions: { durable: true },
}
```

**Comment by WonderPanda** [comment]
Hmmm this does seem like an issue with the implementation. It would be better to use the built in Direct-Reply queue instead of creating an anonymous one like this.

You might consider looking at the library I've been working on [`@nestjs-plus/rabbitmq`](https://github.com/WonderPanda/nestjs-plus/blob/master/packages/rabbitmq/README.md) as it provides more options/functionality for using RabbitMQ from your NestJS apps. Current it supports flexible options for leveraging multiple exchanges and queues as well as patterns for RPC (using Direct Reply To) and Pub/Sub.

I have plans on integrating with amqp-connection-manager for RMQ clusters to fill in the rest of the holes this week so it might be too early for you.

You could also take a look at my implementation of an [`AmqpConnection`](https://github.com/WonderPanda/nestjs-plus/blob/master/packages/rabbitmq/src/amqp/AmqpConnection.ts) which wires up the Direct Reply To queue. It may be something which we can PR back into the ClientRMQ but for now my focus is on getting the rest of the packages from `@nestjs-plus` ready for stable release.

**Comment by patricknazar** [comment]
Cool. I'll try it out soon, thanks.

**Comment by kamilmysliwiec** [comment]
@patrickhousley Thanks for reporting, I'll fix it asap

**Comment by kamilmysliwiec** [comment]
Should be fixed by #1576

**Comment by patricknazar** [comment]
Hey thanks for the quick response! I'll check it out little later today.

**Comment by patricknazar** [comment]
Is there any way for me to use this before release?

**Comment by kamilmysliwiec** [comment]
5.7.3 has been published. Please, update and let me know :)

**Comment by patricknazar** [comment]
@kamilmysliwiec working great as far as I can tell. Thank you!!
