### ISSUE TITLE
naming of async method

### ISSUE THREAD

**Issue by tanekim77** [nestjs/nest#1618]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

In node, async methods do not have Async postfix, but sync methods have Sync postfix.
For example, readFile method has these 2 methods
Async: fs.readFile(
Sync: fs.readFileSync(

But, nest seems to be doing the opposite,
For example,  Nest's startAllMicroservices has 2 methods
Async: app.startAllMicroservicesAsync
Sync: app.startAllMicroservices

Different naming convention can confuse a lot of new comers.

## Expected behavior

The opposite of current behavior

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
There are 2-3 methods in the whole Nest ecosystem that follow this convention. The reason is that `sync` methods were introduced first and we didn't want to introduce needless braking changes. I don't think that we have to necessarily follow Node.js postfixes taking into account that it would force everyone else to change existing codebases.
