### ISSUE TITLE
Redis client created with CacheManager does not close when app quits

### ISSUE THREAD

**Issue by kyle-mccarthy** [nestjs/nest#1621]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When the nest application quits, it doesn't close the redis client.

## Expected behavior

When app.quit() it should trigger the CacheModule to cleanup resources that it is using.

## Minimal reproduction of the problem with instructions

Here is a gist that can be used to verify the resource isn't cleaned up. It would be expected that redis would emit the `end` event, indicating that it is quitting.

https://gist.github.com/kyle-mccarthy/b13e053516ea54a9cc8895a8163b04d9

## Environment

<pre><code>
Nest version: 5.7.3

 
For Tooling issues:
- Node version: 10.14.1
- Platform:  mac

</code></pre>

**Comment by kamilmysliwiec** [comment]
When using redis store, you have to trigger `close` event manually because the library itself doesn't provide this functionality in the public API https://github.com/dabroek/node-cache-manager-redis-store. I'd suggest triggering close in the `onModuleDestroy()`. Also, I think that it might be worth adding to the official docs then.
