### ISSUE TITLE
Allow dependency injection to apply to sub modules

### ISSUE THREAD

**Issue by jacobEAdamson** [nestjs/nest#163]
Currently, if you specify a component to be injected, it only injects it for the current module, and any module that relies on the exported component. This is useful, but it's slightly different than the dependency injection model used by Angular. In angular, injecting a dependency at a top level module injects that dependency globally. This allows for simple configuration of injectables at the top level.

- TopModule
  - Component with Test dependency
  - SubModule
    - { provide: Test, useClass: AlphaTest }

In this case, Component gets the AlphaTest, which is good

- TopModule
  - { provide: Test, useClass: AlphaTest }
  - SubModule
    - Component with Test dependency
    - Test

Component gets a Test object instead of an AlphaTest object, which is different than in angular.

Since the documentation references angular in many cases, I believe it would be good to either make the documentation more clear on the differences between the two, or to make the second case inject AlphaTest instead of Test into the children modules (so it matches angular's injection behavior). I only suggest this because I thought it would act one way, and spent several hours scratching my head before running some tests and discovering it didn't work exactly like I thought it would. Thanks!

**Comment by kamilmysliwiec** [comment]
Hi @jacobEAdamson,
Yes, that's true. The nest injection model is slightly different than the Angular one, because the concept is different. As you mentioned, Angular registers the injectable in the global scope so it's possible to inject dependency in the sub-modules, while Nest's trying to encapsulate the components in their modules. It won't change in the future, but I agree that it'd be good to create a chapter in the documentation to just clear the differences between them. 
Thanks,
Kamil
