### ISSUE TITLE
Nestjs pre-load providers

### ISSUE THREAD

**Issue by underfisk** [nestjs/nest#1631]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

I want to load some services, providers or even just some instances before nestjs starts.
The reason behind this is i have a lot at adapter level with websockets and that requires for example data models (nest provider) and i can't access it and need to create a lot of work around in order to get it

## Expected behavior

What if nestjs contain some area that could really use services/providers at adapter/outside level? that would be awesome to load some of this inside services and ensure that everything is initialized before the adapter or something starts

## What is the motivation / use case for changing the behavior?

In my current project we need this, i have a work around but i think if nestjs support this, that would be great

## Environment

<pre><code>
Nest version: > 10

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Async providers can act as a sort of pre-load providers https://docs.nestjs.com/fundamentals/async-providers

In terms of the DI inside adapters, we're tracking this issue elsewhere already #1612

**Comment by underfisk** [comment]
Hi thanks for the reply, and sorry for quite a duplication request.
Async providers work inside modules which means if you have some model (as a provider) inside a module but you wan't to access it and have it instantiated before you can'.t
Giving you an easy example, if you want to store a jwt blacklist in some kind of external storage (mysql or whatever) and you wan't to only allow websocket user's access your platform with a non blacklisted token, you'll need to provide a middleware in Adapter for socketio and for that middleware you need to have the model access.
This is one of the problems using Nest that i encountered

**Comment by kamilmysliwiec** [comment]
> Giving you an easy example, if you want to store a jwt blacklist in some kind of external storage (mysql or whatever) and you wan't to only allow websocket user's access your platform with a non blacklisted token, you'll need to provide a middleware in Adapter for socketio and for that middleware you need to have the model access.

It's not a big deal actually - you can use an interceptor for that. Interceptors can inject dependencies which means that you can have a direct model access.

**Comment by underfisk** [comment]
So to get an idea, how would you get access to them in Adapter? Because it is easy to do for http but using socketio, you have to specify a middleware and that middleware has to have the instance before the server starts listening.

**Comment by kamilmysliwiec** [comment]
It's not possible yet with adapters #1612

**Comment by underfisk** [comment]
Alright, thanks
I'll wait for further updates

**Comment by kavitha1991dhiman** [comment]
Has anyone got a fix for this. My requirement is to load a entire module even before other get loaded, but I am not able to achieve that with Async providers. The module A is not being initialized completely and the other module B is initiated which is dependent on module B and hence I am getting this following error.

(node:21560) Warning: N-API is an experimental feature and could change at any time.
[Nest] 21560   - 2019-4-2 15:33:39   [NestFactory] Starting Nest application...
[Nest] 21560   - 2019-4-2 15:33:39   [InstanceLoader] ApplicationModule dependencies initialized +29ms
[Nest] 21560   - 2019-4-2 15:33:39   [InstanceLoader] HttpModule dependencies initialized +3ms
[Nest] 21560   - 2019-4-2 15:33:39   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 21560   - 2019-4-2 15:33:39   [ExceptionHandler] Credentials must be provided when creating a service client.

This is because the elements of ConfigModule are not initialized.

**Comment by underfisk** [comment]
@kavitha1991dhiman Here the problem is not related with modules loading before/after another module, the problem is related at http adapter/ws adapter to get access to providers or some module data
