### ISSUE TITLE
Cannot get typeorm and mysql working

### ISSUE THREAD

**Issue by ShawnMercado** [nestjs/nest#175]
Hi, I followed the examples as best I could from the documentation, but no matter what I change I get this error:  

`No repository for "User" was found. Looks like this entity is not registered in current "default" connection?`

My `database.providers.ts` file looks like this

```import {createConnection} from 'typeorm';
import {userProviders} from "../UserModule/user.providers";
import {User} from "../UserModule/user.entity";

export const databaseProviders = [
    {
        provide: 'DbConnectionToken',
        useFactory: async () => await createConnection({
            type: 'mysql',
            host: 'localhost',
            port: 3306,
            username: 'root',
            password: 'root',
            database: 'mydb',
            entities: [
                __dirname + '/../**/*.entity{.ts,.js}',
            ],
            synchronize: true
        }),
    },
];
```
I tried putting the `User` entity directly into the `entities` option, but that had no effect.  I've also fiddled with that glob string about every which way possible.  I'm completely out of ideas as to what to try.

**Comment by cojack** [comment]
@ShawnMercado your `database.providers.ts` should looks like this:

```typescript
import { createConnection } from 'typeorm';

export const databaseProviders = [
  {
    provide: 'DbConnectionToken',
    useFactory: async () => await createConnection({
      type: 'mysql',
      host: 'localhost',
      port: 3306,
      username: 'root',
      password: 'root',
      database: 'test',
      entities: [
          __dirname + '/../**/*.entity{.ts,.js}',
      ],
      autoSchemaSync: true,
    }),
  },
];
```

**Comment by kamilmysliwiec** [comment]
Hi @ShawnMercado,
Can you share the repo? I can't reproduce your issue.

**Comment by ShawnMercado** [comment]
Thanks for looking into it guys.  I went through all the files again, and I finally found the discrepancy.   I forgot to put the `@Entity()` annotation on the `User` object... my bad.

It does feel like this should throw a more specific error, but I imagine that has nothing to do with nestjs and only with the typeorm library.

**Comment by kamilmysliwiec** [comment]
Hi @ShawnMercado,
Cool :slightly_smiling_face: Have a good day!

**Comment by S7R1D3R** [comment]
I am having the same problem but my Entity is well done. I also tried many ways of writing the config file in json and js to check if the problem was in the routes " __dirname + "/src/**/entities/*.entity{.ts,js}" " as well as many other attempts. I am importing the module where I have it into the main module, I'm putting the entity in the imports: [ TypeOrmModule.forFeature([ ProfessionalEntity, ApplicationEntity ]) ], but whenever I try to initialize a repository it says repository is not found.

https://imgur.com/pSzyRah
https://imgur.com/HdQwLng
https://imgur.com/8ttDEH9

This was where I were when I started to debug, but I can't really find any solution... @kamilmysliwiec
