### ISSUE TITLE
Conflict with Knex.js

### ISSUE THREAD

**Issue by chigix** [nestjs/nest#1864]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When I instantiate knex, compiling will become out of control, which makes some alert like:
```
src/endpoints/endpoints.module.ts:12:14 - error TS2339: Property 'a' does not exist on type 'EndpointsModule'.

12         this.a = 2;
                ~

    at createTSError (C:\Projects\project\node_modules\ts-node\src\index.ts:226:12)
    at getOutput (C:\Projects\project\node_modules\ts-node\src\index.ts:335:40)
    at Object.compile (C:\Projects\project\node_modules\ts-node\src\index.ts:368:11)
```

where, exactly a is a property I defined on the EndpointsModule class in Typescript.

## Expected behavior

No Compiling error.

## Minimal reproduction of the problem with instructions

If this problem is not widely reproducible, I'll upload a problem repository later.

## What is the motivation / use case for changing the behavior?

I want to use Knex.js as my Data connection manager.

## Environment

<pre><code>
Nest version: 6.0.0

 
For Tooling issues:
- Node version: v10.14.1
- Platform:  Windows

Others:

</code></pre>

**Comment by jmcdo29** [comment]
What all is happening with that? Is it just a compiling issue with ts-node? Can you use tsc to compile the project? Can you share the repository info?

**Comment by chigix** [comment]
I see. Yes, it seems compiling problem. I've not tried to use tsc compiling directly. But, it should be ensured as the same result between tsc compiling and ts-node, right?.  

I'll attach a sample repository to attach a minimal sample repository about the usage with nestjs and knex.js today.

**Comment by riadhriadh** [comment]
more repository info

**Comment by chigix** [comment]
I've created a sample branch: https://github.com/chigix/nest/tree/knex-usage-error

Although, I think I've temporarily find a place which perhaps result in the build error:
https://github.com/chigix/nest/blob/knex-usage-error/knexfile.js#L1

The js file inline requiring `ts-node` is required by the nest program, which seems a reason to transpiling error in `start:dev`.

But what makes me still not understand very well is that if I remove `DbimplModule` from `AppModule` imports: 
https://github.com/chigix/nest/blob/knex-usage-error/src/app.module.ts#L8

The interpreting could work...

**Comment by jmcdo29** [comment]
I know it's possible to use Knex with TS, though it does require jumping though a few hoops. Let me get to my computer and I'll play around with this for a bit and see what I can figure out. I think this is more an issue with Knex and Typescript than it is with Knex and Nest

**Comment by jmcdo29** [comment]
@chigix So, I wasn't able to get the same compilation error, because I was running into ts-node throwing an error about 
```shell
src/dbimpl/dbimpl.module.ts(4,55): error TS2339: Property 'decorate' does not exist on type 'typeof Reflect'.
```
However, I was able to run `npm run start:prod` which runs the removal of the `dist` folder and then `tsc -p tsconfig.build.json` to compile the project before running it with `node`. That worked and the server started with no issues.

What I may suggest is using [tsc-watch](https://www.npmjs.com/package/tsc-watch) instead of [nodemon](https://www.npmjs.com/package/nodemon) and [ts-node](https://www.npmjs.com/package/ts-node) as it has the same functionality and supports incremental compilation meaning it's really quick for start up. (Plus it's one less package, even if it is a dev dependency)

You can define you `start:dev` as follows for the same effect as nodemon:
```shell
tsc-watch --onSuccess "node dist/main.js" --onFailure "echo There was a problem compiling!"
```
and you can then combine it with other packages or scripts like [concurrently](https://www.npmjs.com/package/concurrently).

**Comment by chigix** [comment]
@jmcdo29 Sincerely, thanks for the advice. One thing makes me unable to get it well is that if `tsc-watch` could work so well, then why not directly use `tsc-watch` as default development launcher instead of the current practice of `nodemon` and `ts-node`?

**Comment by jmcdo29** [comment]
@chigix Honestly, I believe that would be more of a question for @kamilmysliwiec and the other maintainers. I believe it probably has something to do with that fact that nodemon works for Typescript and JavaScript while tsc-watch would be prevalent only for Typescript users. Personally, I use tsc-watch and absolutely love it's speed and reliability, but every developer has their own opinion. The other reason may be the maturity of ts-node and nodemon as packages in the node community. 

With both nodemon and ts-node, the stats are boasting over a million downloads a week, via npm, while tsc-watch is only reaching 36 thousand. Nodemon has been around since 2011, ts-node since 2015 and tsc-watch is still relatively new at 2017. 

I've struggled with ts-node countless times in my career (probably from user error to be honest), but I've had few to no problems with using tsc-watch. Again, it's all up to the developer.

**Comment by kamilmysliwiec** [comment]
I love the speed that `tsc-watch` provides. I'm afraid about its maturity though. Perhaps, we will switch at some point.
