### ISSUE TITLE
Cannot catch UnhandledPromiseRejection when init the app ?

### ISSUE THREAD

**Issue by Weiyu-Chen** [nestjs/nest#1872]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
I know i can catch some exception by exception filters, but it seems that errors in initializing applications will not be caught.

Eg： In a controller ：

The app will exit if throw an error directly. **That is expected!**
```js
export class TestController {
    construct(){
        this.init()
    }
    init(){
        throw new Error("the app will exit because of this uncaught error")
    }
}
```

But the app will work as normal when throw promise rejection,  **without any error output.**
```js
export class TestController {
    construct(){
        this.init()
    }
    // 
    async init(){
        throw new Error("throw error in async function will not crash the app")
    }
}
```

## Expected behavior

throw error in async function should crash the app, or at least give me some error info output.
And are there any way to catch the error globally ? Or I just have to `try catch` everywhere ?

 

## Environment

<pre><code>
Nest version: 5.3.0

 
For Tooling issues:
- Node version: v8.11.4  
- Platform:  Mac 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by quezak** [comment]
Because you're not awaiting the promise, it's handled "in the background", so Nest doesn't know anything about it -- you should get some error output from Node directly, something like this:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: ....
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. */
```

I noticed your Node version is quite old, maybe the message I'm mentioning was introduced in a more recent version?

If the code you pasted is your actual use case, then Nest already has a solution for this -- use the `OnModuleInit` interface and the `async onModuleInit()` hook instead of your `init` function ([see docs here](https://docs.nestjs.com/fundamentals/lifecycle-events))

**Comment by Weiyu-Chen** [comment]
I got what happened. My workmate set `Sentry` so some uncaught error was caught by `Sentry` , which cause no error output. Thanks for reply.
