### ISSUE TITLE
NestJS Production & Deployement

### ISSUE THREAD

**Issue by halimpuckjava** [nestjs/nest#1879]
hi

1.  how i can use Observable instead of Promise as return type (in controllers & services)
2.  how to create a build production 
3.  how to deploy nestjs in real server (cloud) 
4.  add a support for build production for nestjs application

**Comment by jmcdo29** [comment]
Hi @halimpuckjava , I'm currently using Observables instead of async/await and Promises in my code and running the build on Heroku. I've found that promises have a lot of potential once you understnad them, and I know I'm only scratching the surface. You can find the [working example here](https://zeldaplay.herokuapp.com) and you can find the [server code here](https://github.com/jcmdo29/zeldaplay/tree/master/src/server). Feel free to contact me if you have any questions!

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions.
