### ISSUE TITLE
How about renew express to fastify? (may be in future)

### ISSUE THREAD

**Issue by MaxGraey** [nestjs/nest#188]
Hi, @kamilmysliwiec
First of all, I pay tribute to the excellent job on this excited framework. Right now nest based on express that is stable and widely battle tested and I understand why you choose it. But [**fastify**](https://github.com/fastify/fastify) is pretty fast and new replacment of express, has middlewares compatible with Express and Restify and many other ways for extensibility. So have you any plan for migration to this core lib in future?

**Comment by cojack** [comment]
@MaxGraey did you try to pass the fastify instance to Nest App? Maybe the API is so in common for express that will fit for it ;>

**Comment by kamilmysliwiec** [comment]
Hi,
@MaxGraey fastify is a pretty new library. As you said express is stable and widely battle tested, that's why we're using this one instead of any other http server. We'll see what future brings to us, but for now, it's too early to make a decision.
 
@cojack unfortunately it won't work cause fastify has a different routing strategy.
