### ISSUE TITLE
How to use passport in fastify platform?

### ISSUE THREAD

**Issue by yantrab** [nestjs/nest#2100]
When i just trying to use passport, i got` UnhandledPromiseRejectionWarning: TypeError: response.status is not a function` .

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by kamilmysliwiec** [comment]
`passport` is not compatible with fastify.

**Comment by yantrab** [comment]
@kamilmysliwiec  so, do you have any idea how to implement simple name password auth with fastify?

**Comment by jmcdo29** [comment]
@yantrab, the same way you would do it in Express without passport. 

You have two post endpoints, one for signup the other for login. When a user signs up, you save the username (email, custom username, whatever) and the hashed password (using bcrypt or similar) to your database and return some type of token (or create a session) if you want them to be automatically logged in. Subsequent calls you validate the token or session to ensure the user is logged in. 

For login you would have the user send their username and credentials, retrieve the user from your database (hashed password included), and compare the two password hashes (bcrypt has a compare function built in). If the passwords match, create the session or return the token. Otherwise, it is an unsuccessful login.

**Comment by yantrab** [comment]
thanks, i started to implement auth, and i have one problem. i wont to use node-cache to cache the user with her token. the cache instance is exists in auth controller. how can i access it from gourd middleware?
