### ISSUE TITLE
Terminus: Document Disk and Memory indicators

### ISSUE THREAD

**Issue by appsolutegeek** [nestjs/nest#2104]
<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
After digging into the use of the module, I notice there are 2 additional indicators that are not documented here 

https://docs.nestjs.com/recipes/terminus

these are Disk and Memory indicators. These are really handy and would love how to use them.

Also I did try and play around with this and the disk - I had to supply a threshold. Is it possible to not supply a threshold for example ?

I think these indicators are really handy but would love to see them documented more so I can take full potential of them.

## Environment

<pre><code>
Nest version: 6.1
 
For Tooling issues:
- Node version: 11
- Platform:  MAC

Others:

</code></pre>

**Comment by BrunnerLivio** [comment]
We have automatic documentation for the terminus package:

- [MemoryHealthIndicator](https://nestjs.github.io/terminus/injectables/MemoryHealthIndicator.html)
- [DiskHealthIndicator](https://nestjs.github.io/terminus/injectables/DiskHealthIndicator.html)

Unfortunately, the doc examples are currently not human-friendly, but I have submitted a [PR on compodoc] which should fix this. 

I am trying to integrate these kinds of API documentation into the normal docs, but this will be a bigger task [nestjs/docs.nestjs.com#240](https://github.com/nestjs/docs.nestjs.com/issues/249). Until then I have to refer to the current automatic documentation, unfortunately.

> Also I did try and play around with this and the disk - I had to supply a threshold. Is it possible to not supply a threshold for example ?

I do not think a default threshold is a good idea because the size of disks can vary drastically. 
But at this point, I want to refer to the `thresholdPercent` option:

```ts
// The used disk storage should not exceed 50% of the full disk size
async () => disk.checkStorage('storage', { thresholdPercent: 0.5, path: '/' });
```

Maybe this will help you to find an appropriate value?

**Comment by appsolutegeek** [comment]
Ok, thanks and noted.
