### ISSUE TITLE
How to override post in controller

### ISSUE THREAD

**Issue by juliokriger** [nestjs/nest#2320]
Hi!

I have a restful api program.

I have a base controller for CRUD.

I would like to know how I can override the post method in a subclass of the base controller.

Thanks!

Reagards,
Julio

**Comment by fwoelffel** [comment]
You're more likely to get an answer if you provide some code sample :wink: 
Moreover, for such questions, consider posting it to [StackOverflow](https://stackoverflow.com/) rather than opening an issue here. See [CONTRIBUTING.md](https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
