### ISSUE TITLE
Apply middleware using decorator

### ISSUE THREAD

**Issue by williamwong** [nestjs/nest#235]
It would be great if, instead of only configuring middleware when setting up the module, it was possible to add middleware declaratively using decorators on the controller. For example, to apply a middleware to all methods in a controller:
```
@Controller('cats')
@Apply(LoggerMiddleware)
export class CatsController {

  @Get()
  findAll() {
    return [];
  }

}
```

Alternatively, you could choose specifically to apply them to one method at a time:
```
@Controller('cats')
export class CatsController {

  @Get()
  @Apply(LoggerMiddleware)
  findAll() {
    return [];
  }

}
```

**Comment by wbhob** [comment]
This is an interesting proposal, but it may be redundant. I do like this idea though, and would not be opposed to it being in the framework

**Comment by williamwong** [comment]
It just seems odd to me that you can configure so much about Express routing, request parameters, responses, etc. using decorators, but then drop back to configuring middleware using code, in a completely separate class from the controller at the module level.

**Comment by kamilmysliwiec** [comment]
Hi @williamwong,
The reason is that middlewares might be applied to the routes from the outside module. In my opinion, it can be confusing a little to use `@Apply()` together with the middleware from another module which does not exist in the current scope. To bind 'middleware' in a more declarative way, just use interceptors 🙂 I'm sorry, but I'm not gonna implement this. Hope you'll forgive me!
