### ISSUE TITLE
how can I publish nestjs in my hosting (node + mongo)? 

### ISSUE THREAD

**Issue by dependoneo** [nestjs/nest#2415]
I develop my backend with nestjs, but It runs in my localhost computer, I need publish the backend in my hosting. It keeps node server and MongoDB. I don't want use heroku and similar, it's possible?

THANKS

**Comment by CanKattwinkel** [comment]
This is really a question that is better answered on Stackoverflow. Also, it is not nest specific as it is the same as for e.g. an express application. If it is a real project, you might want to use supervisorctl. Because you'll be looking into 'restart of the server', log rotation and so on. There are simpler solutions like [forever](https://www.npmjs.com/package/forever) but I wouldn't rely on this in a production environment.

**Comment by kamilmysliwiec** [comment]
Please, use [StackOverflow](https://stackoverflow.com/questions/tagged/nestjs) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
