### ISSUE TITLE
question: why doesn't Javascript have optional static typing ? 

### ISSUE THREAD

**Issue by catastrop** [nestjs/nest#2437]
tc39 is adding new things to JS. But why not optional static typing ?

If they do it, we don't have to use Typescript anymore and being able to pass type information to the engine.

We will have less dev dependency.

**Comment by BrunnerLivio** [comment]
We are not able to answer this question, because we are not members of the Technical Committee for ECMAScript. If I were you, search Google, ask on StackOverflow or create an issue in an appropriate [TC39 Repo](https://github.com/tc39) (though I am pretty certain your question has be answered already by the Committee, so you’re better up with googling)
