### ISSUE TITLE
PayloadTooLarge throws 500 instead 413

### ISSUE THREAD

**Issue by yogevlahyani** [nestjs/nest#2444]
## Current behavior
If my request body is too large, I get 500 from the server

## Expected behavior
There is a way to increase the limitation by using body-parser, is there a way to use it inside Nestjs API?
Also, There should be an easy way to throw 413 instead of 500 by not creating another middleware

## Possible Solution
Catch payload too large error and throw 413 instead 500, maybe can be caught by a pipe or an interceptor and customized the error message by using Nest.js API

## Environment

<pre><code>
Nest version: 5.4.0
 
For Tooling issues:
- Node version: 8.3.0
- Platform:  Mac

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
`body-parser` middleware throws an exception which is not compatible with NestJS errors. In order to provide this feature out-of-the-box, we'd have to create another middleware, catch this error, and map it to the appropriate type. However, that would mean that we have added even more setup to the initial "raw" application and it would surely affect the initial performance as well.

What I'd suggest is, you can just disable bodyParser (second parameter of `NestFactory.create()`) and create your own middleware that wraps usage of `body-parser` library (surround with `try..catch` block, etc)
