### ISSUE TITLE
Too much questions about how to use the framework.

### ISSUE THREAD

**Issue by MonsieurMan** [nestjs/nest#245]
I think there are way too much issues about this.
We could redirect to stack overflow and / or the gitter which are IMO more suited to it. It would help keeping the issues clean for features requests, bugs and discussion about the framework itself.   

This could be enforced via an ISSUE_TEMPLATE.md for redirecting users to other places.

**Comment by calligraphic** [comment]
I agree. I've subscribed to notifications in my email inbox for the project the past month, since I'm considering using it in an upcoming project. I was surprised at the volume.

**Comment by adrien2p** [comment]
Yes i watch also the project, But in all issues opened i can see than a lot of them are redundant and the same question come back like `how to inject in global something or in that` so maybe if we look dinstinctly they are not to much question

**Comment by MonsieurMan** [comment]
@adrien2p redundancy is also a place where SO does better than issues, there is a 'native' duplicate marker. And also when writing the title and the content of the question people will be showed with suggestion of previously asked questions.

**Comment by BruceHem** [comment]
moving question to stackoverflow isn't that bright idea either.

**Comment by MonsieurMan** [comment]
@BruceHem, could you please elaborate and be a little bit more constructive ?  You make no point if you don't give any argument.
The only downside I could see to it is people fearing the SO community, but with a nestjs tag they will simply pass away and not taking care of downvoting. _I wish so hard downvotes would require a reason to be applied..._

**Comment by shekohex** [comment]
What about making a new repo `nestjs/discussion` for discussion and help or anything else related to solving problem or `How to` questions ?

**Comment by cojack** [comment]
I totally agree to move questions about installation/development process to SO. Issues will be much clear with ISSUE_TEMPLATE.

@shekohex there is already Gitter for that

**Comment by wbhob** [comment]
I've created PR #246 to start a form of issue template. Looking for reviewers 😄

**Comment by MonsieurMan** [comment]
@wbhob, I see you went the SO way too, as I said in my review, we should ask users to use the **nestjs** tag and on the other hand we should subscribe to the tag so we can be as reponsive as we are with issue.

**Comment by wbhob** [comment]
Hehe I have ~300 points right now. We can try though!

**Comment by adrien2p** [comment]
I need to start ro do some points too ^^

**Comment by MickL** [comment]
Imho its a good practice to answer as many questions as possible even on GitHub which should handle bugs/feature requests while StackOverflow is meant to answer questions. Anyway i think its good for a new project to help people as much as possible because exactly this persons will gain experience, come back later and answer others questions. Or they write articles about things they struggled with. Or recommend the framework to other developers because they have so much joy using it. (We all know getting stuck somewhere is sooo frustrating)

I would tolerate support requests on GitHub until the community has grown(up to 10-20k stars?).

**Comment by wbhob** [comment]
I’d say 4K stars, were already getting 3 issues a day with just questions, and that can get tedious

**Comment by calligraphic** [comment]
@MonsieurMan The project owner could email SO's moderation team and request a nestjs tag added, probably with good results (team@stackoverflow.com), it's a legitimate exception to the reason why SO requires 1500 rep to create new tags.

@MickL I understand, but I still think it's a bad idea to use project issues for general questions:
- It makes it difficult for developers to look at the project and get a quick feel for the status of the project when the number of open issues isn't related at all to _actual_ issues. 
- It reduces the usefulness of issue tags in the Github repository, because all of the general questions stay untagged so people have to dig through them to see what they are. As an aside, it'd be nice to have a tag directed at people's first few commits to a project in general, like "easy" or something.
- There's a marketing aspect to making use of SO for questions. A lot of people there work to get to reputation - employers consider it in new hires. So building a foundation over there helps get the word out, as people who are following "javascript" and "node" tags look at the "nestjs" questions and try to answer it for gamification purposes.
- Pushing questions to SO helps with SEO on those questions. When you open and discuss a question in a project issue, the nature of the conversation is pretty free flow and disorganized. People put more time into SO questions and answers because of the gamification and concern about their rep, which in turn gives better search results in the future when people look for an answer to a question.
- Response on SO questions is often really fast, as a last of people are subscribed to javascript and node tags. Much faster than what a repository issue queue can likely provide.
- SO has better tooling for ranking answers if it's subjective. It's hard to read through a long issue conversation and get a sense for what conclusion people are agreeing is the best way forward when it's not clear cut. Smileys help a little, but nothing like upvoting / downvoting answers.
As far as encouraging framework users to generate content like Medium articles and blog posts about their experiences, I think there's better ways to approach that. Definitely making sure they get the help they need is part of it. But using the Github wiki, and linking to a resources wiki page from the root README and listing all articles out there, and encouraging people to go star the article of something, is probably more effective.

My $0.02.

**Comment by NoNameProvided** [comment]
> @MonsieurMan The project owner could email SO's moderation team and request a nestjs tag added, probably with good results 

It's better to ask on https://meta.stackoverflow.com

**Comment by NoNameProvided** [comment]
Uhm, I just realized I have more than 1500 point :D, will create the tag for you guys. What should be the name?

**Comment by adrien2p** [comment]
I think will continue to answer both anyway ^^ but github is more about question related to the framework and SO more about problem during the usage of the framework. What do you think ? But certainty we will have both with same questions but it’s not a problem

**Comment by MickL** [comment]
Personally i would call it nest since its not really JavaScript. Angular also dropped the „js“.

**Comment by NoNameProvided** [comment]
> Personally i would call it nest since its not really JavaScript.

Sadly, `nest` has been taken already.

**Comment by wbhob** [comment]
You'd have to talk to (convince 😄) @kamilmysliwiec. I've discussed migrating to `@nest/*`, but that could cause issues for older codebases. I've mentally constructed a tentative plan for coordinating this type of shift:

1. Close/merge all outstanding PRs and temporarily block them for the shift
2. Move `common` into `core` and refactor `index.ts` files accordingly.
3. Rename package names to `@nest/*`
4. Publish new versions as `5.x.x`
5. Provide instructions for existing forks to rebase their changes against the new setup
6. Reopen Pull Request feature
7. Profit 💰

**Comment by wbhob** [comment]
Also @NoNameProvided someone would reach out to NPM and see if the organization name is actually in use. It's entirely possible that it is not and we could take it from whoever is squatting on it.

**Comment by kamilmysliwiec** [comment]
Hi everyone,
The @wbhob PR with the `ISSUE_TEMPLATE.md` is merged already. 🙂 @NoNameProvided would be great to have a `nestjs` tag. 🎉

**Comment by NoNameProvided** [comment]
@kamilmysliwiec It has been created: https://stackoverflow.com/questions/tagged/nestjs

**Comment by kamilmysliwiec** [comment]
Great 🎉 Thanks @NoNameProvided 🙂

**Comment by wbhob** [comment]
Yipee!

**Comment by MonsieurMan** [comment]
Subscribed to it!

**Comment by wbhob** [comment]
I realized the message I sent a few days is completely irrelevant, I misread the thread. Sorry folks!
