### ISSUE TITLE
provide services automatically without registering in module

### ISSUE THREAD

**Issue by felixhayashi** [nestjs/nest#2476]
## Is your feature request related to a problem? Please describe.

This feature request may be regarded as an attempt to avoid having to touch `app.module.ts` every time a new service is registered.

## Describe the solution you'd like

Services are decorated with `@Injectable()` which should be enough information for NestJS to register it to the DI container at startup, without a developer having to register the services also to the `providers` array in `AppModule`. 

I would assume nest using reflection to scan for `@Injectable` decorators and extract all necessary information and then to register it to the DI container itself

## Teachability, Documentation, Adoption, Migration Strategy

This would resemble the mechanism recently introduced by angular6:

> Beginning with Angular 6.0, the preferred way to create a singleton service is to set providedIn to root on the service's @Injectable() decorator. This tells Angular to provide the service in the application root.
> https://angular.io/guide/singleton-services#using-providedin

**Comment by kamilmysliwiec** [comment]
`providedIn` was introduced in Angular only because they wanted to achieve better tree-shaking. In Nest, modules compose providers and define their facades (`exports` array). Not public providers will be isolated inside their modules, while in Angular, everything is global. For better clarity, we will keep these 2 properties in `@Module`
