### ISSUE TITLE
Reflector.get() return type misleading since it might return undefined

### ISSUE THREAD

**Issue by xxluke** [nestjs/nest#2500]
## Current behavior
When you create a guard you can obtain information from the execution context using something like this:
```typescript
const isAuthenticated = this.reflector.get<boolean>('isAuthenticated', context.getHandler());
```
`isAuthenticated` now has the type `boolean`, but in fact it might also be `undefined`, when you never set the variable before.

## Expected behavior
The IDE/Linter knows that the return value might also be undefined.

## Possible Solution
Change the return type of the function to `TResult | undefined`.

## Additional information
`Reflector.getAll()` has the same issue.

Changing this would propably count as breaking change since there might be lot of new linting errors.

## Environment

<pre><code>Nest version: 6.4.1
</code></pre>

**Comment by kamilmysliwiec** [comment]
It's true.

However, at the same time, we don't know where you'll apply your guard/interceptor so actually, you should better know if `get` is able to return `undefined` value, or not. In this case, if you are aware that your class (guard or interceptor) may be applied to a handler that doesn't provide any metadata under `isAuthenticated` key, you should pass a union type as a type parameter.

```typescript
const isAuthenticated = this.reflector.get<boolean | undefined>('isAuthenticated', context.getHandler());
```

Obviously, we could add `TResult | undefined` to the codebase, but as you mentioned, it will be a breaking change that would additionally force everyone (even those that are fully certain that a value won't be `undefined`) to add an extra `if` check.

**Comment by xxluke** [comment]
Thank you for your answer.

When you're sure that the value can't be undefined in your implementation, you can use the [Non-null assertion operator (!)](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator) to avoid an additional `if`.
```ts
const isAuthenticated = this.reflector.get<boolean>(/*...*/)!;
```
Currently it assumes that you never make mistakes and the reflection-metadata-key is always set.

It's not a critical error, but I think this should get fixed with the next major version. At migration people might have to add a few `!`s, but at least this methods are only used in guards.

**Comment by kamilmysliwiec** [comment]
> but at least this methods are only used in guards.

These methods can be used in interceptors as well. 

> When you're sure that the value can't be undefined in your implementation, you can use the Non-null assertion operator (!) to avoid an additional if.

Good point. I'll think about this. If anyone else has something to add, please, let us know! I'd love to know what the community thinks about this.

**Comment by tonyhallett** [comment]
I agree with @kamilmysliwiec that it should remain as is.

**Comment by kamilmysliwiec** [comment]
Closing due to the inactivity.

**Comment by drew-mcclelland-ch** [comment]
I don't really agree with the motivations for keeping the status quo. I think one of the most common places to use reflection is in authentication scenarios, where it's common to leave off annotations for unauthenticated endpoints (I'm doing the reverse, where all endpoints need to specify an auth role, as this seems safer). But I do agree that it would be difficult to change now that people rely on this behavior. 

At the very least the NestJS [Guard](https://docs.nestjs.com/guards#putting-it-all-together) docs need to updated to correctly specify the type, as their example doesn't pass the `@typescript-eslint/no-unnecessary-condition` rule because the compiler thinks the variable is of type `string[]` when in reality it is `string[] | undefined`:
```
    const roles = this.reflector.get(Roles, context.getHandler());
    if (!roles) { //eslint complains here because it thinks the conditional is unnecessary, because the default type returned form `.get` is `string[]`
      return true;
    }
```

**Comment by micalevisk** [comment]
> At the very least the NestJS [Guard](https://docs.nestjs.com/guards#putting-it-all-together) docs need to updated to correctly specify the type

feel free to improve the docs

**Comment by thw0rted** [comment]
The docs aren't the problem here, the types are just wrong.  `Reflector#get` returns undefined when called on a target that doesn't use the specified decorator.  You can't know at compile-time whether that's the case or not, ergo the correct return type should always include `undefined`.  You can code defensively and handle the `undefined` case explicitly, or as pointed out in a previous comment, you could add a non-null assertion if you're able to say ahead of time that the target will always have the decorator applied (then, you can add a non-null assertion linter-disable comment explaining *why* you know ahead of time... because of course you're flagging non-null assertions with your linter 😁 ).
