### ISSUE TITLE
Hostname matching when matching routes

### ISSUE THREAD

**Issue by alex88** [nestjs/nest#2521]
## Describe the solution you'd like
Being able at module/controller/method level to match or not the hostname of the request

## What is the motivation / use case for changing the behavior?
I'm currently developing a backend that is going to be used by a mobile app, a single page web app and directly from our customers.
I would like to have a seprate subdomain for each of these apps, however without a prefix (which could make things repetitive e.g. api.example.com/api or mobile/example.com/mobile) there could be conflicting routes matching the same path.
A guard could work but it'll block a request, it won't be able to match another route after skipping the one with the wrong hostname.
Just as an example on how it would work, symfony have this https://symfony.com/doc/current/routing/hostname_pattern.html to match the hostname.

**Comment by nonplus** [comment]
I'm considering to work on this.

I am initially looking at adding a Controller config option for this.  I don't think it's possible to cleanly implement it at the module level (since modules aren't involved in routing) and I don't really see use-cases for doing it at the method level.

The host could be specified either as a new `@Host(host)` **Controller class decorator** or a new [`ControllerOptions`](https://github.com/nestjs/nest/blob/a68ae579d4cf6f096708188a861d8a3b76a3268d/packages/common/decorators/core/controller.decorator.ts#L10) property (easier to implement). The `host` value would be matched against the HTTP request host.  If hosts don't match, the controller won't route.

The `host` should support **wildcards**, e.g. `"api.*"` would match `api.example.com` and `api.dev.local`.

The `host` can support **parameters** (useful for multi-tenant apps), e.g. `:account.example.com` would match `foo.example.com` and `bar.example.com`.  A controller method could access the parameter via: `@HostParam` parameter decorator.

### Examples
```
// Matching hostnames starting with "mobile." - using ControllerOptions
@Controller({ host: 'mobile.*' })
export class MobileController { ... }

// Matching hostnames starting with "api." - using a decorator
@Host('api.*')
@Controller()
export class ApiController { ... }

// Capturing subdomain in "account" parameter
@Controller({ host: ':account.example.com' })
export class AccountController { 
  @Get()
  getInfo(@HostParam('account') account: string) {
    return account;
  }
}

@Controller()
export class AppController { ... }
```

### Questions
* Does this approach make sense as an MVP feature?
* Are there valid use cases for supporting this at the method level? (This could be implemented later)
* What is the preferred configuration - a new `@Host` class decorator or a new optional `ControllerOptions.host` setting?  My preference would be the later.

**Comment by kamilmysliwiec** [comment]
Added in 6.11.0
