### ISSUE TITLE
Using decorators in field resolvers causes memory issues (graphql)

### ISSUE THREAD

**Issue by arvidboivie** [nestjs/nest#2571]
## I'm submitting a bug report

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior
When using the argument decorators for a field resolver the memory usage is dramatically increased for large queries.

## Expected behavior
The decorators would add little to no overhead compared to the default arguments

## Minimal reproduction of the problem with instructions

https://github.com/arvidboivie/nestjs-graphql-example

I've prepared an example repo above. Start the app with `yarn start:dev` and it will be available on localhost:3000. There are example queries included in `example-queries.txt`. Monitor memory usage while running them and you will see a huge increase when using decorators

## Environment

<pre><code>
Nest version:
graphql: 6.2.4
core: 6.4.0

</code></pre>

**Comment by kamilmysliwiec** [comment]
I have moved this issue to the main repo since it rather applies to `ExternalContextCreator` implementation than the actual `@nestjs/graphql` package.

> The decorators would add little to no overhead compared to the default arguments

So the problem here is more about the NestJS decorator-related features, in this case, pipes. Before we can actually execute a method, we have to create a dedicated evaluation context based on the cached metadata. Resolving input parameters is very easy. However, every argument can also have an exclusive set of pipes that should be executed before we can pass the final value to the created context. Additionally, we have to bind global pipes. In your example, you're using `ValidationPipe`, so we have to bind it to every property. Pipes in Nest can be asynchronous, hence, we have to await the result and if we have multiple input arguments, we have to await promises for all of them. Therefore, your call with 20000 nested properties will actually call `Promise.all` 20000 times for every parameter and so on and so forth.

I think that there is a small room for improvement here and I'll push some minor optimizations soon. However, if you know that your `@ResolveProperty()` method is meant to be supposed thousands of times, it's sometimes useful to just avoid using decorators (hence - we don't have to create context for pipes).

**Comment by arvidboivie** [comment]
Thanks for the response, that's what we ended up doing, avoiding decorators for large queries.

**Comment by kamilmysliwiec** [comment]
This should be improved in 6.5.3 :)
