### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by zuohuadong** [nestjs/nest#2670]
https://github.com/nestjs/nest/wiki/Roadmap

**Comment by kamilmysliwiec** [comment]
I'm gonna remove this page and figure out how we can effectively plan features for next releases. So far, I think that the best solution is to simply use issues with milestones & projects to keep one source of truth. Having an extra document with timelines is impossible because we're not backed by big companies so we can't plan how much time we'll spend on releases.

**Comment by zuohuadong** [comment]
@kamilmysliwiec 

We should have a plan so that contributors can understand what they are going to do.
Even if we don't have a time list.

**Comment by kamilmysliwiec** [comment]
That's why we have `PRs open` flag for every issue.
