### ISSUE TITLE
POST requests return httpcode option, disable return 201 by default

### ISSUE THREAD

**Issue by fourcels** [nestjs/nest#2672]
## Is your feature request related to a problem? Please describe.
In my project post resqusts should return 200 httpcode , I have to override httpcode every post request

**Comment by kamilmysliwiec** [comment]
Because that's a default option. Usually, POST requests will lead to the "creation of resource". You can use `@HttpCode()` to change this OR create a global interceptor that will modify your status code based on the request. 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
