### ISSUE TITLE
Cannot depend on dynamic created exports from another module.

### ISSUE THREAD

**Issue by peterreisz** [nestjs/nest#2744]
## Bug Report

* `FooModule.forRoot` creates configurable FooService.
* `BarModule` imports FooModule and tries to provide BarService which depends on FooService
* Resulting BarModule cannot finds FooService and cannot create BarService

## Current behavior

```
Error: Nest can't resolve dependencies of the BarService (?). Please make sure that the argument at index [0] is available in the BarModule context.
    at Injector.lookupComponentInExports (node_modules/@nestjs/core/injector/injector.js:183:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

## Input Code

```ts
import { Injectable, Module, DynamicModule } from "@nestjs/common";

@Injectable()
export class FooService {}

@Module({})
export class FooModule {
  static forRoot(): DynamicModule {
    return {
      module: FooModule,
      providers: [FooService],
      exports: [FooService]
    }
  }
}

@Injectable()
export class BarService {
  constructor(fooService: FooService) {}
}

@Module({
  imports: [FooModule],
  providers: [BarService],
  exports: [BarService]
})
export class BarModule {}

@Module({
  imports: [
    FooModule.forRoot(),
    BarModule,
  ]
})
export class AppModule {}

```

## Expected behavior
BarModule should see all of FooModule-s exports, even dynamic ones

## Possible Solution

When ModuleBar importing ModuleFoo, nest should wait for creating all of ModuleFoo exports (even dynamic ones) and then should try to initialize modules depending on ModuleFoo, for example ModuleBar.

## Environment

<pre><code>
Nest version: 6.5.2

 
For Tooling issues:
- Node version: 8 LTS
- Platform:  Linux

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
```typescript
@Module({
  imports: [FooModule],
  providers: [BarService],
  exports: [BarService]
})
export class BarModule {}
```
`BarModule` imports `FooModule` instead of `FooModule.forRoot()` which provides `FooService`. `FooModule.forRoot()` in `AppModule` doesn't change anything here. Read more in the docs - https://docs.nestjs.com/modules

**Comment by peterreisz** [comment]
@kamilmysliwiec 

My use case is to create dynamic service which I would like to configure only at root level. I though `FooModule.forRoot` is the same as `FooModule`. The only different is the `forRoot` provides services at root level (or where you import it).

In angular it works as I described, you can try it here: https://codesandbox.io/s/angular-qld59

```ts
@Injectable()
export class FooService {}

@NgModule({})
export class FooModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: FooModule,
      providers: [FooService]
    };
  }
}

@Injectable()
export class BarService {
  constructor(readonly fooService: FooService) {}
}

@NgModule({
  imports: [FooModule],
  providers: [BarService]
})
export class BarModule {}

@NgModule({
  imports: [FooModule.forRoot(), BarModule],
})
export class AppModule {}
```

Can you provide me a solution for my use case?

**Comment by kamilmysliwiec** [comment]
Angular modules are different (providers are available globally). In Nest, everything is isolated, encapsulated in the module scope.

**Comment by cookrn** [comment]
I'm currently struggling with this as well. One solution I've found is to create a `Container` module (I'm open to alternate naming suggestions) that serves as a host for resolving the dynamic module and re-exporting it. For example, modifying your code above might look like this:

```typescript
import { Injectable, Module, DynamicModule } from "@nestjs/common";

@Injectable()
export class FooService {}

@Module({})
export class FooModule {
  static forRoot(): DynamicModule {
    return {
      module: FooModule,
      providers: [FooService],
      exports: [FooService]
    }
  }
}

@Module({
  imports: [FooModule.forRoot()],
  exports: [FooModule]
})
export class FooContainerModule {}

@Injectable()
export class BarService {
  constructor(fooService: FooService) {}
}

@Module({
  imports: [FooContainerModule],
  providers: [BarService],
  exports: [BarService]
})
export class BarModule {}

@Module({
  imports: [
    BarModule
  ]
})
export class AppModule {}
```

If you read the last section of the docs on [dynamic modules](https://docs.nestjs.com/modules#dynamic-modules), it seems to imply that exported dynamic modules get the dynamically resolved value but using only the static name? I'm also not sure how Nest would handle multiple versus single instantiation of the module/providers within the dynamic module in this case i.e. will it end up re-running the configuration options factory and such many times or instantiating new objects for each use?

Lastly, @kamilmysliwiec has mentioned in other issues that the https://github.com/nestjs/typeorm code is a helpful read for usage of these patterns. I agree! It seems to use a different solution though, which is to hide a global (dynamic) module behind a non-global (also dynamic) module. Specifically, `TypeOrmCoreModule` is decorated with `@Global`, I think in order to ensure that db connection providers are each only instantiated and resolved one time? All application code using the package occurs with the `TypeOrmModule` though -- you never touch the `Core` one directly.

I'm still learning, and would love feedback or pros/cons on these approaches 😎

**Comment by johnbiundo** [comment]
I think the `@Global()` decorator gets you what you want, no?

```typescript
import { Injectable, Module, DynamicModule, Global } from '@nestjs/common';
// tslint:disable: max-classes-per-file

@Injectable()
export class FooService {
  private hello: string = 'hey';

  constructor() {
    console.log('Instantiating FooService');
  }

  setHello(msg) {
    this.hello = msg;
  }

  sayHello(from) {
    console.log(`${this.hello} ${from.constructor.name}`);
  }
}

@Global()
@Module({})
export class FooModule {
  static forRoot(): DynamicModule {
    return {
      module: FooModule,
      providers: [FooService],
      exports: [FooService],
    };
  }
}

@Injectable()
export class BarService {
  constructor(private fooService: FooService) {
    this.fooService.setHello('Hi there');
    this.fooService.sayHello(this);
  }
}

@Module({
  providers: [BarService],
  exports: [BarService],
})
export class BarModule {}

@Module({ imports: [FooModule.forRoot(), BarModule] })
export class AppModule {
  constructor(private fooService: FooService) {
    this.fooService.sayHello(this);
  }
}
```
