### ISSUE TITLE
Is it possible to get rid of forwardRef by making the "imports" field accept a function instead of a static array?

### ISSUE THREAD

**Issue by vnenkpet** [nestjs/nest#2799]
## Feature Request

I assume keeping track of circular references and knowing when and how to use forwardRef is counter-intuitive and it could work better.

## Is your feature request related to a problem? Please describe.
It's more of a developer experience thing. 

## Describe the solution you'd like
Similarly to how https://typegraphql.ml/ deals with this, 
instead of 
```
imports: [
    ConfigModule,
    DatabaseModule,
    forwardRef(() => UserModule),
    forwardRef(() => PostModule),
]
```
can't we have 
```
imports: () => [
    ConfigModule,
    DatabaseModule,
    UserModule,
    PostModule,
]
```
?

Simply treat every import as if it could possibly have a circular reference by making "imports" 
 accept function instead of a static array, so it won't fail when trying to init the app. 

## Teachability, Documentation, Adoption, Migration Strategy
I think this would simplify the module importing a lot for developers. I have no idea if there are some technical/performance limitations to why is it different now and if it could be backwards compatible with current solution, but as for performance that doesn't seem like an issue to me, since this is only called once during Nest app module initialisation.  

## What is the motivation / use case for changing the behavior?
Keeping track of circular references and knowing when and how to use forwardRef is counter-intuitive.

**Comment by kamilmysliwiec** [comment]
So actually, I think that it's important to explicitly indicate (using `forwardRef`) which modules form a circular relationship because that should help to avoid such scenarios in the future. Generally, circular dependencies are not considered as best practices and we should try to prevent them as much as possible. If we have multiple `forwardRef` calls in a module definition, that means we should rather consider restructuring our modules.

Also, to easily detect circular dependencies you could give a shot to [Madge](https://github.com/pahen/madge) library - it creates a visualization of your relationships between files.

**Comment by marcus-sa** [comment]
Otherwise if you're already using Webpack; this plugin exists https://github.com/aackerman/circular-dependency-plugin
