### ISSUE TITLE
Update examples to use new package.json scripts

### ISSUE THREAD

**Issue by johnbiundo** [nestjs/nest#2838]
## Feature Request

Update examples to use recently updated `package.json` scripts from typescript starter.

## What is the motivation / use case for changing the behavior?

Users should be able to use examples with latest installed version of nest.

**Comment by kamilmysliwiec** [comment]
Sounds perfect!

**Comment by johnbiundo** [comment]
@kamilmysliwiec Since I'll be touching every sample, I have two follow-on questions:
1. Should I update all of the dependencies to match `typescript-starter` (and other up-to-date compatible dependencies where they have extras not mentioned in `typescript-starter`)?
2. Should we make the nest dependencies be either `~6.0.0` or `^6.0.0` instead of `6.0.0` for forward compatibility?  With `6.0.0`, yesterday I ran into the logger problem when running a sample! 😄

**Comment by rubiin** [comment]
@johnbiundo  you should also include the fix for path alias in the starter

**Comment by johnbiundo** [comment]
@rubiin  Do you have a specific reference?  Not sure what you're referring to.

**Comment by rubiin** [comment]
for referrence you can see https://dev.to/rubinsays/resolving-path-alias-in-nestjs-projects-11o1

**Comment by jmcdo29** [comment]
@rubin I think the problem with adding in the code I helped you with, the `tsconfig-path-bootstrap` is that it needs to be configurable for non-standard tsconfig names or for different use cases like monorepos. The added file helps, but honestly I think the deeper issues is with `tsconfig-paths` which I haven't dug deeper into. The other thing is that not everyone uses path mapping, so now a new file shows up and some users could be confused by it. Rather, this may need to be brought up to the author of `tsconfig-paths` as that whether the real issue lies. The bootstrap script is a workaround, not a perfect solution
