### ISSUE TITLE
04-injector example - strange behavior 

### ISSUE THREAD

**Issue by myflowpl** [nestjs/nest#292]
I'v just cloned and fired the injectior example from master branch
it works, but when I started to play with it, I got strange error

in the `feature.service.ts`
https://github.com/nestjs/nest/blob/master/examples/04-injector/src/modules/feature/feature.service.ts
```typescript
@Component()
export class FeatureService {
  constructor(private readonly commonService: CommonService) {
    console.log("FeatureService", commonService);
  }
}
```
 i just removed the injections in constructor, so it's free of dependencies
```typescript
@Component()
export class FeatureService {
  constructor() {
    console.log("FeatureService");
  }
}
```
now i have sturtup error:

`Nest can't resolve dependencies of the CommonService (?). Please verify whether [0] argument is available in the current context.`

Why CommonService can't get CoreService injection when I stop using it inside FeatureService ?

I'v read all the docs and past issues about DI and modules, and can't figure out the idea behid DI logic

Is it a bug or i just cant find out how it works ?

Nest version:
 "@nestjs/common": "^4.4.2",
 "@nestjs/core": "^4.4.2",
 
Node version: 9.2.0
Platform:  Ubuntu 16.04

**Comment by kamilmysliwiec** [comment]
Hi @myflowpl,
Everything works as expected here. The reason why Nest can't create a `CommonService` instance is that there's no `CoreService` in the current context. It works properly when `FeatureModule` is used because, in this situation, the `FeatureService` needs the `CommonService`. It creates a `FeatureModule` execution context, and this module has an access to the `CoreModule` which contains the `CoreService`. This makes possible to inject this service into the `CommonService`. Without `FeatureService`, the `CommonService` is created within `CommonModule` context because this component is not needed in the `CoreModule` (the Nest injector starting point is `CommonModule` now, previously it was `FeatureModule`).
