### ISSUE TITLE
OpenAPI (Swagger) - Wrong swagger-ui generation when multiple dto's with the same class name exist

### ISSUE THREAD

**Issue by NielsPeeters** [nestjs/nest#2946]
## Bug Report
When creating multiple dto.ts files with the same class name only one of the alphabetically latest will be used when generating the swagger-ui.

## Current behavior
Given the following file structure:
```
src/

├── users/
│   ├── dto
|   │   └── get-user.dto.ts // with classname 'userDto'
│   ├── user.controller.ts  // import userDto from './dto/get-user.dto.ts'
│   └── user.service.ts
└── wrestler/
    ├── dto
    │   └── get-user-wrestler.dto.ts // with classname 'userDto'
    ├── wrestler.controller.ts       // import userDto from './dto/get-user-wrestler.dto.ts'
    └── wrestler.service.ts
```

**Note that both dto.ts file have the same class name?**

When viewing the swagger-ui for the /users path the incorrect response data will be shown.
Instead of the expected dto data from `./dto/get-user.dto.ts` to be shown for the /users path the data `get-user-wrestler.dto.ts` will be shown because of the similar class names.

## Expected behavior
When generating the swagger-ui its should look for the dto's related import file instead of overwriting dto's to the latest possible instance of that class name.

Like the example because the dto is imported from  `./dto/get-user.dto.ts` it should contain that related data in the swagger-ui, even if later another dto is created with the same class name.

## Temporarily Solution
Changing class name's resolves the issue for this example (ex. give the `get-user-wrestler.dto.ts` the `wrestler` class name), In larger projects this could be a more common issue and would become less easy to avoid.

## Environment
Nest version: 6.5.0

**Comment by kamilmysliwiec** [comment]
We generate OpenApi models based on DTO classes you provide. Eventually, these models have to be represented by name, and for model's name, we use the class name (which is fairly obvious). If you have 2 classes with the same name, these definitions would override each other (because they would share the exact same name). Solution: just don't use the same names for DTOs which is, by the way, a recommended practice. Having classes with the same name decrease developer experience (e.g. auto imports, context switching).

> When generating the swagger-ui its should look for the dto's related import file instead of overwriting dto's to the latest possible instance of that class name.

This wouldn't work for bundlers like webpack. Also, I don't think that there is an easy way to lookup import paths at the runtime that would work for every scenario (except using precompilation step with some sort of the static analysis over the AST).

**Comment by NielsPeeters** [comment]
> We generate OpenApi models based on DTO classes you provide. Eventually, these models have to be represented by name, and for model's name, we use the class name (which is fairly obvious). If you have 2 classes with the same name, these definitions would override each other (because they would share the exact same name).

Wouldn't it be possible to generate an unique name for each class dependent on its content?
ex: instead of the class name use a file hash or if the class name already exists use add an incremental value behind its mapping.
