### ISSUE TITLE
Typed API

### ISSUE THREAD

**Issue by benbayard** [nestjs/nest#318]
Hey y'all, I think a great feature would be the ability to use our API in a type safe way. 

For instance, if we went through the `@Param` and `@Body` we could generate some sort of front-end compatible type-safe communication layer.

**Comment by wbhob** [comment]
There is no way to use decorators as types; they are a runtime decoration, not compile-time.

**Comment by cojack** [comment]
@benbayard so if the client wont use the `restyped` the whole idea is "icky"?

**Comment by benbayard** [comment]
How do you mean "icky"? Restyped is an example that can be hooked in to. (We would have to generate the `.d.ts` files. Another option would be for nest to consume those files and keep some type safety around the route decorators. Then we could create a restyped file and have the code actually enforced in our back end.

**Comment by cojack** [comment]
@benbayard by "icky" i mean _useless_

**Comment by benbayard** [comment]
In the restyped example, yes. If you don't use a feature, you aren't using the feature. 

Simply, I'm asking for some kind of way to generate or enforce a front end API client that is typed from nest. I think this should be technically doable.

**Comment by arkraft** [comment]
Have you seen https://github.com/nestjs/swagger? You can create a swagger file from nest and use the client generator to create an API client. There is also a typescript generator.

**Comment by benbayard** [comment]
@arkraft that is DOPE. I had not seen that yet. I think that nearly accomplishes the goal. It doesn't look like swagger enforces the response type though? Like I can declare the response type, but does it enforce that in the actual function call?

**Comment by myflowpl** [comment]
@benbayard not sure what do you mean by "envorces the response type"
but you can always set return type of the controller function, so your response is typed, like this:
```typescript
@ApiUseTags('slackmap')
@Controller('config')
export class ConfigController {
  constructor(private configGetUseCase: ConfigGetUseCase) {}
  @Get()
  @ApiResponse({status: 200, type: ConfigModel, description: 'SlackMap UI configuration'})
  async configGet(): Promise<ConfigModel> {
    return this.configGetUseCase.process();
  }
}
```
in this case i will get typescript parse error if the process method don't return valid ConfigModel, and this model is also represented in swagger contract, this works pretty good for me

and if you need to validate the params, look at this issue #335

**Comment by tx4x** [comment]
it seems relative easy & doable to convert TS definitions into some json. Most leg work can be seen in many places like 'typedoc' (doc generator) which utilize ts-lib or so. 

However, I am also looking for some guaranties (but overhead less) that my client uis (web, std-in, yargs, blessed,...) do this type-check at build-time and in some cases at run-time as well. 

Swagger is great but I won't build this feature with that since it's more static solution to another problem, though. Til now I'm using an abandoned proposal, way more direct, called  "Dojo-SMD" (https://dojotoolkit.org/reference-guide/1.8/dojox/rpc/smd.html). It's sort of offline & online service method introspection you can return for all you services. would love to see that as decorator,ie: '@rpc-method' something your filter against some @acl and what not :+)

**Comment by wbhob** [comment]
The only thing I can think of is that you have shared interfaces between your server and client and connect them together. This quickly becomes problematic and complex. Just use runtime checks!

**Comment by tx4x** [comment]
i did end up with a combination of swagger tools and a shared code base; job done :-)
