### ISSUE TITLE
unknown instead of any

### ISSUE THREAD

**Issue by WillSquire** [nestjs/nest#3189]
Noticed there's a lot of `any` in the framework, where `unknown` might be more favourable for type safety? Here's more on [unknown](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type)

P.S. (where generics isn't an option ;) )

**Comment by BrunnerLivio** [comment]
Thanks for your issue. Reason for that being simply because `unknown` has not been a feature for long in TypeScript. The Nest codebase is way older than that, therefore we mainly used `any`. Feel free to submit Pull Requests when you see areas, where using `unknown` makes sense.

I am closing this issue, since it is not specific enough too keep it open.
