### ISSUE TITLE
Sample n. 23 does not compile

### ISSUE THREAD

**Issue by Akxe** [nestjs/nest#3220]
## Current behavior
1. Cloning nestJS
2. Navigate into `23-type-graphql`
3. run `npm i`
4. run `npm run start:dev`

## Input Code
This repo, sample n.23

## Expected behavior
Expectedto compile and work

## Possible Solution
Not sure, I am new

## Environment

<pre><code>
Nest version: 6.8.3
 
For Tooling issues:
- Node version: v12.6.0
- Platform:  Windows

Others:
</code></pre>

**Comment by TannerGabriel** [comment]
Hey @Akxe,

The command `npm run start:dev` is not available in this project because it hasn't been added in the package.json file. You can run the sample by using the following two command:

`npm run build` - Builds the project
`npm run start` - Start the project

Note that your application will not automatically update if you save new changes in your project. If you want to use the `npm run start:dev` command instead you need to add three packages to your project and add the command manually in your package.json file.

Installing the dependencies:
`npm install concurrently nodemon wait-on -D`

Adding the command to your package.json file:
`"scripts": {
    "start:dev": "concurrently --handle-input \"wait-on dist/main.js && nodemon\" \"tsc -w -p tsconfig.build.json\" "
  },`

I hope this helps you out. I will also submit a solution to this problem as a pull request so you have a reference and it's added in the future.

**Comment by Akxe** [comment]
> The command `npm run start:dev` is not available in this project because it hasn't been added in the package.json file. You can run the sample by using the following two command:

This is part of package.json of 23
```
"scripts": {
    "prebuild": "rimraf dist",
    "build": "nest build",
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "start": "nest start",
    "start:dev": "nest start --watch",
    "start:debug": "nest start --debug --watch",
    "start:prod": "node dist/main",
    "lint": "tslint -p tsconfig.json -c tslint.json",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:cov": "jest --coverage",
    "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
    "test:e2e": "jest --config ./test/jest-e2e.json"
  }
```

**Comment by TannerGabriel** [comment]
> > The command `npm run start:dev` is not available in this project because it hasn't been added in the package.json file. You can run the sample by using the following two command:
> 
> This is part of package.json of `23-type-graphql`
> 
> ```
> "scripts": {
>     "prebuild": "rimraf dist",
>     "build": "nest build",
>     "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
>     "start": "nest start",
>     "start:dev": "nest start --watch",
>     "start:debug": "nest start --debug --watch",
>     "start:prod": "node dist/main",
>     "lint": "tslint -p tsconfig.json -c tslint.json",
>     "test": "jest",
>     "test:watch": "jest --watch",
>     "test:cov": "jest --coverage",
>     "test:debug": "node --inspect-brk -r tsconfig-paths/register -r ts-node/register node_modules/.bin/jest --runInBand",
>     "test:e2e": "jest --config ./test/jest-e2e.json"
>   }
> ```

I'm very sorry I had an old version before the scripts where added. It seems that it has to do with the new package.json scripts Nest.js uses see #2838.

That said I will be on the lookout for a fix for this problem and will respond when I find something.

**Comment by Akxe** [comment]
I have a workaround in #3221, if it helps...

> Running code via ts-node -r tsconfig-paths/register src/main.ts instead of npm run start:dev works.

**Comment by kamilmysliwiec** [comment]
Just fixed

**Comment by Akxe** [comment]
@kamilmysliwiec shouldn't there be at least reference to fix? Pull request or some official workaround?

**Comment by kamilmysliwiec** [comment]
It's just an example project @Akxe. You can look at this commit https://github.com/nestjs/nest/commit/ec4bd340d91eb7483e5d266518e4400248549b94
