### ISSUE TITLE
@Param() decorator without a string can easily cause developer error

### ISSUE THREAD

**Issue by briankracoff** [nestjs/nest#3279]
## Current behavior

It is currently very easy for developers to ship a bug where they have a method decorator `@Param()` without the name of the param (such as `@Param() myParam: string`) since typescript doesn't complain in this case. In these cases, you think `myParam` is a `string`, but it's in-fact an `object` with **all** of the request params.
## Input Code

```ts
async getUser(@Param() id: string) {
    // `id` is _not_ a string here, it's an object of all of the params
    // There isn't much stopping us from shipping this if it's missed during code review
}
async getUser(@Param('id') id: string) {
    // `id` is a string here as expected
}
```
## Expected behavior

The param decorators could be implemented in a way that helps to prevent developer error by ensuring we know whether we're getting _one_ or _all_ of the params from the request.

## Possible Solution

I'd like to change the names of the decorators to be `@Param('myParam')` and `@Params()` (for all of the params) to help prevent developer errors.
* `@Params()`: does not allow anything to be passed with it and always returns all of the params
* `@Param('myParam')`: requires a string to be passed in and only ever returns 1 param

We could potentially do something similar with `@Query` as well.

## Environment

<pre><code>
Nest version: 6.8.0

For Tooling issues:
- Node version: n/a  
- Platform: n/a 
Others:

</code></pre>

**Comment by eropple** [comment]
I work with Brian at Hydrow and yeah, this one was a shocker. Given that TypeScript doesn't really offer parameter-level validation (rather, you can get it with `design:type` but it's lossy), it seems like a _really_ good idea for NestJS 7 would be to separate out any and all parameter decorators that change type based on decorator argument overloads.

We could PR this and submit it for NestJS 7.

**Comment by kamilmysliwiec** [comment]
> I'd like to change the names of the decorators to be @Param('myParam') and @Params() (for all of the params) to help prevent developer errors.

This is how every existing parameter-level decorator works in Nest. If you used `@Query()`, you would get an object with all defined query parameters (equivalent to `req.query`), if you used `@Body()`, you would get a request-body object. Likewise, if you passed `@Query('page')`, you would get the value of `page` property of `req.query` object. That's the intended behavior of the framework and for the sake of consistency, we don't plan to change this behavior in the future.

**Comment by kamilmysliwiec** [comment]
Ah, one thing that I forgot to mention. As @eropple said, there is no easy way to reflect the names of arguments passed to methods (especially that bundlers could modify them at the compilation time). TypeScript reflection system is limited, but I think we should be able to enhance it with Nest CLI in the nearest future.

**Comment by eropple** [comment]
@kamilmysliwiec  This goes pretty squarely against the assertion that Nest CLI won't become necessary for pretty basic things.

If we can do this without needing build system integration that isn't portable outside of specific NestJS applications, isn't that better for everybody at all points?

**Comment by kamilmysliwiec** [comment]
> This goes pretty squarely against the assertion that Nest CLI won't become necessary for pretty basic things.

Alright, I didn't choose my words right. Nest CLI will never become *required* to develop Nest apps. If we decide to provide something that would simplify the developers life (like additional checkers/enhancers, similary to how `tslint`/`eslint` works), they will be published as TypeScript plugins compatible with TypeScript API.

**Comment by eropple** [comment]
I appreciate the answer, Kamil--but I guess this gets into the "the Nest CLI has not been adequately roadmapped or explained" situation, which [I've discussed a little bit elsewhere](https://eyrie.substack.com/p/the-eyrie-1-two-passes-means-prod). TypeScript plugins can't, as I understand them, do what you seem to be suggesting--that's why stuff like TSLint (well, ESLint now, with TSLint being deprecated) still exist today.

I dunno, I don't get it. Take for instance this problem--and we had a production outage because it wasn't caught by a linter or by a code review because it compiled and worked correctly. It can be solved in the traditional way of "your code completion in your editor that respects the standard TypeScript language server yells at you because the function signatures don't match up". Or it can be solved in the nontraditional way of "your ecosystem-specific tooling will squawk an error on build". I guess I just don't get why the latter, and why building that specific tooling at all, is better for the developer experience in general than changing a function signature to work with standard, plain old TypeScript. Even as API breaks go--and like, I suggested it for 7.x for that reason--it's super light and could probably even be written as a codemod.

Could you maybe explain your thinking a little to help us better get a sense of why NestJS is going in the direction it is?
