### ISSUE TITLE
Access to response type metadata

### ISSUE THREAD

**Issue by iniel** [nestjs/nest#3287]
## Is your feature request related to a problem? Please describe.

I have an issue with a private route handler metadata.

I wanna create universal auth guard that throws two different type of exception depends of handler type:
* page route handler - redirect to login page.
* ajax route handler - send status code `401`.

To do so I need to know about response type of the handler (render/redirect and other). So I need an access to metadata keys like `RENDER_METADATA`, `REDIRECT_METADATA`, so I could check if this is a page handler or not. But it's private constants in `@nestjs/common` package.

## Describe the solution you'd like

I'm not sure about the rest of metadata keys, but having response type keys in public api could be useful in cases like this.

**Comment by kamilmysliwiec** [comment]
`RENDER_METADATA` and `REDIRECT_METADATA` would work fine for statically applied statuses. What if someone injects `@Res()` object and would change the status code dynamically? Similarly, what if someone changes `status()` in a middleware before the route handler is executed? I would personally suggest trying to determine the type of route based on different characteristics.

**Comment by iniel** [comment]
In our particular project, we have strong rule do not use res in route handlers, so it always should be a static decorator and it wouldn't be a problem. And unfortunately we couldn't find another reliable automatic way to get this information.

**Comment by kamilmysliwiec** [comment]
I'm not entirely sure what approach I should recommend :( There are two ways: either use custom decorators feature and annotate every method - then read this metadata in the guard or just create 2 separate guards (one for page route handlers and second for REST route handlers) following the SRP rule. We can't make this internal metadata (both render and redirect) public because this is something that could potentially change over time (introducing additional, useless breaking changes in this case)

**Comment by iniel** [comment]
Okay, thank you any way.
We've found another solution - to create our own `@Render` and `@Redirect` decorators which set metadata and call original decorators from `@nestjs/common`.

**Comment by kamilmysliwiec** [comment]
Perfect! :)
