### ISSUE TITLE
Error using Graphql Module with type-graphql at the same time

### ISSUE THREAD

**Issue by RELATO** [nestjs/nest#3353]
## Current behavior
When running the provided NestJS project (link below) the following errors occurred 
```
(node:7098) UnhandledPromiseRejectionWarning: Error: Query.users defined in resolvers, but not in schema
(node:7098) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7098) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Input Code
I created the repository below to easy the evaluation process

https://github.com/RELATO/nest-graphql-case.git

## Expected behavior
Running without any errors

## Environment

<pre><code>
Nest version: 6.9.0

For Tooling issues:
- Node version: v10.17.0
- Npm version: 6.12.0
- Platform: Linux Ubuntu 18.04.3

Others:

</code></pre>

**Comment by jmcdo29** [comment]
It looks like you're trying to combine bot hthe schema-first approach and the code-first approach. I have a NestJS project using GraphQL with type-graphql due to the code-first approach running with no problems. If you need [you can find it here](https://github.com/jmcdo29/zeldaPlay/tree/master/apps/api/src/app)

**Comment by RELATO** [comment]
Hi Jay,

Thank you for your reference repository. It is a very well done work! 

Yes I want to use both schema-first approach and the code-first approach. Depending on each case It would be more productive using a particular approach. 

Think about ngrx as an example of two approaches. Sometimes you will be much more productive using ngrx-data and achieve your goals faster. Sometimes you will need to use the old fashion way I.E. Entities + Effects + Reducers + Actions to be able to deal with complex scenarios. 

So, when using database tables with a lot of fields It is much better to use code-first approach because you can generate typeorm entity classes from your database structure and this way you will not need to create graphql schemes by hand because type-graphql will do the job. 

I am really wanting to find a solution for such problem.

**Comment by jmcdo29** [comment]
I'll let the core maintainers speak more to it, but to my understanding, without at least using multiple endpoints, it wouldn't be possible to use both approaches, due to the way that both of them generate the graphql/typescript necessary to allow for development. the closest you can get is in one project following a schema-first design pattern and in another following the code-first.

**Comment by kamilmysliwiec** [comment]
Using both at the same time is not supported and we don't plan to support it in the future.
