### ISSUE TITLE
Validation Pipe not working with files when fastify adapter uses. Updated

### ISSUE THREAD

**Issue by Wizp** [nestjs/nest#3473]
## Bug Report
For file upload uses "fastify-file-upload" version "2.0.1".
When value in ValidationPipe.transform includes file object plainToClass function try to run mv function in transformation process. Because it differs from /express-fileupload/lib/fileFactory.js implementation it fail.

This issue is duplicate for https://github.com/nestjs/nest/issues/3449
I was busy and added repository little bit late.
Here is link  to repository which reproduces issue: https://github.com/Wizp/minimal-repository

**Comment by kamilmysliwiec** [comment]
This issue doesn't seem to be related to NestJS. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by bastiaanv** [comment]
Maybe my answer is too late, but I had the same problem using the same libraries. I was able to fix it, by using the ```@Exclude``` decorator from the class-transformer library. Example:
```typescript
import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, MaxLength } from 'class-validator';
import { Exclude } from 'class-transformer';

export class NewAgendaDTO {
    @ApiProperty()
    @IsNotEmpty()
    location: string;

    @ApiProperty({type: String, format: 'date'})
    @IsNotEmpty()
    date: Date;

    @ApiProperty({maxLength: 63})
    @IsNotEmpty()
    @MaxLength(63)
    title: string;

    @ApiProperty({maxLength: 255})
    @IsNotEmpty()
    @MaxLength(255)
    summary: string;

    @ApiProperty({maxLength: 65535})
    @IsNotEmpty()
    @MaxLength(65535)
    description: string;

    @ApiProperty({ type: 'string', format: 'binary' })
    @Exclude()
    image: any;
}
```

This problem is caused, because the class-transformer library want to decode the file object. But when it hits the data key, it thinks it is a function, in stead of the buffer. As a result of that, the buffer function is executed, but missing the parameters it needs (such as a path).
