### ISSUE TITLE
Avoid breaking everything after a new version. It's really bad for developers.

### ISSUE THREAD

**Issue by sinner** [nestjs/nest#3614]
I take this time because I can see real huge potential in this framework. If you want to have this framework as a reference as the Typescript backend framework by excellence you must try to take into account the previous version compatibility and avoid changes such as changing the name of a method... I'm following you by many years I have two different projects in production using different versions of the framework and thinking on migrating them is a big headache, it drops in the ground the possible engagement the developer could have on your technology.

Yes, I can understand, with changes in evergreen browsers, JavaScript engines, ECMAScript specifications, frameworks and tooling happening at the same time, it’s really hard to keep everything backward compatible and get the benefits of the new features without compromising performance and API integrity. But after that episode, things have changed and major JavaScript frameworks learned the lesson. But I think Nest.js must take compatibility very seriously. This commitment shows the framework’s maturity and stability looking into the future.

**Comment by kamilmysliwiec** [comment]
?

I'm not sure what you mean. We didn't introduce any breaking change in the framework since March 18 (8 months ago - major release v6).

If you are referring to the Swagger module (`@nestjs/swagger`), this package has been fully refactored and published as a new major release (you can find more here https://trilon.io/blog/nestjs-swagger-4-whats-new). Major release means breaking changes = https://semver.org/
