### ISSUE TITLE
[Kafka Microservice] Buffer values are always stringified

### ISSUE THREAD

**Issue by antogyn** [nestjs/nest#3726]
## Current behavior
Consumed Kafka messages are systematically decoded to strings, using the default `utf8` encoding.

https://github.com/nestjs/nest/blob/257203d0e74530cdbda8f5e376c9c689f3899c8c/packages/microservices/helpers/kafka-parser.ts#L21-L36

This code is called before the customizable deserializer, so there is no way to retrieve the original `Buffer` and use any other encoding.

## Expected behavior
There should be a way to retrieve the original `Buffer`, preferably by disabling the automatic transformation into a string.

## Possible Solution
It could be fixed by adding a new option to toggle the transformation

## Environment
Nest version: 6.10

**Comment by kamilmysliwiec** [comment]
> There should be a way to retrieve the original Buffer, preferably by disabling the automatic transformation into a string.

We could merge the current implementation of `KafkaParser` with a deserializer. Hence, it would be possible to override the default deserializer. PRs are welcome!

**Comment by antogyn** [comment]
I started looking at it and I realized there is already a special deserializer for responses in the client:

https://github.com/nestjs/nest/blob/38d9e743599bc8c6755da768d3eddbf636f25659/packages/microservices/deserializers/kafka-response.deserializer.ts#L5-L29

It doesn't seem right to me to have to reimplement this kind of logic in custom deserializers.

The simplest solution I came up with would be to have a new `parser` option with this Interface:

```ts
import type { KafkaMessage } from 'external/kafka.interface';

export interface KafkaParser {
  parse<K, V, H>(data: KafkaMessage): KafkaMessage<K, V, H>;
}
```

with `KafkaMessage` becoming a generic type:

```ts
export interface KafkaMessage<K = Buffer, V = Buffer, H = Buffer> {
  key: K;
  value: V;
  timestamp: string;
  size: number;
  attributes: number;
  offset: string;
  headers?: IHeaders<H>;
}
```

The current parser would implement `KafkaParser` and be the default value.

It's simple but it does seem a bit weird not to use the `deserializer` option. Wdyt?

**Comment by antogyn** [comment]
Any opinion on this?

**Comment by krukru** [comment]
Hey, this forced stringifying of the Buffer is really just terrible, since it corrupts incoming buffers without a chance of recovery.
For example, when producing an Avro buffer to Kafka, casting the buffer to string (and then back again to buffer, to decode the Avro) will most likely result in a corrupt buffer.

I agree this would be best merged with the deserialiser (what are really the differences between this parser and deserialiser, do we really need both?), but for now the best thing would be just to @antogyn idea of using a default parser and exposing an option to provide a custom parser implementation.

This preserver compatibility and buys time for a proper solution. I can help with a PR if you agree with the idea, since this is a blocker for me.

**Comment by kamilmysliwiec** [comment]
> This preserver compatibility and buys time for a proper solution. I can help with a PR if you agree with the idea, since this is a blocker for me.

PRs are more than welcome @krukru :)

**Comment by krukru** [comment]
Just a word of warning, KafkaParser decode runs on both the message key, value and headers. While I would like to keep Buffer for key and value, I think that headers need to be converted `toString`, because of the way the framework processes the message headers (for example, when responding in MessagePattern)

**Comment by furkee** [comment]
I believe without access to original buffer, using kafka micro-service of NestJS is impossible for a lot of applications since original buffer is lost and avro decoding fails. Is this on your milestone?

**Comment by ivalduan** [comment]
Is there any pending PR related with this issue? Otherwise I would try to come with something.

The easiest solution for what I need is to add a new field with the raw buffer to the data response here:
https://github.com/nestjs/nest/blob/257203d0e74530cdbda8f5e376c9c689f3899c8c/packages/microservices/helpers/kafka-parser.ts#L5

A more elegant one is to deal with custom Deserializers as discussed.
@kamilmysliwiec if you have any preference guidelines to integrate this let me know and I will take those into account.

**Comment by can-kayacan** [comment]
Do you have any concerns for [this PR](https://github.com/nestjs/nest/issues/3726) @kamilmysliwiec ?

**Comment by zaro** [comment]
Not being able to use Avro message with nestjs is big blocker for adopting Kafka + Nestjs

**Comment by techvlad** [comment]
@zaro I found [@rob3000/nestjs-kafka](https://www.npmjs.com/package/@rob3000/nestjs-kafka) module that allows working with Kafka.js + Avro. Give a try

**Comment by kamilmysliwiec** [comment]
PR merged https://github.com/nestjs/nest/pull/6863
