### ISSUE TITLE
Expose native client from the ClientProxy

### ISSUE THREAD

**Issue by overflowz** [nestjs/nest#3913]
## Is your feature request related to a problem? Please describe.

I want to have more control over options when I use ClientProxy. (e.g. I want to be able to set retain, QoS, etc. options to MQTT client).

## Describe the solution you'd like

ClientProxy should have a method that exposes native client instances so I could have more control over options.

## Teachability, Documentation, Adoption, Migration Strategy

The use case would be that you can get a native client and have more control over the options.

## What is the motivation / use case for changing the behavior?

ClientProxy is way too limited.

**Comment by krukru** [comment]
Most if now all client implementations have a `public createClient` method. 
This does require you to downcast your ClientProxy to the specific Client implementation, which is obviously not ideal because it couples you to a specific Transport and the details of the underlying native client.
I think that your configurations of the native client should go in a transport-specific layer, and keep your controllers and services agnostic of the native client.
Or if you really do need to take this route (for example, you will never consider changing your transport layer and are ok with coupling), just inject ClientMqtt instead of ClientProxy (would not recommend)

**Comment by overflowz** [comment]
I'm not sure about not recommending, what if it's crucial to specify the QoS level when publishing a message? or retain flag, etc.

**Comment by krukru** [comment]
If it is crucial to access transport-specific details (and it most probably always will be at some point!), I would still inject ClientProxy into the controller and abstract mqtt details into some other service. This way you could change the transport without modifications to the controller and existing mqtt code

**Comment by overflowz** [comment]
Hmm. I'll try and post back whenever I can. Thanks!

**Comment by kamilmysliwiec** [comment]
`ClientProxy` is intended to be platform-agnostic and act as an abstraction over the transport layer. If you need more control over the transport strategy, you can create a custom strategy (or inherit from the existing one). We're tracking this here https://github.com/nestjs/docs.nestjs.com/issues/113 + series of articles https://dev.to/nestjs/part-1-introduction-and-setup-1a2l
