### ISSUE TITLE
Docs for building a Monorepo for NestJS and frontend

### ISSUE THREAD

**Issue by ttsirkia** [nestjs/nest#3929]
## Is your feature request related to a problem? Please describe.
This is more a question of best practices and documentation.

## Describe the solution you'd like
The current documentation covers nice recipes for various things. In addition, a monorepo structure was recently added to project. However, if I have understood correctly, the current monorepo functionality is only for server-side code.

I would like to see an example how to create a monorepo which contains NestJS as the backend and React/Angular/whatever for frontend. It should be possible to share at least interfaces between the modules. Frontend probably requires Webpack to create a single JavaScript package.

Is using Lerna or Nx currently the best ways to achieve this? Any pros or cons? I have tried to find nice articles or examples but haven’t find anything that useful. Nx seems to have some built-in features of embedding NestJS.

## What is the motivation / use case for changing the behavior?
Monorepos are popular nowadays, NestJS too. Therefore, I assume that the need of creating this kind of monorepos exists. Giving some advice or pointers how to achieve the best structure for new projects would be highly appreciated.

**Comment by kamilmysliwiec** [comment]
Our documentation covers a scenario when you have a monorepo structure with multiple NestJS libraries and applications (recommended).

When you want to use a monorepo approach, but...
- you have to publish libraries to NPM registry (or any other registry): use lerna or yarn workspaces
- you don't want to have a single `package.json` (and follow the single version policy): use lerna or yarn workspaces
- you don't want to bundle libraries with applications using webpack: use lerna or yarn workspaces
- you want to share code between FE and BE apps written in different technologies and you want to bundle code together with apps: use nx
- you want to share code between FE and BE apps written in different technologies and you don't want to bundle code together with apps: use lerna or yarn workspaces

We don't plan to add anything more to the documentation since all mentioned technologies are platform agnostic and aren't targeting only NestJS

**Comment by ttsirkia** [comment]
Thanks for the answer and pointers!
