### ISSUE TITLE
Modifying the request via callbacks and the next() function does not actually fire 

### ISSUE THREAD

**Issue by amit12cool** [nestjs/nest#4003]
## Bug Report
Modifying the request via callbacks and that the next() function does not actually fire 

## Current behavior

I have been experiencing an issue in nestjs where in parsing the request body in middleware results in route NOT called, hence the api hangs.

Here is the link to sample code:-

https://github.com/amit12cool/testMiddleware/blob/master/src/middlewares/request-body-parser.middleware.ts

If line no. 11 in testMiddleware/src/middlewares/request-body-parser.middleware.ts is commented, then everything will work and route will be called. But if not, the request hangs as route is not called.
## Input Code

```
import {
    Injectable,
    NestMiddleware
} from '@nestjs/common';

@Injectable()
export class RequestBodyParserMiddleware implements NestMiddleware {
    async use(req: any, res: any, next: any) {
        console.log('Im here');
        let data = '';
        req.on('data', (chunk) => {
            data+=chunk;
        })
        req.on('end', () => {
            console.log(data);
            next();
        })
    }
}
```

## Expected behavior

The next function should be called after request body parsed in callback function.

## Possible Solution

Not sure.
## Environment

<pre><code>
Nest version: 6..7.2

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by amit12cool** [comment]
@kamilmysliwiec at least specify some reason to close this issue, as this seems to be a bug straightaway and I have attached link to source code toom

**Comment by jmcdo29** [comment]
After taking a look at this, I think this is a bug. Using the FastifyAdapter with the following middleware class
```ts
@Injectable()
export class RequestBodyParserMiddleware implements NestMiddleware {
    use(req: any, res: any, next: any) {
        console.log('Im here');
        let data = '';
        req.on('data', (chunk) => {
            console.log('working with data');
            data+=chunk;
            console.log('data added');
        });
        req.on('end', () => {
            console.log(data);
            console.log('data ended');
            next();
            console.log('next called but not gone there');
        });
    }
}
```
And using the curl
```sh
curl -X POST http://localhost:8080/cats -d 'name=something'
```
I get the output
```sh
Im here
working with data
data added
name=something
data ended
next called but not gone there
```
Using an ExpressAdapter and the same curl I get
```sh
I'm here
```
Seems like there is something wrong with modifying the request object using the event listening methods. Is there a different way to go about this? I know interceptors can do the task, just wanting to know if there is anything I'm missing.

**Comment by kamilmysliwiec** [comment]
As I've already said here https://github.com/nestjs/nest/issues/4002, this is not a **bug**.

These listeners:
```typescript
req.on('data', chunk => {
  ///
});
req.on('end', () => {
  ///
});
```

Will never be fired because your body is processed already. However, when you explicitly disable `bodyParser`:

```typescript
const app = await NestFactory.create(AppModule, {
    bodyParser: false,
});
```

and then use the curl:

```typescript
curl -X POST http://localhost:8080/cats -d 'name=something'
```

You will see the following output:

```
Im here
end
name=something
```

You **can't** process the body **twice**. 

Also, @amit12cool:

> @kamilmysliwiec it seems like you want to just increase the closed issue count to show the community

Please, I'd be very happy if the next time you'll investigate more in advance instead of insulting me. This is very unfair.

PS. @jmcdo29 Fastify will behave differently because middleware takes "native" `req` and `res` objects as input arguments before they get processed by "parsing hook". Hence, in fact, the request body is not processed yet in middleware.

**Comment by amit12cool** [comment]
Contrary to that the listeners are being called with bodyparser as false.


@kamilmysliwiec you are taking it wrong, I'm not insulting you rather I just asked you to provide me a one liner reason for closing the issue rather than blindly closing it.

**Comment by kamilmysliwiec** [comment]
> And in your answer it's not clear will next be called or not? 

Yes, it will. I tested everything locally. I have also explained what's different in @jmcdo29 example. 

> I just asked you to provide me a one liner reason for closing the issue rather than blindly closing it.

I have already replied + I didn't blindly close your issue.

> suggestion should you not close the issue once the author confirms its been resolved or can be closed now or will be done in future?

I'm trying to make issues as clean as possible. This issue is not a bug which I confirmed above. There's no reason to track this here.
