### ISSUE TITLE
Maybe Circular Dependency creates an error when accessing property of a service

### ISSUE THREAD

**Issue by JustDoItSascha** [nestjs/nest#4168]
## Current behavior
It's a little bit hard to describe and I'm not sure what causes the problem in the first place, but I will try to describe it:

We have a Service A which has a property, let's call it `foo`. In the constructor of Service A we set `foo` to 1, trigger an async function and in this function we set `foo` to 2. We have another Service B with a Dependency to Service A. In Service B whenever I try to get ServiceA.foo I get `1` even I know it's now `2`. It's like there are two instances of the same service, but I checked it, so constructors of both service are just called one time.

And it gets weirder: In Service B I can set ServiceA.foo to another value and in Service A I can set a timer which makes a `console.log(this.foo)` after X seconds and I get `2` even the console.log() before in Service B gives me the new value.

The services itself have no circular dependency, but the modules have. But all modules use forwardRef().

Everything else is working in this constellation.

## Input Code
Couldn't recreate it yet. But when I have a working setup I will post it for recreation of the issue.

## Environment
Nest version: 6.11

**Comment by jmcdo29** [comment]
How are you adding `ServiceA` to `ModuleB`? Does `ModuleA` export `ServiceA` and `ModuleB` import `ModuleA`, or does `ModuleB` have both `ServiceB` and `ServiceA` in the `providers` array?

**Comment by JustDoItSascha** [comment]
ModuleB imports ModuleA with forwardRef(). I think it happens only with a
certain level of circularity.

I have two code versions. In the first one it works and the second one is
quite more complex, even nothing has changed in the mentioned Services, but
the circular dependency structure Overall. The issue aopeared between these
two versions.

Yet I don't know which part causes the issue. But I will try to figure that
out.

Jay McDoniel <notifications@github.com> schrieb am Mi., 26. Feb. 2020,
18:56:

**Comment by kamilmysliwiec** [comment]
Unfortunately, we can't do anything until we have a repository which reproduces the issue you reported.

**Comment by JustDoItSascha** [comment]
Hey @kamilmysliwiec , thanks for your answer and your hard work.

Here is a repository with the bug: https://github.com/JustDoItSascha/nestjs-forwardref-bug

I could isolate the bug. In our specific situation it has something to do with the RabbitMQ Library. But I don't think it has something to do with the AMQP Lib itself, because the issue comes only in conjunction with forwardRef() and circular dependency. I think it's more a general problem with third party library callbacks. I have wrote some comments in the code.

You need to start a RabbitMQ with docker and change the port in the code. Then just start the nest server and you will see a console.log() that outputs A1, but should output A2.

**Comment by kamilmysliwiec** [comment]
Thanks for sharing the repo. So actually, this has been discussed a few times in the past already. When you have circular dependencies, it's impossible to call 2 constructors (and instantiate 2 classes) at once. This code:

```
// Start RabbitMQ Server with docker and change the port here
connect('amqp://localhost:32770', () => this.name = 'A2');
```

Will not work properly because you're trying to access the `this` object which points at the "original" instance. However, with circular dependencies, the framework has to decide which class instantiate first and then, re-instantiate it again (without calling the constructor `Object.create`) and assign to the "original" one (to apply dependencies). Hence, the `this` in fact, will reference a different context.

That's why, in the documentation, we recommend putting any additional logic (especially when it comes to circular dependencies) in the **lifecycle hooks**, not the constructor itself.

When you move your code from `constructor` to the, for example, `onModuleInit()`, everything will work fine.
