### ISSUE TITLE
Make NestJS more strict

### ISSUE THREAD

**Issue by joffarex** [nestjs/nest#4178]
Limit usage of `any` and enable strict flags in TypeScript compiler by default.

So whenever I try to use strict flags with NestJS projects, I get some errors. mostly regarding to `any`.

For example, 
```javascript
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: (config: ConfigService) => config.get('database'),
      inject: [ConfigService],
    }),
```

This piece of code simply is not compiling with `--strict` flag, and the error is:
`Type '(config: ConfigService) => ({ retryAttempts?: number | undefined; retryDelay?: number | undefined; autoLoadEntities?: boolean | undefined; keepConnectionAlive?: boolean | undefined; } & Partial<...>) | ... 14 more ... | undefined' is not assignable to type '(...args: any[]) => ({ retryAttempts?: number | undefined; retryDelay?: number | undefined; autoLoadEntities?: boolean | undefined; keepConnectionAlive?: boolean | undefined; } & Partial<MysqlConnectionOptions>) | ... 13 more ... | Promise<...>'.`

Then I check type definitions for `useFactory`, and i find that it is using `(...args: any[])`. however, whenever i disable strict tags, it works.

I am pretty sure this kind of problem might appear with other parts of Nest as well.(for example, again with 'strict' flag, if i do not add `!` after class' properties when i do not initialize them, i get this error `Property 'name' has no initializer and is not definitely assigned in the constructor.`) and in my opinion, it would be a great idea to make Nest's code base more 'strict' and take the full advantage of TypeScript.

**Comment by kamilmysliwiec** [comment]
Nothing prevents you from using the strict mode with NestJS. 

> Limit usage of any and enable strict flags in TypeScript compiler by default.

In some scenarios, `any` is exactly what we need. For example

> Then I check type definitions for useFactory, and i find that it is using (...args: any[]). however, whenever i disable strict tags, it works.

`any` is the expected type here. We can't infer parameters registered with the symbol/string token.

> This piece of code simply is not compiling with --strict flag, and the error is:

This issue is not related to Nest, but rather to the typeorm package.

> I am pretty sure this kind of problem might appear with other parts of Nest as well.(for example, again with 'strict' flag, if i do not add ! after class' properties when i do not initialize them, i get this error Property 'name' has no initializer and is not definitely assigned in the constructor.)

This is not connected with Nest

**Comment by zlk89** [comment]
> Nothing prevents you from using the strict mode with NestJS.
> This is not connected with Nest

I think it does prevent us using strict mode. For example, in [graphql model definition file](https://github.com/nestjs/nest/blob/master/sample/23-graphql-code-first/src/recipes/models/recipe.model.ts):

```
import { Field, ID, ObjectType } from '@nestjs/graphql';

@ObjectType()
export class Recipe {
  @Field(type => ID)
  id: string;

  @Field()
  title: string;

  @Field({ nullable: true })
  description?: string;

  @Field()
  creationDate: Date;

  @Field(type => [String])
  ingredients: string[];
}

```

generates a bunch of typescript error, some are fixable, but some are not:
`TS2564: Property 'id' has no initializer and is not definitely assigned in the constructor.` on all required properties.

There is no way to pass typescript check without `// @ts-ignore` or setting `strictPropertyInitialization : false` in tsconfig, while both workarounds are not ideal.
Because `// @ts-ignore` will ignore all errors on that line, it might hide other issues.

One main reason we want to choose nest.js is that it enforces good patterns. But if we have to lose some benefits brought by Typescript at the same time, it would invalidate the benefits in some senses.

**Comment by jmcdo29** [comment]
@zlk89 why couldn't you [do something like this](https://github.com/jmcdo29/zeldaPlay/blob/master/apps/api/src/app/character/models/character-insert-data.graphql.ts) where you give typescript the assertion that this field will be there, but there is no constructor?

```typescript
import { Field, ID, ObjectType } from '@nestjs/graphql';

@ObjectType()
export class Recipe {
  @Field(type => ID)
  id!: string;

  @Field()
  title!: string;

  @Field({ nullable: true })
  description?: string;

  @Field()
  creationDate!: Date;

  @Field(type => [String])
  ingredients!: string[];
}
```

**Comment by zlk89** [comment]
Good call. It would be great that nestjs uses code under strict mode in the examples or documents by default, or adding a section for this. @jmcdo29

**Comment by kamilmysliwiec** [comment]
> I think it does prevent us using strict mode. For example, in graphql model definition file:

DTOs in REST APIs or Input Types in GraphQL purposely don't have initializers. They represent shapes of objects sent from another external system (e.g., FE app) and in many cases, they are not supposed to have default values. Errors like this one:

> TS2564: Property 'id' has no initializer and is not definitely assigned in the constructor

can be simply ignored by using the assertion (as @jmcdo29 suggested above)
