### ISSUE TITLE
Replace axios by different http package

### ISSUE THREAD

**Issue by hejkerooo** [nestjs/nest#4189]
## Is your feature request related to a problem? Please describe.
Axios project is dead. Even with 8.3 mln of downloads, project is no longer maintained.

https://github.com/axios/axios/issues/1965

## Describe the solution you'd like
Switch to [gaxios](https://github.com/googleapis/gaxios)

**Comment by BrunnerLivio** [comment]
I don’t think Gaxios - even if maintained by Google - has yet reached maturity.

 I actually [left a comment on the issue](https://github.com/axios/axios/issues/1965#issuecomment-578486866) you have mentioned. Unfortunately, there has not been a discussion revolved around that yet as far as I know.

Axios has some problems with maintainers, though maintenance is still being done. If you have a look at the commit history, you’ll see it is still actively maintained. 

I do not see a reason, to potentially introducing breaking changes out of thin air from the perspective of NestJS, because of the current state of Axios.

**Comment by joffarex** [comment]
I would say that the only possible alternative to Axios as of now would have been Request package. But unfortunately, it got deprecated at Feb 11, 2020.

**Comment by kamilmysliwiec** [comment]
Please note - NestJS is a modular framework. `HttpModule` is shipped as an example. If you don't want to use Axios, you can use any other existing library.

**Comment by gerardolima** [comment]
hey, @BrunnerLivio, [Gaxios](https://github.com/googleapis/gaxios) is used as the http client by the Google Cloud's [Node.js Cloud Client Libraries](https://github.com/googleapis/google-cloud-node/blob/main/package.json) (and its interface is actually included in their [official documentation](https://cloud.google.com/nodejs/docs/reference/gaxios/latest/gaxios/gaxios)). Could you, please, explain why you consider Gaxios as _ yet reached maturity_?
