### ISSUE TITLE
Mikro-ORM support

### ISSUE THREAD

**Issue by gperdomor** [nestjs/nest#4265]
## Feature Request

Please add support for Micro-ORM https://mikro-orm.io 😄

**Comment by jmcdo29** [comment]
There is already [nestjs-mikro-orm](https://github.com/dario1985/nestjs-mikro-orm) from the community. Is there a problem with using that library?

**Comment by gperdomor** [comment]
thanks @jmcdo29

**Comment by dpyzo0o** [comment]
@jmcdo29 Is there any chance that nestjs could have an official integration package for mikro-orm (similar to @nestjs/typeorm)?

 I'm asking because 
* [nestjs-mikro-orm](https://github.com/dario1985/nestjs-mikro-orm) seems not to be maintained actively. 
* I personally think mikro-orm has better DX than typeorm and it is being maintained more actively than typeorm.

**Comment by kamilmysliwiec** [comment]
@dpyzo0o I think this question is rather to the MikroORM team. They could release a small library which makes it easier to work with this ORM (if they have enough time & capacity of course!).

We don't plan any official integration ATM - integrating anything into Nest is super easy anyway (such module could consist of ~4 files, you can check out the `@nestjs/typeorm` source code as a reference)
