### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by cojack** [nestjs/nest#4335]
## Is your feature request related to a problem? Please describe.

I wish to have an auto generated `CHANGELOG.md` file in repository

## Describe the solution you'd like

So for every `git tag` this file will be auto updated and added to commit.

## Teachability, Documentation, Adoption, Migration Strategy

There is a module https://www.npmjs.com/package/conventional-changelog for that

## What is the motivation / use case for changing the behavior?

It will helps to check difference between releases

**Comment by kamilmysliwiec** [comment]
This has been discussed many times in the past (see old issues). Important changes/updates are being directly added to the release notes, e.g., https://github.com/nestjs/nest/releases/tag/v7.0.0

**Comment by gprochnicki** [comment]
@cojack you have my sword! I was searching a few days ago what was included in 7.0.2 update and what I was left with was checking the commits in give tag. Automatic CHANGELOG.md would be more convenient.

**Comment by cojack** [comment]
@kamilmysliwiec maybe give a chance to this idea?

**Comment by kamilmysliwiec** [comment]
We're adding notes to every major and minor release to list: new features, improvements, important bug fixes, and, in case of major releases, breaking changes/link to a migration guide. We don't plan to add release notes to patch versions because these versions (in line with semantic versioning principle) contain only bug fixes (mainly very minor bug fixes) and nothing else.

The rule is simple - you should **always** use the latest **patch** version under a specific minor release. These don't (and will never) introduce breaking changes/API changes (nor add new features/functionalities).

Having full control over release notes allows me to emphasize what's important from the developer's perspective (and what framework's users should be aware of). Generated changelogs from commits, on the other hand, would be bloated with nonessential commits that are useless for 99% of developers (we use them for other `@nestjs/__` libraries and it's already quite messy). If people are interested in seeing a list of commits, they could just view the list of commit messages between releases (which is obviously possible - https://stackoverflow.com/questions/5863426/get-commit-list-between-tags-in-git) - having them as part of release notes doesn't bring any relevant value.

We don't plan to change the current approach.
