### ISSUE TITLE
HttpException generic message

### ISSUE THREAD

**Issue by hejkerooo** [nestjs/nest#4338]
## Feature Request
Add generic type to message property of `HttpException`
## Is your feature request related to a problem? Please describe.

So I was implementing custom exception filter to standardize error messages across the application. I've made a helper to transform class validator error messages to my custom error format.  
## Describe the solution you'd like

Sample code:
```js
protected transformValidationError(exception: BadRequestException): BadRequestException<ErrorTemplate> {
    // ... code

    return new BadRequestException<ErrorTemplate>(transformedException);
  }
```

## Teachability, Documentation, Adoption, Migration Strategy

https://docs.nestjs.com/exception-filters#built-in-http-exceptions
Probably we should update this section of the documentation to provide information about possible generic types in `HttpException` but I don't see that necessary.

## What is the motivation/use case for changing the behaviour?

It would be helpful to standardize error messages across the application.

**Comment by kamilmysliwiec** [comment]
> It would be helpful to standardize error messages across the application.

This is why we recommend creating your own exceptions hierarchy:

![image](https://user-images.githubusercontent.com/23244943/77150682-b9046b00-6a94-11ea-9329-1ef88f880445.png)

https://docs.nestjs.com/exception-filters#custom-exceptions

Adding a type argument (making `HttpException` generic) would only lead to redundancy (repeating, e.g. `throw new BadRequestException<ErrorTemplate>` throughout the code). Instead, simply extend the built-in exception and specify (in a `constructor`) what shape (of a message) is acceptable (or create this shape within a constructor based on passed arguments). 

If you don't want to create your own exception classes (because the shape for messages is equal for all existing exceptions) which also makes a lot of sense in some specific scenarios, you can create a factory class which defines the `create()` method that indicates what shape of messages is acceptable.
