### ISSUE TITLE
Throw an error (if possible) when controller uses a @Res() or @Response() and a normal 'return' statement.

### ISSUE THREAD

**Issue by juanp123** [nestjs/nest#4414]
The docs at https://docs.nestjs.com/controllers explain that when  @Res() or @Response() is injected into a request handler, that the response must be given on the response object (i.e. res.send() or otherwise). Failing to do so will hang the http server. 

Assuming it is possible, a nice-to-have would be a a console warning shown when the code uses a  @Res() or @Response() .  Ideally, an error would be thrown if `return` is used but likely difficult to implement.

Motivation for this request, is it is pretty easy to make the mistake of using a normal return statement with a @Res() or @Response() .   If a person misses the explanation in the docs, it is a bit of a black hole to find the problem.

**Comment by kamilmysliwiec** [comment]
Unfortunately, we can't really throw an exception because (1) this would introduce a breaking change (2) we can't preassume that this is wrong in all cases (e.g., the returned value can be still accessed from the interceptors)

> a nice-to-have would be a a console warning shown when the code uses a @res() or @response() 

In addition, if someone is using `@Res` directly, we must assume that this is exactly what a developer wants to achieve. Adding an annoying console log warning her/him about this decision doesn't make too much sense.
