### ISSUE TITLE
NATS event handler throw an error when no data returned

### ISSUE THREAD

**Issue by homaily** [nestjs/nest#4874]
## Current behavior
When an event subscriber using `@EventPattern()` doesn't return data, an error will be thrown from NATS that the subject is missing.

```
/tmp/node_modules/nats/lib/nats.js:1619
      throw (new NatsError(BAD_SUBJECT_MSG, BAD_SUBJECT))
      ^
NatsError: Subject must be supplied
    at Client.publish (/tmp/node_modules/nats/lib/nats.js:1619:14)
    at /tmp/node_modules/@nestjs/microservices/server/server-nats.js:77:30
    at /tmp/node_modules/@nestjs/microservices/server/server.js:37:50
    at Array.forEach (<anonymous>)
    at /tmp/node_modules/@nestjs/microservices/server/server.js:37:32
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'BAD_SUBJECT',
  chainedError: undefined
}
```

## Input Code

```ts
@EventPattern('message')
async messageListener(@Payload() data): Promise<void> {
  console.log('data', data);
}
```

## Expected behavior
Not to throw an error

## Possible Solution
`handleMessage` method in `server-nats.ts` should check for `replyTo` before calling `getPublisher` method.
https://github.com/nestjs/nest/blob/9f14b14b9e701f317b194adb96bbe2fff4d18a49/packages/microservices/server/server-nats.ts#L104

## Environment

<pre><code>
Nest version: 7.1.2
 
For Tooling issues:
- Node version: v14.4.0
- Platform: Mac

Others:

</code></pre>

**Comment by homaily** [comment]
To add more to the context, I'm publishing the events from an external service using Nest event format `pattern, id and data`. It works when requesting a reply. But when only publishing that's when you get the error.

**Comment by kamilmysliwiec** [comment]
@johnbiundo I think you've been looking into this issue in the past, am I right?

**Comment by kamilmysliwiec** [comment]
Ping @johnbiundo (know you're busy so ignore if you dont have time now). Also @homaily, could you provide a minimum reproduction repository?

**Comment by borovik96** [comment]
This is still relevant. 
When a handler gets request without `replyTo` then the whole app will be crashed with the error 

```
/Users/vladimir/projects/test/node_modules/nats/lib/nats.js:1619
      throw (new NatsError(BAD_SUBJECT_MSG, BAD_SUBJECT))
      ^
NatsError: Subject must be supplied
    at Client.publish (/Users/vladimir/projects/test/node_modules/nats/lib/nats.js:1619:14)
    at /Users/vladimir/projects/test/node_modules/@nestjs/microservices/server/server-nats.js:68:30
    at /Users/vladimir/projects/test/node_modules/@nestjs/microservices/server/server.js:38:50
    at Array.forEach (<anonymous>)
    at /Users/vladimir/projects/test/node_modules/@nestjs/microservices/server/server.js:38:32
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'BAD_SUBJECT',
  chainedError: undefined
}
``` 

To prevent it I suggest changing `getPublisher` method:

```diff
	getPublisher(publisher, replyTo, id) {
+		if (replyTo) {
          return (response) => {
            Object.assign(response, { id });
            const outgoingResponse = this.serializer.serialize(response);
            return publisher.publish(replyTo, outgoingResponse);
          };
+		}
+		// request doesn't need reply, do nothing
+   	return () => {}
    }
```

The same technique used in the official nats repo as an example: https://github.com/nats-io/nats.js#basic-usage
![image](https://user-images.githubusercontent.com/9018702/95088263-6423fb80-072b-11eb-84f6-42710d678d2b.png)

**Comment by borovik96** [comment]
@kamilmysliwiec I think you should reopen this issue till fix will be merged

**Comment by zlooun** [comment]
@borovik96 
The bug is still present. If you send a request from one microservice that is waiting for a response to another, which is just subscribed to this event and is not going to send a response. It will still send "nothing" and it will break the first microservice.
1 microservice (that send the request):
![image](https://user-images.githubusercontent.com/50909481/152400023-b6c2251a-b6ff-4473-81cb-32d84b333b9f.png)
2 microservice (that just want to get data):
![image](https://user-images.githubusercontent.com/50909481/152399806-fb078bfe-5e55-4576-a870-155f6d43c843.png)
3 microservice (who must to reply):
![image](https://user-images.githubusercontent.com/50909481/152400173-aaed6b39-0aef-46b0-8471-184ef5114976.png)

The error (because the second microservice send reply, but it shouldn't to do it):
![image](https://user-images.githubusercontent.com/50909481/152400246-d7a55251-39d7-45d3-913a-e824793598b9.png)
