### ISSUE TITLE
Function is executed twice when emitting event inside an event handler

### ISSUE THREAD

**Issue by cre8** [nestjs/nest#4956]
## Current behavior

The following code reproduces this output when emitting inside a listener (not only when calling itself like in this simple example):
Console output:
```
call 1
call 2
call 2
```

Relevant in the following scenario:
- service A emits data (e.g. user_created)
- service B listens to them, updates them and emits them again (e.g. servers_started)
- service C listen to the results form B and fires and event service A is interested in (e.g. emails_sent)

## Input Code

```ts
  constructor(
    @Inject('PARSE_SERVICE') private client: ClientProxy,
  ) {}
  
  @EventPattern('call_me')
  event(call: number) {
    console.log('call', call);
    if (call === 1) {
      this.client.emit<number>('call_me', 2);
    }
  }

  async onApplicationBootstrap(): Promise<any> {
    await this.client.connect().catch(() => {
      console.warn('failed to connect to redis server');
    });
    this.client.emit<number>('call_me', 1);
  }
```

## Expected behavior

Console output:
```
call 1
call 2
```
## Environment

<pre><code>
Nest version: 7.1.3

 
For Tooling issues:
- Node version: 14.4.0
- Platform:  Windows 10

Others:

</code></pre>

**Comment by cre8** [comment]
Error can't be reproduced after a cache dump of the IDE, so it's not a nestjs error.

**Comment by waqarilyas** [comment]
The handler function should be in a different service file from where the event is being emitted. If the event is being emitted in "Service_A", the @OnEvent handler method should be inside a different file "Service_B". Otherwise, the function will be called twice or behave abnormally. It's mentioned in nest js documentation:
<img width="830" alt="Screenshot 2022-12-09 at 12 58 29 PM" src="https://user-images.githubusercontent.com/66460686/207331794-6b778ea4-3056-4dfb-9e50-0b158be7cd9a.png">
