### ISSUE TITLE
Future support of decorator when Typescript complies with the Javascript TC39 proposal

### ISSUE THREAD

**Issue by skyzhangty** [nestjs/nest#5030]
Hello,

    I do enjoy using the framework. My only concern is the plan of future support of decorators. 

    Currently, a decorator in Typescript is just another function, which is the first draft of the decorator proposal. 

    The proposal has been changed dramatically since and Typescript will not follow the proposal until it reaches stage 3. 

    I am wondering if the Nest team has any plan for decorators if Typescript decides to comply with the Javascript proposal. 

    Or even worse decorators will never be accepted to the final stage and typescript deprecates it.

    Thank you very much for your feedback.

**Comment by jmcdo29** [comment]
My two cents on this, Typescript most likely won't deprecate decorators due to frameworks like Nest, Angular, TypeORM, class-*, and others. There's too many libraries that already rely on such features that are widely used as if decorators were already a part of the spec. I assume if things end up drastically changing, plans will be made to accommodate the spec.

**Comment by kamilmysliwiec** [comment]
As @jmcdo29 mentioned, deprecating decorators would affect a lot of popular TS packages (probably the majority of the most popular ones). There's simply no reason for that. If anything changes, we'll accommodate the spec.

**Comment by arthu** [comment]
just found this thread! It looks like Typescript 5 has adopted stage 3 decorator, still support stage 1 when experimentalDecorators is turned on. I was wondering what's the plan to adopt stage 3 in nestjs

**Comment by micalevisk** [comment]
@arthu See https://github.com/nestjs/nest/issues/11414#issuecomment-1495794076
