### ISSUE TITLE
Update docs:  Add resolution of #443 to documentation

### ISSUE THREAD

**Issue by svstartuplab** [nestjs/nest#506]
This issue is based on a February 2018 issue that was resolved but the documentation doesn't include this solution. Exporting the service per Issue 443 solved my problem with 

    Nest can't resolve dependencies of the MembersController (?). Please verify whether [0] argument is available in the current context.

[Link to documentation](https://docs.nestjs.com/techniques/sql)

    @Module({
      imports: [TypeOrmModule.forFeature([Photo])],
      components: [PhotoService],
      controllers: [PhotoController],
      exports: [PhotoService],  //  Add this line to fix problem?  Worked for me.
    })
    export class PhotoModule {}

**Comment by kamilmysliwiec** [comment]
Hi @svstartuplab,
Honestly, I don't understand. 🙁 Could you explain a little further?

**Comment by svstartuplab** [comment]
I'm not sure what else to write.  A problem was solved but needs to be added to the documentation so users won't have to waste time with it.  Maybe this has been done recently.  I'm traveling for a month and won't have time to get back into it for a while.

**Comment by kamilmysliwiec** [comment]
I guess you have in mind that you had to export `PhotoService` in order to make this available for the rest of the application. This is explained in the documentation: https://docs.nestjs.com/modules (a little bit more meaningful in the new docs: https://docs.nestjs.com/v5). The reason why it behaves like that is Nest injector which is a bit different than this one used in Angular itself (providers work like components, they're encapsulated within modules).
