### ISSUE TITLE
Request scoped factories exception filters results in hanging response

### ISSUE THREAD

**Issue by egodsk** [nestjs/nest#5173]
## Current behavior

When throwing a custom exception with a exception filter attached inside of a request scoped factory, the user never gets a response returned if returning a custom object inside the exception filter. If the exception filter throws a new error inside an `UnhandledPromiseRejectionWarning` is thrown in the console, and the response still hangs.

## Input Code

https://github.com/egodsk/nestjs-request-scoped-errors

## Expected behavior

The user get the returned object / thrown error returned and the response is automatically terminated.

## Environment

<pre><code>
Nest version: 7.4.2
 
For Tooling issues:
- Node version: v12.18.2
- Platform:  Mac
</code></pre>

**Comment by kamilmysliwiec** [comment]
I've just pulled your repo and I have a few notes:

`CustomExceptionFilter` class:

> // throwing an error here return in an "UnhandledPromiseRejectionWarning" in the console, and response is never sent.
>    // throw new Error('test');
>
>    // throwing an HttpException here return in an "UnhandledPromiseRejectionWarning" in the console, and response is never sent.
>    throw new HttpException('test', 400);


This is the expected behavior. Filters should never be re-throwing exceptions. They **must** handle them and **send a response** (as stated in the docs).

> console.log('CustomExceptionFilter - catch - 2');
> //
> //     // Extending the BaseExceptionFilter and just calling super results in "UnhandledPromiseRejectionWarning: TypeError: > Cannot read property 'reply' of undefined"
> //     super.catch(exception, host);

The problem here is that the `BaseExceptionFilter` class requires the `applicationRef` to be passed as a first constructor argument.  This is mentioned in the docs:

![image](https://user-images.githubusercontent.com/23244943/102768930-35104400-4382-11eb-988b-7ebca75fe99e.png)

https://docs.nestjs.com/exception-filters#inheritance
