### ISSUE TITLE
Nest does not build properly

### ISSUE THREAD

**Issue by arturwita** [nestjs/nest#5243]
## Current behavior

I'm trying to import variables from a directory below my service (which was created with nestjs CLI in fact), but compilation can't be done due to Error: Cannot find module 'PATH\nest-build-bug\my-service\dist\main'. Moreover sometimes (quite often tbh) changes made in files are not detected, just as if nest build wasn't clean or it wasn't executed after a file was changed. It makes me think that there is something wrong with npm scripts / ts compiler options. I have no idea how to solve this problem - I was even trying to make changes the compiled files, but that's even worse than tragic.
 
## Input Code
[Minimal repo](https://github.com/arturwita/nest-build-bug)

## Expected behavior

Application imports properly variables from a file and is able to run the server.

## Possible Solution
- changing some npm scripts (e.g. `start` or `start:dev`)
- changing some options in tsconfig.json

## Environment

<pre><code>
- Nest version: 7.4.1
 
For Tooling issues:

- Node version: 12.16.0
- NPM version: 6.14.7
- TypeScript version: 3.9.7
- Platform:  Windows

Others:
- Microsoft Windows [Version 10.0.18362.959]
- IDE: Jetbrains Webstorm
- package manager: npm
</code></pre>

**Comment by jmcdo29** [comment]
This is an issue with directory structure rather than the tool. In short, all of your ts files should reside in the same directory unless you're building up some monorepo. If you would like to continue with your current structure, you can use the `entityFile` property of the `nest-cli.json` file. 

```ts
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "entryFile": "my-service/src/main"
}
```

In the future, please use our [Discord](https://discord.gg/nestjs) channel (Support) for help and questions. We are using GitHub to track Feature Requests, Bug Reports, and Regressions.
