### ISSUE TITLE
Extracting Express in a seperate module

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#531]
Big fan of this this framework, good work! I created a REST API with it and it works like a charm. 

My use case is an application, which has nothing to do with an webserver. Its a standalone application. Now it would be really nice to still use decorators like `@Component` or `@Module` etc. If I would want to have these features, I have to use `@nestjs/core` as  dependency in my application. Now I have the dependency `express`, even though my application does not even need it. 

It would be nice to split the functionality of all the webserver-stuff in a seperate module. For me atleast, that would fit the pattern. 
Want NestJS? Install `@nestjs/core`. 
_Need a webserver? Install `@nestjs/web`._
Need websockets? Install `@nestjs/websocket`
Need an orm? Install `@nestjs/typeorm`

Are there any plans to extract express in an seperate module?

**Comment by shekohex** [comment]
There's a helpful Links in Documentation
see.

Execution Context :https://docs.nestjs.com/execution-context
and what about a Microservice ?
I will Edit this Comment with a another Module Could help.

**Comment by BrunnerLivio** [comment]
Thanks @shekohex for the quick response. I know about these features, but thas is not what I am refering to.

I would like to use the injection / module / component functionality from NestJS, without having all the Webserver stuff.


My use case is an application, which has nothing to do with an webserver. Its a standalone application. Now it would be really nice to still use decorators like `@Component` or `@Module` etc. If I would want to have these feature I have to have `@nestjs/core` as  dependency in my application. Now I have the dependency `express`, even though my application does not even need it.

**Comment by shekohex** [comment]
That's what we were talking about a long time ago with Kamil , and seems that we are going to have something like that soon in V5 
but anyway, I was playing with `Angular` Depancy Injection Engine, and created small `Module` wrapper around it so it could be Modulear, 
see [Core101](https://GitHub.com/shekohex/core101)
it's not a framework or even ready to use, but it could be.
it was built for just learning.
i thought it could give you an inspiration to build yours
Hope I helped.

**Comment by BrunnerLivio** [comment]
>  That's what we were talking about a long time ago with Kamil , and seems that we are going to have something like that soon in V5

Thats awesome! Is this issue already a duplicate? If not, I think we should let it open for an open discussion, until it is merged. 

> see Core101

Nice work. Unfortunately I'm not allowed to use such "hacky" libraries in the company I'm working at. Building my own library is also not a good idea. I prefer to wait, until NestJS comes up with a solution

> we are going to have something like that soon in V5

How is the progress with that? On the branch `update/version-5` the core package seems to still heavily rely on express-features.

**Comment by shekohex** [comment]
I mean by `smaller something like this..` to not only rellay on Expressjs, we could use another adapters or even, without any `HttpServer` at all, by just using NextJS Context, but I don't think we are going to sprate the adapters. maybe Kamil has another Idea or solution for this.

**Comment by kamilmysliwiec** [comment]
Hi @BrunnerLivio,
The nest ecosystem can be easily used as a standalone application by making use of execution context feature. However, in what I have understood, you would like to use `@nestjs/core` without a necessity to install `express` as a part of it. The question is, why? I mean, express library is tiny, and it doesn't need a lot of resources. It's a part of a `@nestjs/core` because the most popular Nest use-case is still - a web application. Extracting even this single HTTP library would force everyone to separately install this package. That's why I'm wondering, what is more important since even though you install express, you don't have to use it.

**Comment by BrunnerLivio** [comment]
Thanks for the feedback @kamilmysliwiec. By the way, I posted your framework on [reddit](https://www.reddit.com/r/webdev/comments/880a5n/nestjs_a_progressive_nodejs_framework_for/). Many interested people :)

> The question is, why? 

Imagine if any framework / library would say this. Then you would pull for any framework / library unneeded dependencies. What I'm trying to elaborate is the NodeJS-philosophy. Small packages, so you can download what you actually need.

Another thing is, in our company we need to validate frameworks / tools etc. The more dependencies it has, the harder it gets. Off course, Express would not be a problem because it is well tested and widely used.

Also, I could imagine the core of the framework could then be used for frontend development? I would love that, because in some cases you do not want to have full framework like Angular 5 with their component-Functionality.

**Comment by kamilmysliwiec** [comment]
Hi @BrunnerLivio,
With `v5.0.0` you'll be able to use various (now express/fastify) adapters. This feature makes Nest a bit more portable and extensible so far. However, the plan is to completely extract express within `v6.0.0` which is the next major release. Thanks for convincing me 🙂

**Comment by BrunnerLivio** [comment]
Oh wow thats awesome, thanks alot! Looking forward to contribute more to NestJS.

**Comment by marcus-sa** [comment]
If you'd want I've actually extracted everything related to servers, pipes and what so ever to be external plugins that you can add.
I'd like to discuss the coding structure, should I just create a PR or a new issue?

**Comment by wbhob** [comment]
Also, splitting out frameworks would be good so that nest-middlewares can identify the framework in use and spit out the right middleware for the framework :)

**Comment by BrunnerLivio** [comment]
`@nest/platform-electron` anyone?

**Comment by wbhob** [comment]
Electron is a desktop application container, not a server framework @BrunnerLivio so idk how that would work

**Comment by BrunnerLivio** [comment]
@wbhob depends how much of `@nest/core` gets extracted I guess. If there's basically just `@Inject` and `@Module`-functionality in `@nest/core`, then I think it would be pluggable to Electron?

**Comment by wbhob** [comment]
you would use something like angular with Electron (https://electronjs.org/). Nest is a server framework and can't run in a container like electron, you would need to use a frontend framework instead

**Comment by BrunnerLivio** [comment]
Oh boy its been a long day. Sorry I just had my head somewhere else I guess. You're right off course haha

**Comment by marcus-sa** [comment]
@BrunnerLivio if you want to use the same architecture for Electron, I'd suggest you checked out mine https://github.com/marcus-sa/one/tree/master/examples/electron

**Comment by BrunnerLivio** [comment]
@marcus-sa Looks nice! Really like the `@Window()`-decorator. Lurking through your repo I suspect you've built your own framework? So this is not compatible with Nest right?

**Comment by marcus-sa** [comment]
@BrunnerLivio you're right it's not compatible with `Nest` in any way.
This uses `Inversify` which of course has it's limitations compared to coding my own Ioc, but in the end it's a way better solution because it'll make 3rd party modules way easier to intregate with providers before the actual app is instantiated.

Using `MODULE_INITIALIZER` it let's me modify the container before other modules / providers are injecting them.

https://github.com/marcus-sa/one/blob/22f72985bfabf96687a61a3437d93e6d9efe16ee/packages/electron/src/windows/windows.module.ts#L5-L32

https://github.com/marcus-sa/one/blob/22f72985bfabf96687a61a3437d93e6d9efe16ee/packages/electron/src/windows/windows.service.ts#L26-L38

https://github.com/marcus-sa/one/blob/22f72985bfabf96687a61a3437d93e6d9efe16ee/examples/electron/src/main/windows/main.window.ts#L5-L14

(Doesn't show permalinks, dafuq?)

**Comment by BrunnerLivio** [comment]
## Why

I think we should concretely discuss how the new API will look like to use NestJS running with or without Express / Fastify, so we can estimate how drastic the breaking changes of 6.0.0 will be and how much time it will take to implement something like 

## Prestudy

Angular uses the packages [@angular/platform-browser](https://www.npmjs.com/package/@angular/platform-browser) and [@angular/platform-server](https://www.npmjs.com/package/@angular/platform-server) to configure the platform it should run on. Lets have a look at `@angular/platform-browser`. This package exposes a `BrowserModule`, when imported into the ecosystem will automatically run Angular in the browser without any configuration

`app.module.ts` in an Angular Project
```TypeScript

@NgModule({
  imports: [
    BrowserModule
    [...]
   ]
})
export class AppModule {}

```

I think we can potentially adapt this for NestJS. The problem is with this approach, you have to bootstrap the Express instance in the ecosystem of Nest, which is in some cases good enough, but in some cases you want to do this outside of any module, in a `main.ts` like before with the `NestFactory`

This problem could be solved with the approach Angular Universal used. With ngExpressEngine you can specify which providers are going to be injected. I think we could expand on this and also support `imports`.

`main.ts` in an Angular project
```TypeScript

app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));

```

## Proposal

### outside Context

**Before**
`main.ts`

```TypeScript
import { NestFactory } from '@nestjs/core';
import { ApplicationModule } from './app.module';
import * as http from 'http';

async function bootstrap() {
  const server = http.createServer();
  const app = await NestFactory.create(ApplicationModule, server);
  await app.listen(3000);
}
bootstrap();
```

**After**
`main.ts`

```TypeScript
import { NestFactory } from '@nestjs/core';
import { ExpressModule } from '@nestjs/platform-express';
import { ApplicationModule } from './app.module';
import * as http from 'http';

async function bootstrap() {
  const server = http.createServer();
  const app = NestFactory.create({
    bootstrap: ApplicationModule,
    imports: [
      ExpressModule.forRoot({
        server,
        port: 3000
      })
    ]
  });
 
  await app.listen();
}
bootstrap();
```


### inside Context

```TypeScript
import { ExpressModule } from '@nestjs/platform-express';

@Module({
  imports: [ExpressModule]
})
export class ApplicationModule {}
```

**Comment by kamilmysliwiec** [comment]
The problem is that each possible solution complicates API instead of simplifying it, which does not seem to be a good idea.

**Comment by BrunnerLivio** [comment]
> The problem is that each possible solution complicates API instead of simplifying it, which does not seem to be a good idea. 

In my opinion it does not complicate it in most cases. If you do not care how the HTTP/Express instance is going to be initiated (which most people probably do not care), you can just easily import the `ExpressModule` into your ApplicationModule as described in "inside Context" from my previous comment.

For the more advanced use cases it may introduce more code (as described in "Propsoal>oustide Context>After" in my previous comment), but in my opinion modularity and consistency has its cost. But I do not think it is more complicated, it is just more code. But thanks to the Nest CLI you could bypass the initial boilerplate code.

**Comment by kamilmysliwiec** [comment]
`create()` method is supposed to be used with web apps. Plain context is created with `createApplicationContext()`. What if someone doesn't import anything, neither ExpressModule nor Fastify? Nest is mainly a web framework anyway, I believe we should provide a default option, for example, use `platform-express` internally.

**Comment by BrunnerLivio** [comment]
With my vision there would be no difference between `createApplicationContext()` and `create()`. The only purpose of `NestFactory` is to create an application context. The ExpressModule / FastifyModule will handle the HTTP tasks completely by itself. This would mean the class `NestApplication` would be completely removed and only `NestApplicationContext` would be used.

**Comment by kamilmysliwiec** [comment]
It would be worth considering the balance of usability in relation to the cost of implementation. Such changes would affect Nest ecosystem heavily, force a lot of people to adjust to the breaking changes and at the same time, brings a doubtful overall profit (since `createApplicationContext()` is in place already).

**Comment by kamilmysliwiec** [comment]
Closed by accident. Sorry

**Comment by BrunnerLivio** [comment]
I really do not think it would not break too much. Sure, the downside is every application would have to migrate, but in my opinion it would be pretty easy to migrate. 

But maybe I'm just too ignorant and not seeing how much it would effect the ecosystem. So easiest way to find out would be to just run a feasibility. I'll try to get a `ExpressModule` as described running, just with the current `createApplicationContext()`. If I realize that this would be too hard, or it would break the public API too extremely, then we should definitely go a different route. But first I have to focus on other issues, before I can hack around :)

**Comment by kamilmysliwiec** [comment]
My thoughts:
1. Extract `express` specific stuff, respectively: `ExpressAdapter`, `ExpressFactory` and all related interfaces to `@nestjs/platform-express` + `MulterModule` and `FIleInterceptor` which is compatible only with express.
2. Same with `socket.io`, `ws` and `fastify` ^
3. Since express would be still used by default, we could dynamically require `express` package (same as we did we with `class-validator` inside `ValidationPipe` for example)
4. A separate package enables us to force the installation of `@types/express` so we could provide a strong typings for express instance.

All this stuff shouldn't break API and should require a minimal amount of additional work.

**Comment by shekohex** [comment]
If we need more developer experience on migration, @nestjs/cli should help on this.

I think if we could have a sub-command `nest fix` or `nest migrate` or maybe `nest doctor`

Which would do a static analysis on the project or on the package.json itself and provide a `warn` or a notic about missing packages or `@types`.

**Comment by BrunnerLivio** [comment]
@kamilmysliwiec I think this is a great idea. But a downside what bugs me is, if a user want to create his own platform, he’d have to modify the core. With Angular it is the other way round and in my opinion a bit of a cleaner solution. You simply have to use [createPlatform](https://angular.io/api/core/createPlatform).

What are your thoughts about this?

**Comment by wbhob** [comment]
I think we're taking this idea of "breaking api" too seriously. Things break between major versions, and it's for the _overall_, _long-term_ improvement of the library. As long as we're offering adequate commnunity support (migration guides and explanations, primarily), I think devs will appreciate a cleaner design.

**Comment by kamilmysliwiec** [comment]
> @kamilmysliwiec I think this would be a great step forward. But a downside what bugs me is, if a user want to create his own platform, he’d have to modify the core (correct me if I’m wrong). With Angular it is the other way round and in my opinion a bit of a cleaner solution. You simply have to use createPlatform.

He wouldn't have to modify the core in this solution :) `create` method would be changed to somewhat more generic one which accepts T parameter and returns a mixin object for example (standard app + merged platform-specific methods).

> I think we're taking this idea of "breaking api" too seriously. Things break between major versions, and it's for the overall, long-term improvement of the library. As long as we're offering adequate commnunity support (migration guides and explanations, primarily), I think devs will appreciate a cleaner design.

The problem really is is that this change doesn't help 99% of the community at all. I would prefer to achieve cleaner design without forcing them to change stuff which completely doesn't affect them. We need to keep in mind that Nest is being used in the vast majority to create web apps.

**Comment by wbhob** [comment]
What I mean by cleaner design is cleaner syntax/style. And, to that end, it _does_ affect them because they will have a cleaner, more maintainable codebase. My one qualm with Nest apps, which I have already expressed, is that it's not logically organized. 

That isn't your fault, since Nest was never designed to be this big; when you started Nest, you just had to keep adding bits and pieces, and now it's in someways more cluttered than it needs to be. What @shekohex and @BrunnerLivio and I are offering are to a) get involved with the community, take a survey, and see if these changes matter to the community (which, in my experience, is what I am hearing from Nest devs); b) work with you as the lead dev to make a plan for how to adapt it to meet the community's needs; c) split up tasks and build towards v6; and d) help the community with the transition. Every bit of the framework affects your users, and so starting from the drawing board to make it more intuitive for them will contribute to developer happiness and growth.

**Comment by kamilmysliwiec** [comment]
> What I mean by cleaner design is cleaner syntax/style. And, to that end, it does affect them because they will have a cleaner, more maintainable codebase. My one qualm with Nest apps, which I have already expressed, is that it's not logically organized. That isn't your fault, since Nest was never designed to be this big; when you started Nest, you just had to keep adding bits and pieces, and now it's in someways more cluttered than it needs to be.

I tend to disagree. The way of defining whether something is clean or not depends on the point of personal view and overall concept of the framework. Yours is different and it's fine but the way how you articulate your opinion is very unpleasant ("that isn't your fault" suggests in advance that someone made a mistake, it's unkind in such conversation and it's sad that you're doing it for such a long time already). Nest was designed not to be a copy of Angular(!), but also to stay as close to express as possible. This library is used across majorities of Node.js apps and it was a very important goal to make the transition smooth for most of the people. The target was always to become a web-platform and at the same time, to keep codebase platform-agnostic and flexible (but still with keeping in mind that web is the biggest target, the most essential one and steps to start building web app should be very easy, pretty straightforward). Please, keep in mind that we're going our path, we don't want to reflect Angular but combine what is best from both worlds. 

Also, I would like to emphasize that I really care about the opinion of the community. People like @shekohex and @BrunnerLivio are heavily committed, they take care of dedicated 3rd-party libraries, they help with issues and are always open to help people which is incredibly awesome and I really appreciate it because it helps me a lot. Besides, they tend to express their opinion and propose solutions in a kind way, keeping the discussion away from personal attacks which I respect very strongly. I have my own vision how the core maintainers team should be built and I'm going to follow it because it's definitely a requirement to have a solid support of the people, who can help with additional packages as well as with typical issues & and core stuff. And this team is forming "automatically" in the background (without "offerring"), I believe that these people who have a real impact on the framework (like @BrunnerLivio who have recently become an organization member, @shekohex, @nartc with its swagger commitment, @weeco, @jbpionnier who went trough the whole codebase already I believe 😅  and a lot of other people who are making pull requests that provide new features, proposed functionalities, creates libraries and so on) and at the same time are able to have friendly and cultural conversations will at some point eventually become the part of a bigger team (obviously, if they want to).

Furthermore, I would like to point out that you are already talking about the exact same topic in several places, a bunch of issues and so on, hence, this is my last response to your post which such suggestions ^ you can use it as a reference everywhere.

**Comment by adrien2p** [comment]
Hey @bashleigh, in fact the module container store all the modules through the app. You can go through them to find what you need for the custom decorator. 

I used it in one of my 3rd party module if you want an example.

https://github.com/adrien2p/nestjs-dialogflow/blob/master/src/module/dialog-flow.provider.ts

I hope that can be used as an example, @kamilmysliwiec could see me if something is wrong in the usage. I very appreciate the work done on the framework, that’s why i keep learning on it and stay informed about any issues and news throught my emails ^^

**Comment by BrunnerLivio** [comment]
@adrien2p @bashleigh Thanks a lot for your enthusiasm towards NestJS. 

But this topic is regarding the extraction of the express module, so please focus on that topic. That is why I will mark as off topic, because the issue is too cluttered anyway.

Nonetheless I highly encourage you to create issues regarding your concerns (How we should handle the “nest community” org / moduleRef best practice) or contact Kamil directly using Gitter if your concern is subjective.

**Comment by marcus-sa** [comment]
@wbhob unfortunately Kamil doesn't approve of that, already created a PR regarding it and it was declined due to core being entirely rewritten and using Inversify over Nests own DI. Imo there's no reason to reinvent the wheel, when Inversify improves developer experience and extensibility.

**Comment by BrunnerLivio** [comment]
6.0.0 has been released with `@nestjs/platform-express` and `@nestjs/platform-fastify` which fixes this (2nd oldest open) issue :) 🎉 🎉
