### ISSUE TITLE
Pipes, interceptors (etc) priority

### ISSUE THREAD

**Issue by anyx** [nestjs/nest#541]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Pipes are running in sequence 'globalMetadata', 'classMetadata', 'methodMetadata'. 

## Expected behavior

Pipes are running in reverse sequence from concrete to common - 'methodMetadata',  'classMetadata', 'globalMetadata'. 

## What is the motivation / use case for changing the behavior?

For example, you have some global pipe, which transform request params to database entities
```
@Get(':id')
async getOneAction(@RequestEntity() bot: Bot): Promise<Bot> {
    return bot;
}
```
RequestEntity decorator returns some data for global pipe. Global pipe with injected database service returns entity. But now for certain actions you might have to set additional parameters to database query through another pipe:

```
@Get(':id')
async getOneAction(@RequestEntity({}, new OnlyActiveEntityPipe()) bot: Bot): Promise<Bot> {
    return bot;
}
```
but right now pipe OnlyActiveEntityPipe can be executed only after global pipe

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Looks like right now there is no way to change priority for pipes (interceptors): they are running in sequence 'globalMetadata', 'classMetadata', 'methodMetatada'. 
I think, feature for setting priority for certain pipes might be useful.

Also, the logic when pipes are running from concrete to common appears more straightforward (and more useful)

**Comment by kamilmysliwiec** [comment]
Hi @anyx,
Thanks for sharing your thoughts. 
```
Also, the logic when pipes are running from concrete to common appears more straightforward (and more useful)
```
All features, including pipes, interceptors, guards, and exception filters are running from common to concrete due to keeping a consistency between them, making them cohesive, and intuitive when you think about the incoming request as a pipeline. Think about interceptors, they follow a simple request processing pipeline, being executed from global to concrete once the request wants to hit an end-handler, and then (in response pipeline), they are executed from concrete to global (if you attach some asynchronous/mapping logic inside them and so on). It looks the same with guards. You could have a global authorization guard, then (tied at class-level) roles guard, and afterward (tied at method-level) permission guard that checks a set of user permissions to validate whether the request should be handled or not. Let's think about pipes - same here we should start with simple DTO validation (using, let's say built-in `ValidationPipe`), then, at class-level, we could have `UserByIdPipe` that selects user by ID passed in DTO.

```
RequestEntity decorator returns some data for global pipe. Global pipe with injected database service returns entity. But now for certain actions you might have to set additional parameters to database query through another pipe:
```
In your case, you should rather use interceptor that makes use of `Reflector`. Through `@ReflectMetadata()` decorator, you should define a metadata to the particular handler which then you could reflect inside the interceptor, and based on picked value - run an appropriate database query. Afterward, attach the result to the `request` object and pull out this value using custom decorators feature. 🙂

**Comment by trainerbill** [comment]
@kamilmysliwiec I have an interceptor applied at the controller level that is doing a db lookup and attaching an entity to request.team if an id parameter is provided.  I also have a custom decorator to extract the value in the controller method.

Now i am trying to implement a guard, at the method level, that would deny access if request.team.ownerId !== request.user.id but the guard is always executed before the interceptor.  So request.team is always undefined.

Do you have any suggestions on this use case?
