### ISSUE TITLE
[Fastify] req.cookies is undefined in middleware

### ISSUE THREAD

**Issue by numToStr** [nestjs/nest#5483]
## Bug Report
Although I am using `fastify-cookie` plugin. I can access `req.cookies` in `onRequest` and `onResponse` hooks and even in the controllers. But, `req.cookies` is undefined in middleware.

## Current behavior
`req.cookies` is undefined in middleware.

## Input Code

- Added `console.log`
- Added `onRequest` and `onResponse` hooks

Reproduction: https://github.com/numToStr/nest-cookie-issue

## Expected behavior
`req.cookies` should not be undefined if the `fastify-cookie` plugin is used. Also middlewares are called after `onResponse` hook, so cookies should be present.

## Environment

```
"@nestjs/common": "^7.4.4",
"@nestjs/core": "^7.4.4",
"@nestjs/platform-fastify": "^7.4.4",
"fastify": "^3.4.1",
"fastify-cookie": "^4.1.0",
 
For Tooling issues:
- Node version: v12.18.4
- Platform: Linux hello-pc 5.8.6-1-MANJARO
```

**Comment by jmcdo29** [comment]
Nest's middleware use `middie` to be Express compliant, but to do this, the `req` and `res` passed to the middleware are Fastify's `req.raw` and `res.raw`, meaning the `IncomingMessage` and `ServerResponse` typed objects instead of `FastifyRequest` and `FastifyReply` typed objects. This allows for compatibility with _most_ other middleware, and as such, will likely not be changed. If you're looking for a package to help work with cookies, there is [nest-cookies](https://github.com/jmcdo29/nest-cookies) (disclaimer: I'm the author). Other than that, you can [visit our Discord](https://discord.gg/nestjs) for more support.

**Comment by numToStr** [comment]
@jmcdo29 Thanks for the response. But, I have some questions.

- So, I suppose this issue will stay as it is?
- And What's the difference between `nest-cookie` and `@nestjsplus/cookies`?

**Comment by jmcdo29** [comment]
* Due to how Nest makes use of `middie`, probably. Kind of a problem when trying to support Express and Fastify with their different `req` structures.
* `nest-cookies` was inspired by `@nestjsplus/cookies`, I'm actually a maintainer of both, but as the core maintainer of `@nestjsplus/cookies` has been away for a while, and there are some support issues with the project (needs to have `@nestjs/graphql` installed, must import from path rather than project name, doesn't support Fastify) I figured I would provide a supplementary package in the meantime. I'm hoping to eventually move the code base from `nest-cookies` to `@nestjsplus/cookies`. Also, `nest-cookies` is a cookie parser **and** cookie setter. `@nestjsplus/cookies` requires you to install a cookie parser yourself.

**Comment by numToStr** [comment]
Yeah, I can understand that supporting both framework can be cumbersome.

I will give `nest-cookies` a try ✌🏻.

And just a quick suggestion, currently there is no docs regarding cookie handling, as this is a common task and dev might face this "issue" again. So, it might be worth adding to the docs.

**Comment by kamilmysliwiec** [comment]
Contributions to the documentation are more than welcome. I fully agree that having a dedicated chapter for handling cookies would be great :) We could showcase all the possible approaches @numToStr @jmcdo29

**Comment by Cavdy** [comment]
I was able to handle this by getting the cookie from the headers

`  const unParsedCookie = request.headers.cookie;
    const splitUnParsedCookie = unParsedCookie?.split(';');
    let cookies = {};
    splitUnParsedCookie?.forEach((cookie) => {
      const splitCookie = utils.removeAllSpaces(cookie).split('=');
      const obj = { [splitCookie[0]]: splitCookie[1] };
      cookies = { ...cookies, ...obj };
    });

    console.log(cookies['cookieName'])`

**Comment by Cavdy** [comment]
I was able to resolve this by getting the cookie from the headers

```
    const unParsedCookie = request.headers.cookie;
    const splitUnParsedCookie = unParsedCookie?.split(';');
    let cookies = {};
    splitUnParsedCookie?.forEach((cookie) => {
      const splitCookie = utils.removeAllSpaces(cookie).split('=');
      const obj = { [splitCookie[0]]: splitCookie[1] };
      cookies = { ...cookies, ...obj };
    });

    console.log(cookies['cookieName'])
```
