### ISSUE TITLE
monorepo ignores all apps but the main

### ISSUE THREAD

**Issue by azizoid** [nestjs/nest#5577]
Followed the tutorial
nest new app1
nest generate app1 app2
nest build 
nest build "app1"
nest build "app2"

in all cases it builds the default app (app1) have no idea how to make it build all apps, or at least second app too

**Comment by jmcdo29** [comment]
<details>

<summary>I'm not sure what you're seeing, but this is what happens when I follow the flow</summary>
<pre>
▶ nest new monorepo-test -p npm
⚡  We will scaffold your app in a few seconds..

CREATE monorepo-test/.eslintrc.js (663 bytes)
CREATE monorepo-test/.prettierrc (51 bytes)
CREATE monorepo-test/README.md (3370 bytes)
CREATE monorepo-test/nest-cli.json (64 bytes)
CREATE monorepo-test/package.json (1895 bytes)
CREATE monorepo-test/tsconfig.build.json (97 bytes)
CREATE monorepo-test/tsconfig.json (339 bytes)
CREATE monorepo-test/src/app.controller.spec.ts (617 bytes)
CREATE monorepo-test/src/app.controller.ts (274 bytes)
CREATE monorepo-test/src/app.module.ts (249 bytes)
CREATE monorepo-test/src/app.service.ts (142 bytes)
CREATE monorepo-test/src/main.ts (208 bytes)
CREATE monorepo-test/test/app.e2e-spec.ts (630 bytes)
CREATE monorepo-test/test/jest-e2e.json (183 bytes)

✔ Installation in progress... ☕

🚀  Successfully created project monorepo-test
👉  Get started with the following commands:

$ cd monorepo-test
$ npm run start

                                         
                          Thanks for installing Nest 🙏
                 Please consider donating to our open collective
                        to help us maintain this package.
                                         
                                         
               🍷  Donate: https://opencollective.com/nest
                                         

~/Documents/code                                                               
▶ cd monorepo-test 

Documents/code/monorepo-test  master ✗                                      ◒  
▶ nest generate app app1 && nest g app app2
CREATE apps/monorepo-test/tsconfig.app.json (228 bytes)
CREATE apps/app1/tsconfig.app.json (219 bytes)
CREATE apps/app1/src/app.controller.spec.ts (617 bytes)
CREATE apps/app1/src/app.controller.ts (274 bytes)
CREATE apps/app1/src/app.module.ts (249 bytes)
CREATE apps/app1/src/app.service.ts (142 bytes)
CREATE apps/app1/src/main.ts (208 bytes)
CREATE apps/app1/test/app.e2e-spec.ts (561 bytes)
CREATE apps/app1/test/jest-e2e.json (183 bytes)
UPDATE tsconfig.json (355 bytes)
UPDATE package.json (1957 bytes)
UPDATE nest-cli.json (758 bytes)
CREATE apps/app2/tsconfig.app.json (219 bytes)
CREATE apps/app2/src/app.controller.spec.ts (617 bytes)
CREATE apps/app2/src/app.controller.ts (274 bytes)
CREATE apps/app2/src/app.module.ts (249 bytes)
CREATE apps/app2/src/app.service.ts (142 bytes)
CREATE apps/app2/src/main.ts (208 bytes)
CREATE apps/app2/test/app.e2e-spec.ts (561 bytes)
CREATE apps/app2/test/jest-e2e.json (183 bytes)
UPDATE tsconfig.json (355 bytes)
UPDATE package.json (1957 bytes)
UPDATE nest-cli.json (988 bytes)

Documents/code/monorepo-test  master ✗                                      ◒  
▶ nest build
Hash: a0b6772fde37c1d9f8b3
Version: webpack 4.44.1
Time: 2839ms
Built at: 10/17/2020 11:18:15 AM
Entrypoint main = apps/monorepo-test/main.js

Documents/code/monorepo-test  master ✗                                      ◒  
▶ nest build app1
Hash: a0b6772fde37c1d9f8b3
Version: webpack 4.44.1
Time: 2542ms
Built at: 10/17/2020 11:18:24 AM
Entrypoint main = apps/app1/main.js

Documents/code/monorepo-test  master ✗                                      ◒  
▶ nest build app2
Hash: a0b6772fde37c1d9f8b3
Version: webpack 4.44.1
Time: 2455ms
Built at: 10/17/2020 11:18:33 AM
Entrypoint main = apps/app2/main.js
</pre>
</details>

All of the `nest build X` commands are working as expected.
