### ISSUE TITLE
NestJS - Not instantiating some providers at the start of the app

### ISSUE THREAD

**Issue by DavideCarvalho** [nestjs/nest#5618]
## Bug Report
We are using a PubSub to separate the GameficationModule from the rest of the app, but the services inside the GameficationModule are not being instantiated at the start of the app if they have some dependency with other services.

## Input Code

Repo: https://github.com/DavideCarvalho/newschool-backend/tree/fix/nestjs-not-instantiating-services

I've removed every typeorm dependency, so just run ``npm run start:dev`` and it should work.

Send a POST request to ```http://localhost:8080/api/v1/test/117d44fe-22db-4b59-8c00-f9bb33103dbe/checkTest/alternative/A``` and you can see that it won't work, but if you enter CourseRewardsService and remove CourseTakenService dependency, it should work fine, in other words, we will receive "inside checkTestReward" log on terminal

## Expected behavior

We should be able to see ``inside CourseRewardsService constructor`` and ``inside CourseRewardsService onModuleInit``, and we should be able to see ``inside checkTestReward`` even if CourseRewardsService has a dependency with CourseTakenService

## Environment

<pre><code>
Nest version: X.Y.Z

 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jmcdo29** [comment]
Looks like in your `CourseTakenService` you have `@Inject(PublisherService)` which is `REQUEST` scoped. (this happens by default when you add `@Inject(REQUEST)`. As mentioned in [your other issue](https://github.com/nestjs/nest/issues/5600) if a service is request scoped, it can't be instantiated until there is a request, which is why you don't see the logs you are expecting.

If you _really_ need to make use of request scoping the `PublisherService` and need `CourseTakenService` to be non-request scoped, you can make use of `ModuleRef` and the `ContextIdFactory` as [described in the docs](https://docs.nestjs.com/fundamentals/module-ref#resolving-scoped-providers), but you'll need to resolve the current `PublisherService` on each call manually, so take that into account.

**Comment by DavideCarvalho** [comment]
My problem isn't PublisherService that much, but why CourseRewardsService isn't being instantiated at the start of the application.

Debugging a little more, I could see that if ``CourseRewardsService `` has a dependency that depends on ``PublisherService``, it can't be instantiated at the start of the app, but if it is dependency free (or has a dependency that has nothing to do with ``PublisherService``), it is instantiated at the start of the app normally

**Comment by jmcdo29** [comment]
Exactly, because `PublisherService` is `REQUEST` scoped, and as such, adding it to `CourseRewardsService` makes it inherently `REQUEST` scoped, so it can't be created until a request comes in. It's all a part of the [scope hierarchy](https://docs.nestjs.com/fundamentals/injection-scopes#scope-hierarchy)

**Comment by DavideCarvalho** [comment]
Oh, now everything makes sense to me, @jmcdo29 thank you very much.
