### ISSUE TITLE
Documentation doesn't have the types for some entities

### ISSUE THREAD

**Issue by WeekendMan** [nestjs/nest#567]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Learning the docs.

What is the type of the injected @Res, @Params, @Headers and other params of the controller methods? You omitted these types in the documentation so they are just "any", I'd like to use typed entities.

Your table with decorators comparison contains @Request, @Response etc items, but you have @Res, @Req decorators in the code samples.

Can you add variable/returned types everywhere in the code samples? It will be pretty easier to understand instead of searching in the sources.

</code></pre>

**Comment by shekohex** [comment]
I think this will help,

> There's a @types/express package and we strongly recommend to use it (Request has its own typings).

```ts
import { Request } from 'express';
import { Controller, Get, Req } from '@nestjs/common';

@Controller('cats')
export class CatsController {
    @Get()
    findAll(@Req() request: Request) {
        return [];
    }
}
```

**Comment by WeekendMan** [comment]
Right from the express, hmm.
Thanks a lot, will know it.

It would be great to see explicit types for properties/returned types in docs, it increases readability of the docs in 100500 times.

**Comment by kamilmysliwiec** [comment]
I agree, but `@types/express` is an optional package. That's why we cannot include those types explicitly. Furthermore, we want to achieve a full portability, meaning, to make Nest loosely coupled from HTTP provider that is used in the background, and therefore we shouldn't copy & paste express typings and serve them from `@nestjs` packages. Unfortunately, there're no typings in the official express package, that would solve this issue.
