### ISSUE TITLE
Cannot use repository defined in external package using @nestjs/typeorm

### ISSUE THREAD

**Issue by pavel-luhin** [nestjs/nest#5700]
## Current behavior
I have custom abstract repository with some logic in external `common` package. I am trying to use it in my application, but nestjs throws with error that it cannot find the repository for injection.
It seems that the problem here
![image](https://user-images.githubusercontent.com/8158004/99158364-021fc400-26e3-11eb-857e-a92a2b2ce4ab.png)
condition `entity.prototype instanceof typeorm_1.Repository` is false because repository from outer package use not the same typeorm dependency as my app (but they have the same version).

## Expected behavior
Repository should be created and injected.

## Environment

<pre><code>
Nest version: 7.0.0
TypeORM version: ^0.2.29
Nest TypeORM version: ^7.1.4

 
For Tooling issues:
- Node version: v14.10.1
- Platform:  Mac
</code></pre>

**Comment by jmcdo29** [comment]
Please provide a minimum reproduction repository.

**Comment by pavel-luhin** [comment]
Here it is
https://github.com/pavel-luhin/nest-external-repository

**Comment by kamilmysliwiec** [comment]
> is false because repository from outer package use not the same typeorm dependency as my app (but they have the same version).

You should specify `typeorm` as a peer dependency of your library. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by Irungaray** [comment]
Hi, I came to this issue several times in the current week as I was debugging something similar that we have done in my company.

Attempting to kill the monolith, we created 2 libraries, 'common' and 'core'.
Common contains plain objects like DTOs, enums, claims and entities (and its migrations).
Core contains the files that handles bussiness logic such as services, repositories and mappers.

We came onto this and other errors by the like when we started to consume 'core' in a new microservice.

The problem (i think) was that we were installing the 'core' package from the local folder, and it came with the package's node_modules, so all the code in 'core', specifically, everything from 'typeorm', was being instantiated from the package's node_modules, and not from the consumer node_modules.

The solution was to publish the package and install it from the NPM registry instead of installing it from a local folder.

Hope it helps someone in the future.
