### ISSUE TITLE
Swagger @ApiResponse does not accept ts types as a value in type property

### ISSUE THREAD

**Issue by Pacheco95** [nestjs/nest#5721]
```ts
// userNotificationDocument.ts
export type UserNotificationDocument = UserNotification & Document;

// userController.ts
@Get('user/notifications')
@ApiResponse({ status: HttpStatus.OK, type: [UserNotificationDocument] }) // `'UserNotificationDocument' only refers to a type, but is being used as a value here.`
@ApiOperation({ summary: "get all user's notifications" })
async getUserNotifications(
  @Body('userId') userId: string,
  @Body('filters') filters: UserNotificationFilters,
): Promise<any> {
  return this.userService
    .getNotifications(userId, filters)
    .then((notifications) => ({
      data: notifications,
    }));
}
```
Is there a way to pass types to `@ApiResponse`?

Note: it is impossible to get help on discord channel 😒.

**Comment by jmcdo29** [comment]
Types don't exist at runtime, so there's nothing for the decorator to work with if you provide a `type` type instead of a `class` type. 

> Note: it is impossible to get help on discord channel 😒.

Apologies, but I don't believe I've seen your message on the Discord channel. It's a shame that most people that post there only post to _get_ support and not _give_ support, but those of us who do, do it voluntarily, just as this project is open source. If you have a better suggestion, great, but if not, then please don't bring forth such criticisms. They aren't constructive and provide no real value.
