### ISSUE TITLE
app.getUrl() doesn't resolve in the listen callback

### ISSUE THREAD

**Issue by Sikora00** [nestjs/nest#5798]
## Current behavior
I want to display the address on which the app is running from the "listen" method callback. Currently, app.getUrl () never gets resolved and nothing is displayed.

## Input Code
```ts
  await app.listen(port, '0.0.0.0', async () => {
    console.log(`Application is running on: ${await app.getUrl()}`);
  });
```

## Expected behavior
The app url should be resolved in this place.

## Possible Solution
I see in the source code that inside NestApplication.getUrl() we need to wait for 'listening' event to be emitted from httpServer 
```ts
this.httpServer.on('listening', () => {...})
```
Probably we shouldn't wait for this event after it was once emitted.

I tested that when I write it like that, the second console.log is displayed properly.
```ts
  await app.listen(port, '0.0.0.0', async () => {
    console.log(1, await app.getUrl());
  });
  console.log(2, await.getUrl());
```

## Environment

<pre><code>
Nest version: 7.5.5
Platform Fastify: 7.5.5

 
For Tooling issues:
- Node version: 12.18.1  
- Platform:  Ubuntu 20

Others:

</code></pre>

**Comment by Tony133** [comment]
hi, @Sikora00 I usually do like this:

```
  await app.listen(3000);
  console.log(`Application is running on: ${await app.getUrl()}`);
```

**Comment by kamilmysliwiec** [comment]
cc'ing @jmcdo29 as this is related to the `#getUrl()` method. Perhaps, we can just add an additional condition to immediately trigger the "onListening" callback when `httpServer.address()` already returns !== `null`. What do you think?

**Comment by jmcdo29** [comment]
PR ready for review. Turns out, `this.isListening` should have been moved up to before `app.listen()` to make sure `app.getUrl()` doesn't error out in the callback.

**Comment by jmcdo29** [comment]
Let's track this here: #5802

**Comment by cjmyles** [comment]
> Hi, @Sikora00 I usually do like this:
> 
> ```
>   await app.listen(3000);
>   console.log(`Application is running on: ${await app.getUrl()}`);
> ```

@Tony133 I do the same but I get the output `Application is running on: http://[::1]:5000`. This happens locally and on the deployed server. Any ideas? I can raise a new bug request if it requires further debug.

**Comment by Tony133** [comment]
@cjmyles Also has me from so `Application is running on: http://[:: 1]:3000`, doing so:

```
  await app.listen(3000);
  console.log(`Application is running on: ${await app.getUrl()}`);
```

if you want to see ip instead like this: `The application is running on: http: //127.0.0.1: 3000`, doing so:

```
  await app.listen(3000, '0.0.0.0');
  console.log(`Application is running on: ${await app.getUrl()}`);
```

although maybe the first method was nicer, but something has changed see here #5802

**Comment by cjmyles** [comment]
@Tony133 changing `await app.listen(3000);` to `await app.listen(3000, '0.0.0.0');` worked for me, thanks!

**Comment by ehaynes99** [comment]
I can open a new issue if you like, but the change made doesn't fix this issue. The test is a false positive. It returns the `Promise` returned by `app.listen`, and `app.listen` doesn't wait for the server to start listening. The unresolved promise used by the `expect` gets orphaned. Adding the `done` callback demonstrates this:

```typescript
it('should return 127.0.0.1 even in a callback', (done) => {
  const app = testModule.createNestApplication(new ExpressAdapter(express()));
  return app.listen(port, async () => {
    expect(await app.getUrl()).to.be.eql(`http://127.0.0.1:${port}`);
    await app.close();
    done()
  });
});
```

`getUrl` doesn't resolve because the promise it returns is resolved by the `httpServer.on('listening'` event. If the method is called **AFTER** that event has already fired, the promise will never resolve. Cases where it does work like the example from @Tony133 above won the race condition, creating the promise after `this.httpAdapter.listen` was called but before the adapter fires the event.

The fix here creates just one event handler & promise, storing the promise for future calls to `getUrl`.
https://github.com/nestjs/nest/pull/7285
