### ISSUE TITLE
Save HTTP exception description as a property of HttpException

### ISSUE THREAD

**Issue by egormkn** [nestjs/nest#5809]
## Is your feature request related to a problem? Please describe.

I have an issue when implementing a custom ExceptionFilter for an MVC application. When the exception filter catches a HttpException, I want to render a template with HTTP error code, description, and message (e.g. `401 Unauthorized: Wrong username or password`). While I can easily get error code and message, getting the HTTP error description (`Unauthorized` in this case) is harder than it should be: it is stored in the `error` property of JSON response. At the same time HttpException has a `name` property, that is always initialized to `'Error'`.

## Describe the solution you'd like

I'd like the `name` property of HttpException to be initialized with HTTP error description.

## Teachability, Documentation, Adoption, Migration Strategy

Here is how it can be used:
```typescript
import { Catch, ArgumentsHost, HttpStatus, Logger, ExceptionFilter, HttpException } from '@nestjs/common';
import { Request, Response } from 'express';

@Catch()
export class DefaultExceptionFilter implements ExceptionFilter<any> {
  private readonly logger = new Logger('ExceptionHandler');

  catch(exception: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const req = ctx.getRequest<Request>();
    const res = ctx.getResponse<Response>();
                         // now it is always equal to 'Error' ---v
    const name = exception instanceof HttpException ? exception.name : 'Internal Server Error';
    const message = exception instanceof HttpException ? exception.message : '';
    const status =
      exception instanceof HttpException ? exception.getStatus() : HttpStatus.INTERNAL_SERVER_ERROR;

    res.status(status).render('error', { name, message, status });
    if (!(exception instanceof HttpException)) {
      return 'message' in exception
        ? this.logger.error(exception.message, exception.stack)
        : this.logger.error(exception);
    }
  }
}
```

**Comment by kamilmysliwiec** [comment]
> I'd like the name property of HttpException to be initialized with HTTP error description.

`name` property should be equal to the name of the class. Currently it's always `Error` (which is incorrect). I'll fix it shortly.

In the meantime, you can use this:
```typescript
Object.getPrototypeOf(exception).constructor.name
```

as w workaround

**Comment by egormkn** [comment]
I think that it would be nice to be able to get a human-readable description of an error (`Not Found` instead of `NotFoundException`). While I can drop the 'Exception' part and split by uppercase letters, that doesn't seem to be the right way. :smiley: 
I thought about adding an optional third `description` argument to the HttpException constructor, that will save description from its subclasses.

**Comment by coder-freestyle** [comment]
Hi @kamilmysliwiec, I have created a PR for this issue.

**Comment by kamilmysliwiec** [comment]
You could always generate a human-readable description based on the serialized class names (e.g., by adding spaces between uppercased characters). Let's track this here https://github.com/nestjs/nest/pull/5859

**Comment by JaapWeijland** [comment]
Hi there, sorry to resurrect this issue, but I think I experience something that is related and thus not yet fixed.

I have two files, a service and a controller. In the service, I perform an API call. When this API call returns a response indicating that I am unauthorized, I throw a `new UnauthorizedException()`. The controller catches all errors thrown by the service, checks them and if needed, complements them. An `UnauthorizedException` may be rethrown as is, so I do the following to check whether the error is an `UnauthorizedException`:

```
try {
...
} catch (error) {
    if (error instanceof UnauthorizedException) throw error;
    throw new InternalServerErrorException(error);
}
```

_However, `error instanceof UnauthorizedException` always returns `false`._ I did some research and stumbled upon the following FAQ about Typescript: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work. Since `UnauthorizedException` is an indirect subclass of `Error`, I think we're dealing with the same kind of issue here, namely that the prototype of the error is incorrectly set. Is this correct?

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
