### ISSUE TITLE
Improved Circular Dependency Logging

### ISSUE THREAD

**Issue by sloanbholzman** [nestjs/nest#5847]
## Feature Request
If there is a circular dependency, display the full cycle to make it easier to identify the issue

## Is your feature request related to a problem? Please describe.
I have had circular dependency errors that were very hard to track down.

For example:

```
(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope [ScriptModule -> Registration2Module -> AnswerModule]
 +4ms
Error: Nest cannot create the module instance. Often, this is because of a circular dependency between modules. Use forwardRef() to avoid it.
(Read more: https://docs.nestjs.com/fundamentals/circular-dependency)
Scope [ScriptModule -> Registration2Module -> AnswerModule]
```

AnswerModule ended up having a dependency on Registrations, but it was several layers down and I had to search through each dependency of AnswerModule individually, and then their dependencies, and then their dependencies, etc in order to find it.

## Describe the solution you'd like
Ideally, the full cycle would be identified so that for any dependency issue, the logging shows the module/service that is circularly referencing itself.  In other words, the logging for a circular dependency should _always_ mention a module/service twice.

## What is the motivation / use case for changing the behavior?
It is challenging to debug some circular dependencies

**Comment by kamilmysliwiec** [comment]
This has been discussed a few times in the past, we even had a draft PR for this but it turned out there are simply too many edge-cases to cover and the actual change could have brought more issues than benefits. The issue is that - when the circular dependency occurs - some classes are represented as `undefined` values. The cycle you shared (`[ScriptModule -> Registration2Module -> AnswerModule]`) means, that we detected an undefined value in the `AnswerModule` (in the imports array) and that's all we know from Nest core perspective.
