### ISSUE TITLE
NatsOptions if not on par with nats.js connect options

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6054]
## Current behavior
According to the [documentation](https://docs.nestjs.com/microservices/nats#options) the NatsOptions does have the same properties as the [nats.js connect options](https://github.com/nats-io/nats.js#connect-options). 

Actually it does have fewer properties, e.g. `token` or `timeout` is missing:

```ts
export interface NatsOptions {
    transport?: Transport.NATS;
    options?: {
        url?: string;
        name?: string;
        user?: string;
        pass?: string;
        maxReconnectAttempts?: number;
        reconnectTimeWait?: number;
        servers?: string[];
        reconnect?: boolean;
        pedantic?: boolean;
        tls?: any;
        queue?: string;
        serializer?: Serializer;
        deserializer?: Deserializer;
        userJWT?: string;
        nonceSigner?: any;
        userCreds?: any;
    };
}
```

I have read somewhere that Nest is just passing the options object to nats.js but this does not seem to be the case. At least I tested setting token and timeout with supressing ts errors but they did not have any effect.

## Expected behavior
It should be equal or allow any.

## Environment

<pre><code>
Nest version: 7.6.5

**Comment by jmcdo29** [comment]
[This should be setting up the server](https://github.com/nestjs/nest/blob/master/packages/microservices/server/server-nats.ts#L72) and [this should be the client](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-nats.ts#L46). As you can tell, Nest does just pass the options on to the underlying package. Interesting that the options passed aren't doing what you'd expect.

Regardless, an update could be made for the nats options object. Would you like to make a PR to update the types (and maybe add `[key: string]: any` so that extra values can be added more easily)?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/6062
