### ISSUE TITLE
[Feature Request]: Nested Exceptions

### ISSUE THREAD

**Issue by ruscon** [nestjs/nest#6259]
## Describe the solution you'd like

I would like to suggest a similar solution
https://symfony.com/doc/current/contributing/code/stack_trace.html#nested-exceptions

**Comment by jmcdo29** [comment]
I'm not sure what the use case is here, or at least, what Nest's role here would be. If you wanted, you could extend the `HttpException` object and add the `previous` property to it so that something like that could be possible, but (personally) I don't see the need for it. If you could add more details, like the Feature Request template asks you for, then maybe we could get a better understanding of why you think this is important.

**Comment by kamilmysliwiec** [comment]
Agree with @jmcdo29 on that

**Comment by ruscon** [comment]
> you could extend the HttpException object and add the previous property

Then I can't use all the other nestjs exception classes extended from `HttpException` :)

**Comment by jmcdo29** [comment]
> > you could extend the HttpException object and add the previous property
> 
> Then I can't use all the other nestjs exception classes extended from `HttpException` :)

True, but without more information on _why_ you want this, we don't really see this is a useful addition to the `HttpException` class

**Comment by ruscon** [comment]
@jmcdo29 I added a link to an article with a real example
