### ISSUE TITLE
Improve support for serverless (lazy loading)

### ISSUE THREAD

**Issue by yardz** [nestjs/nest#6265]
## Is your feature request related to a problem? Please describe.
I'm currently using Nestjs with firebase functions. As I need to load several modules due to coldstart, the startup time is very high, some cases almost 3 seconds

## Describe the solution you'd like
it would be interesting to have some way to load the modules as they are being requested. For example, I have the "orders" module that uses the "products" module and I also have the "users" module.
When I make a request to get user information, the "products" and "orders" modules are loaded, but will not be used (now).
In this case, these modules consume a lot of time in the coldstart even if they have not been used yet. This module may be used later or not, as this is the context of serverless functions

## Teachability, Documentation, Adoption, Migration Strategy

I thought of something like that:
The default behavior is what happens today, this "asLazy" option would be to enable lazy loading
```ts

@Module({
	controllers: [UsersController],
	providers: [UsersService],
	exports: [UsersService],
})
export class UsersModule {}

@Module({
	imports: [],
	controllers: [ProductsController],
	providers: [ProductsService],
	exports: [ProductsService],
})
export class ProductsModule {}

@Module({
	imports: [
		Example01Module, // these module will be loaded after the "OrdersModule" is loaded
		ProductsModule.asLazy(), // these modules will only be loaded after being requested inside "OrdersModule"
		UsersModule.asLazy(),
	],
	controllers: [OrdersController],
	providers: [OrdersService],
	exports: [OrdersService],
})
export class OrdersModule {}
@Module({
	imports: [
		Example01Module, // this module loads when the application starts (default behavior)
		Example02Module, // this module loads when the application starts (default behavior)
		Example03Module, // this module loads when the application starts (default behavior)
		ProductsModule.asLazy(), // these modules will only be loaded after being requested
		OrdersModule.asLazy(), // these modules will only be loaded after being requested
		UsersModule.asLazy(), // these modules will only be loaded after being requested
	],
	controllers: [OrdersController],
	providers: [OrdersService],
	exports: [OrdersService],
})
export class AppModule {}


```
## What is the motivation / use case for changing the behavior?
Serverless. Nest initialization is very slow when trying to apply to the serverless context.
A very lean application loads with 2 or 3 seconds (in firebase functions). If you add that to the computation time, the response would be very high. This reduction in coldstart time would reduce costs ($$) and create a better user experience.

There was an issue in 2019 with the same request, but it didn't go ahead. I believe there was a lack of context when creating it. (https://github.com/nestjs/nest/issues/2587)

**Comment by Gbuomprisco** [comment]
I would have the same need, would love to see a way to dynamically load modules (or a similar strategy)

**Comment by jlarmstrongiv** [comment]
It would also be great to optionally return a 503 Service Unavailable after loading particular modules dynamically.  

For example, loading [serverless-chrome](https://github.com/adieuadieu/serverless-chrome) takes ~20 seconds.  Running the task with serverless chrome takes another ~20 seconds.  AWS API Gateway has a maximum timeout of 29 seconds.  

If the loading and task take place during the same request, it’s a guaranteed timeout error.  

If the loading occurs and returns a 503, followed by another successful request, I won’t hit that timeout error 😄 

It’s not just serverless chrome, but also other large libraries like tensorflow.  I find myself depending on this behavior.  Currently, I’m returning a 503 when the entire app has initialized, but being able to do that for specific modules would be great.

**Comment by jlarmstrongiv** [comment]
Lazy loading would be very helpful!  There’s other pain points with serverless, and I think NextJS has the potential to alleviate or document them.  

<details>
 <summary>This may be better for a separate issue though</summary>
<br>

- Deployment examples
  - Platforms:  Nextjs API Routes, @vercel/node, claudiajs, serverless, and more
  - Each platform has it’s own quirks and it’s been a [journey](https://github.com/jlarmstrongiv/create-vercel-http-server-handler#readme) figuring all that out (especially with NextJS)
- Timeouts
  - Lambda timeouts are incredibly short
    - NextJS API routes (10sec), AWS Lambda with API Gateway (29sec), @vercel/node (60sec)
  - Some modules have a particularly long startup time
      - For example, [@serverless-chrome/lambda](https://www.npmjs.com/package/@serverless-chrome/lambda) and [tfjs-node-lambda](https://www.npmjs.com/package/tfjs-node-lambda)
      - When you combine the startup time with a long task, you are almost guaranteed to hit a timeout.  An official way to automatically send either an 503 Service Unavailable after the startup would be great.  
      - Lazy loading is a great way to help shorten that startup time
- Caching
  - Nestjs has a significant startup time.  When deploying to serverless, I always cache the initialized application.
    - Currently, I’m using a server listening on a local socket with [http-proxy](https://www.npmjs.com/package/http-proxy).  The [lambda-request-handler](https://www.npmjs.com/package/lambda-request-handler) package doesn’t rely on a background server, but it doesn’t cache the app, so it’s actually slower with starting up NestJS on every request (will try [serverless-http](https://www.npmjs.com/package/serverless-http) next).
- Dependency pruning 
  - Similar to the now deprecated [bundled-nest](https://github.com/ZenSoftware/bundled-nest)
  - [modclean](https://www.npmjs.com/package/modclean) or [node-prune](https://www.npmjs.com/package/node-prune)
  - It’s very easy to hit the 50MB lambda zip limit
- Native modules
  - NodeJS C++ addons need to be built per node version on the right OS
  - For example, the commonly used [SharpJS](https://sharp.pixelplumbing.com/) package for images
  - I’ve found the most success with [docker scripts](https://www.npmjs.com/package/create-vercel-http-server-handler#scripts) or [commands](https://www.rookout.com/blog/3-min-hack-for-locally-building-a-native-extension)

</details>

**Comment by leandro-manifesto** [comment]
I had that same use case and opened [this issue](https://github.com/nestjs/nest/issues/3886) a while back.

**Comment by kamilmysliwiec** [comment]
This one is tricky. Basically, if you think about providers, these are simple classes (or functions/values in case of custom providers syntax) that we should be able to instantiate/run lazily. However, controllers (or resolvers in GQL apps, which in fact must be registered as providers) represent sets of routes/paths/topics (or queries/mutations) depending on the type of the application, and that makes it way tougher. For example, let's say you're building a REST API (HTTP) with a Fastify driver under the hood (`@nestjs/platform-fastify`). Fastify does not let you register routes **after** the application is ready/successfully listening to messages. That means lazy loaded routes wouldn't be accessible at all (since we cannot register them). Likewise, some transport strategies we provide in the `@nestjs/microservices` package require to subscribe/listen to specific topics/channels before the connection is established. Once you start listening to messages, you won't be able to lazily load any controllers.

That means, in theory, we could at least provide a way to lazily instantiate providers (without controllers), and while this sounds easier, there are no simple solutions to that either. For example, we could expose an API to lazily load a module with its providers (and that's something that can be considered), but you couldn't be able to inject any of these providers through constructors of eagerly loaded classes (since they were created & instantiated already in eager modules). The only way to access these lazy instances would be through methods (e.g., `moduleRef.get()` or `moduleRef.resolve()`) which kinda breaks the whole idea of the DI system for all routes that depend on lazily-loaded providers (another key thing here is that you would have to keep controllers and providers in separate modules). A benefit here is that this solution would allow us to split chunks at the bundle level (by tools like webpack) improving the overall bootstrap time even further.

Alternatively, we could wrap all lazy providers and controllers(! this isn't doable with the solution above) in proxies and just load them on-demand, calling a constructor on the first interaction with a class. However, this wouldn't let bundlers like webpack split our code into multiple chunks, nor significantly speed-up the bootstrap time as the only difference between a regular application now and this one (just described) would be that constructors (or functions of factories) wouldn't be called immediately (but all the wiring-up modules, reading metadata logic, connecting interceptors/guards etc would still be required).

**Comment by kamilmysliwiec** [comment]
> For example, we could expose an API to lazily load a module with its providers (and that's something that can be considered)

Let's track this here https://github.com/nestjs/nest/pull/6386
