### ISSUE TITLE
@ALL() decorator issue with fastify

### ISSUE THREAD

**Issue by rathax** [nestjs/nest#6281]
## Current behavior
using the @All() and the @Header() decorators on a controller in an app that uses the FastifyAdapter throws:
```
TypeError: response.header is not a function
```
## Input Code

```ts
  @All()
  @Header('test', 'test')
  getHello(): string {
    return this.appService.getHello();
  }
}
```

## Expected behavior
it should correctly add the headers as it does with the default expressAdapter

## Environment

<pre><code>
Nest version: X.Y.Z
    "@nestjs/common": "^7.5.1",
    "@nestjs/core": "^7.5.1",
    "@nestjs/platform-fastify": "^7.6.7",
 
For Tooling issues:
- Node version: v14.5.0
- Platform:  Windows

**Comment by Tony133** [comment]
Hi @rathax,  I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported. 

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by kamilmysliwiec** [comment]
When you annotate your method with `@All()` decorator, Nest will use the `router.use()` method to register it (instead of using `router.all()`) and that means your route handler will receive the unwrapped request and response objects when your application uses `@nestjs/platform-fastify` driver. This has been fixed in this PR https://github.com/nestjs/nest/pull/6237 and will be changed in the next major release.
