### ISSUE TITLE
V5 - req.BaseUrl is empty

### ISSUE THREAD

**Issue by thaoula** [nestjs/nest#630]
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

When injecting @Req() req in a controller, req.BasePath is returning "" rather than the router path.

## Expected behavior

According to express and previously in V4 ... it should return the router path i.e /api/users

## Environment

<pre><code>
Nest version: 5.0.0-rc2

 
For Tooling issues:
- Node version: 10  
- Platform:  Mac (docker for mac) 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Hi @thaoula,
In terms of the request object, nothing has changed in the incoming `v5.0.0`. Is `BaseUrl` the only missing property?

**Comment by thaoula** [comment]
Hi @kamilmysliwiec,

I cannot say for sure if the only missing property. However, our code which was relying on the BaseUrl to do a redirect stopped working.

We got "" for baseUrl on req object rather than the controller url of ("/api" + "/users" set in @Component). 

I hard coded the base Url for now. 

I reported the issues as it was discovered by accident when a small area of our application stopped working.

The application was relying on a redirect -
res.redirect(`${req.baseUrl}/detail?detail=1`);

I had to change it too -
res.redirect(`**/api/users**/detail?detail=1`);

Regards,
Tarek

**Comment by kamilmysliwiec** [comment]
Read here: https://github.com/expressjs/express/issues/3125#issuecomment-260134822
Nest no longer uses routers concept.

**Comment by enVolt** [comment]
I've noticed the same behavior when stream is ended .

We are using [express-bunyan-logger](https://github.com/villadora/express-bunyan-logger) package to log the HTTP request. These logs are pushed to ELK setup for visualization purpose. Since the requested URL is matched, I needed a way to log the pattern of the route for some analytical purpose.

Here is my code-structure - 

> routes.js
```javascript
...
app.use("/questions", require("../app/routes/question");
...
```

> ..app/routes/question
```javascript
const express = require('express');
const router = express.Router();

router.get(
    "/slug/:slug",
    QuestionController.getQuestionBySlug
);
```

Inside the `getQuestionBySlug`, I'm actually using the `req.baseUrl` for something (not going into the specifics). The value of `req.baseUrl` is `/questions` always. 

I wanted to log the route pattern, which should've been `req.baseUrl + req.route.path`. But it keeps logging `/slug/:slug`. 

I'm not able to figure out what's wrong, but basis on what I could debug once the stream is ended (`close` or `finish` event is emitted on `req`), the value of `req.baseUrl` is changed to empty strings `""`. (the logger library logs the event once the event is emitted [https://github.com/villadora/express-bunyan-logger/blob/master/index.js#L193](https://github.com/villadora/express-bunyan-logger/blob/master/index.js#L193))
