### ISSUE TITLE
Your `PlayerRepository` depends on the `Connection` object which is unavailable in your testing module. Instead of using `TypeOrmModule.forFeature([Player])`, you should mock your repository manually.  https://docs.nestjs.com/techniques/database#testing

### ISSUE THREAD

**Issue by whytekieran** [nestjs/nest#6317]
Your `PlayerRepository` depends on the `Connection` object which is unavailable in your testing module. Instead of using `TypeOrmModule.forFeature([Player])`, you should mock your repository manually.  https://docs.nestjs.com/techniques/database#testing

_Originally posted by @kamilmysliwiec in https://github.com/nestjs/nest/issues/2569#issuecomment-511193974_

I have tried following the documentation posted here and mentioned in several forums however to be honest I'm not following what I'm being instructed to do. I get the concept of custom providers and what is being said but I just don't get what I'm supposed to do. Honestly the documentation at times is very disappointing especially when it comes to trying to find a simple example of what is being described, at times its very vague. Can someone just show me a code example of how to do this? I hope in the future better documentation is coming to fill these gaps

**Comment by kamilmysliwiec** [comment]
How do you want to create a repository which acts as an abstraction representing your database and relying on the connection without having the connection established and registered in the IoC container?

>  Instead of using TypeOrmModule.forFeature([Player]), you should mock your repository manually.

By saying this, I meant you should provide a mock for the repository since TypeORM requires the database connection to create one. There are several ways to do that (e.g., `overrideProvider` (see testing docs) or custom providers https://docs.nestjs.com/techniques/database#testing).

> Honestly the documentation at times is very disappointing especially when it comes to trying to find a simple example of what is being described, at times its very vague. Can someone just show me a code example of how to do this? I hope in the future better documentation is coming to fill these gaps

Contributions to the documentation are more than welcome https://github.com/nestjs/docs.nestjs.com Feel free to fix whatever sounds too vague & could be described in a better way.

In the future please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
