### ISSUE TITLE
Issue https://github.com/nestjs/nest/issues/6317

### ISSUE THREAD

**Issue by whytekieran** [nestjs/nest#6319]
## Feature Request

Attempted to use discord for support but wouldnt log me in. Requesting new features to be added to documentation. Recently reached out here: https://github.com/nestjs/nest/issues/6317 and was left disappointed with the response.

I was told there are "several ways of doing" the things I'm trying to do, but where are the examples? Why are these several different approaches not shown clearly in the documentation? Why is there only a paragraph that explains little to nothing.

I was told if id like to contribute to documentation I can which is cool however that's not why I'm here. What I want is someone to actually add these "several ways" of doing things to the current documentation with clear examples.

**Comment by jmcdo29** [comment]
The docs don't explicitly show examples on that so that people don't think that it "has to be done this way". For the community, I created [testing-nestjs](https://github.com/jmcdo29/testing-nestjs) to show _some_ ways testing can be done. There's a lot of examples there, using some auto-mockers, and manually creating tests in other cases. 

The docs say that we need to create a [custom provider](https://docs.nestjs.com/fundamentals/custom-providers) to be injected instead of the actual repository (due to the dependency on the `Connection` object and other TypeORM necessities). Then you can provide what a `Repository` instance looks like. Nest doesn't show that because A) everyone's needs are different here, and B) there's so many different ways and combinations of methods that could be used just between mocking libraries alone (jest, sinon, ts-mockito, the list goes on), so a lot of this is left up to the dev. [There's also this StackOverflow answer](https://stackoverflow.com/questions/57099863/spyon-typeorm-repository-to-change-the-return-value-for-unit-testing-nestjs/57122036#57122036) that provides a decent approach with `useClass` instead of `useValue`.
