### ISSUE TITLE
WS does not invoke custom validator with injection

### ISSUE THREAD

**Issue by TrejGun** [nestjs/nest#6440]
## Current behavior
WebSockets does not invoke custom validator with injection
Native and custom validators without injection are fine

<img width="626" alt="Screen Shot 2021-02-18 at 2 18 03 PM" src="https://user-images.githubusercontent.com/185285/108314142-5fe90e00-71f4-11eb-82e0-6f60f52ad193.png">

It also works perfectly fine with REST endpoints

## Input Code
https://github.com/TrejGun/nestjs-ws-validation-bug

## Expected behavior
validator should be invoked

## Possible Solution
unknown

## Environment

<pre><code>
Nest version: 7.6.12

 
For Tooling issues:
- Node version: v14.15.4  
- Platform:  mac Catalina 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
I'm looking at your repository now and from what I can see, there are several missing steps you need to take in order to integrate `class-validator` IoC container and Nest container. Registering `ValidateCustomNumberWithInjection` class as a provider is not how you do it.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions (or check out older issues). We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by TrejGun** [comment]
@kamilmysliwiec 

yes there should be 
```
useContainer(app.select(AppModule), {fallbackOnErrors: true});
```
in the bootstrap function which is present in my real application (and now in example too)

anyways this setup works with REST endpoints but just silently fails with WS
there should be some error message about unresolved dependencies i guess
if it does not throw any error considered as a bug

**Comment by TrejGun** [comment]
actually yes. I forgot @ValidatorConstraint() and it seems to be working now
