### ISSUE TITLE
 TypeError: redisIoAdapter is not a function

### ISSUE THREAD

**Issue by twigs67** [nestjs/nest#6474]
I know socket 3 is expected to work with the next major release, but I'm trying to get it working on socket 2 and am running into this issue. Any idea how to get this working?

```
{
  "dependencies": {
    "@nestjs/platform-express": "^7.5.1",
    "@nestjs/platform-socket.io": "^7.6.11",
    "@nestjs/websockets": "^7.6.11",
    "@types/redis": "^2.8.28",
    "redis": "^3.0.2",
    "socket.io": "^3.1.1",
    "socket.io-redis": "^5.0.0",
  },
  "devDependencies": {
    "@types/socket.io": "^2.1.13",
  },
}
```

**Comment by Tony133** [comment]
Hi @twigs67, I advise you to leave a minimal reproduction of a clonable git repository so that the core team can evaluate the problem you have reported.

However if you have difficulty you can always use the [discord](https://discord.com/invite/G7Qnnhy) channel for support.

**Comment by jmcdo29** [comment]
@twigs67 you can try to follow the adapter made in [this issue](https://github.com/nestjs/nest/issues/5676). Otherwise as mentioned, Socket.IO v3 is not, and will not be supported until Nest v8. You currently have socket.io 3 installed, which is probably an issue. Please take this to our [Discord](https://discord.gg/nestjs) for more support
