### ISSUE TITLE
RMQ skip queue assert

### ISSUE THREAD

**Issue by Caperious** [nestjs/nest#6539]
## Is your feature request related to a problem? Please describe.

We are trying to use the RabbitMQ microservice package on an existing queue. During the setup the microservice asserts the queue. We want to skip this step, as the queues are created ahead of time and we do not know the queue options.

## Describe the solution you'd like

Add an option in the parameters to skip the queue assertion. The drawback is that any possible errors should be handled if the queue does not exist.

## What is the motivation / use case for changing the behavior?

We are trying to create a configurable worker, which could be used as a worker for the RabbitMQ queues. The worker could be added to existing queues and handle the message appropriately. We have 20+ queues and all the queues are defined upfront.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? 

Also, just FYI you can workaround this following this chapter https://docs.nestjs.com/microservices/custom-transport and in the "Creating a strategy", you could extend the existing `ServerRMQ` class instead of `Server`.

![image](https://user-images.githubusercontent.com/23244943/109484435-b837cf80-7a80-11eb-83b3-169078f2d5fc.png)

**Comment by Caperious** [comment]
Thank you for your very quick response. I got it to work using the workaround you mentioned. Awesome work, awesome project, awesome team. Keep up the good work!

I can still try to create a PR, but it will take some time as I'm currently on a tight schedule.

**Comment by kamilmysliwiec** [comment]
Thank you @Caperious! Maybe instead of creating a PR to the core, would you like to add a new section to the docs showing how you've extended an existing strategy https://github.com/nestjs/docs.nestjs.com/edit/master/content/microservices/custom-transport.md? That would be very beneficial to other people for sure!

**Comment by kamilmysliwiec** [comment]
Ping @Caperious 🏓  Let me know! If you're busy, Ill just close this issue

**Comment by Caperious** [comment]
Yeah sure, i'll add a new section to the docs.. Will let you know, when its done!

**Comment by kamilmysliwiec** [comment]
That's great, thank you @Caperious 🙌
