### ISSUE TITLE
Microservice's ClientProxy should make client instance's public

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6670]
## Feature Request

When using using ClientProxy, e.g. [ClientNats](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-nats.ts), it holds an instance of the used client but it is not accessible. It would be great if it is, e.g. [socket.io-nats-adapter](https://github.com/MickL/socket.io-nats-adapter) requires an instance of a nats client but I cant reuse the existing one:

```ts
constructor(
    @Inject(MY_CLIENT) private natsClient: ClientProxy,
  ) {
      const io = createAdapter(natsClient.natsClient); // Currently not possible

      io.emit('hello');
  }
```

Instead I have to create another one manually:

```ts
constructor(
    @Inject(OPTIONS) private options: MyOptions,
  ) {
    const natsClient = connect(this.options.url, {
      token: options.token,
    });
    const io = createAdapter(natsClient); // Currently not possible

    io.emit('hello');
  }
```

**Comment by kamilmysliwiec** [comment]
This has been discussed several times in the past, please search for old issues for more context.

In short: if you need more control, use the transporter driver (package) directly instead of relying on `@nestjs/microservices` decorators/abstractions (you can use the driver in combination with the Standalone Apps https://docs.nestjs.com/standalone-applications feature if you need a separate app OR just register a connection/client as a custom provider).
