### ISSUE TITLE
Using the microservice client proxy to subscribe

### ISSUE THREAD

**Issue by MickL** [nestjs/nest#6671]
## Is your feature request related to a problem? Please describe.
If I am not mistaken the only way to subscribe to microservice events is to create a microservice app and create a controller and then use `@MessagePattern` or  `@EventPattern` decorator. This is very unhandy if I just want to listen for some event here and there.

E.g. I want to listen for something and clear the cache but I dont want to make my app a hybrid app and create an extra controller for that.

## Describe the solution you'd like
We have the `ClientProxy` that, e.g. for nats, holds a `Client` instance [here](https://github.com/nestjs/nest/blob/master/packages/microservices/client/client-nats.ts#L15). Therefor `ClientProxy` could easily provide a subscribe function.

If the client instance, e.g. natsClient, would be public I could use it myself to subscribe and even do [other things with it](https://github.com/nestjs/nest/issues/6670).

**Comment by kamilmysliwiec** [comment]
This has been discussed several times in the past, please search for old issues for more context.

In short: if you need more control, use the transporter driver (package) directly instead of relying on `@nestjs/microservices` decorators/abstractions (you can use the driver in combination with the Standalone Apps https://docs.nestjs.com/standalone-applications feature if you need a separate app OR just register a connection/client as a custom provider).
