### ISSUE TITLE
Non exported tokens can be replaced by external modules

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#6751]
## Current behavior

Providing a token from a module permits to override the token of modules of other scopes.

Consider the following example:

```ts
import {DynamicModule, Module} from "@nestjs/common";
import {NestFactory} from "@nestjs/core";

@Module({
    providers: [{
        provide: 'Foo',
        useValue: 'This is foo'
    }]
})
export class MainModule {

}

@Module({
    providers: [
        {
            provide: 'Foo',
            useValue: 'This is bar'
        }
    ]
})
class SecondaryModule {

}

NestFactory.createMicroservice(<DynamicModule>{
    module: MainModule,
    imports: [
        SecondaryModule
    ]
}).then((app) => {
    console.warn(app.get('Foo')); // this is bar
});
```

Executing the above code, `SecondaryModule`, a dependency of `MainModule`, actually replace `'Foo'` with another value.

# Expected behavior

Per documentation, non-exported providers are non-public: `Thus, you may consider the exported providers from a module as the module's public interface, or API.`

https://docs.nestjs.com/modules

Executing the above code, `SecondaryModule`, a dependency of `MainModule`, should not be allowed tp replace `'Foo'` with another value.

# Is this a bug or a feature?

According to the documentation - and my interpreation of the terms `Thus, you may consider the exported providers from a module as the module's public interface, or API` - `'Foo'` is not part of the module's public interface and hence is private. It should then not be replaceable by a dependency.

Now, the documentation may mean that the privacy only concerns the injection of a provider, not its replacement. Which in my opinion is not less an issue: allowing a private provider to be replaced while forbidding it to be injected goes against is analoguous to give private properties a public setter but a private getter, which is probably not what people expect when they think about privacy scope.

# Questions

* Is this a bug or a feature?
* In case this is a feature, shouldn't the documentation clarify this point?
* In case this is a feature, what mechanism do NestJS provide to mark a provider _setter_ as private?

**Comment by jmcdo29** [comment]
Can you provide this code in a clonable git repo?

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. Just to provide you with somewhat more information on that: you can register multiple providers using the same token (there's no restriction preventing you from doing that) in different modules (and there will be no collision), and Nest will use this one that's available in the resolution context (there are also more advanced techniques where you can override providers in certain modules if needed). So for example, if you had another provider registered in the `MainModule` that relies on `"Foo"` provider, Nest would inject `"This is foo"`. However, in the context of the `SecondaryModule` (so assuming you have another provider there [..]), it would inject `"This is bar"`. Still, if you exported `"Foo"` from the `SecondaryModule` and override it in the `MainModule`, Nest will use this one closer to the "inquirer provider" (so in this case, `"This is foo"` from the `MainModule`). `app.get()` itself is a slightly different subject as it's not tied to any specific context - it performs a lookup through the entire container (you can read more about it here https://docs.nestjs.com/standalone-applications). For example, in your case, to obtain the `"Foo"` registered in the `MainModule`, you could use the following line: `app.select(MainModule).get("Foo", { strict: true })`. You should be able to find all that in the docs.

For further questions, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support).

**Comment by ericmorand** [comment]
@kamilmysliwiec :

> Nest will use this one closer to the "inquirer provider"

Doesn'i mean that you can't replace a provider at all? Let's consider the following modules:

```ts
@Module({
    providers: [
        {
            provide: 'Foo',
            useValue: 'foo'
        },
        {
            provide: 'FooConsumer',
            useFactory: (foo: string) => {
                return 'Consumed ' + foo;
            },
            inject: ['Foo']
        }
    ],
    exports: ['Foo']
})
class MainModule {}

@Module({
    imports: [
        MainModule
    ],
    providers: [
        {
            provide: 'Foo',
            useValue: 'bar'
        }
    ]
})
class OtherModule {}
```

OtherModule replace the token 'Foo' of MainModule.

Your comment seems to imply that 'FooConsumer' would be resolved to 'Consumed foo' instead of 'Consumed bar' since MainModule's 'Foo' is closer to MainModule's 'FooConsumer' than OtherModule's 'Foo'.

Is it true?

And if so, how are modules supposed to replace tokens exposed by imported modules without relying on tight dependency coupling - namely the usage of static factories like proposed  in the documentation?

**Comment by kamilmysliwiec** [comment]
> For further questions, please, use our Discord channel (support).
