### ISSUE TITLE
[Discussion] What's the future of NestJS ?

### ISSUE THREAD

**Issue by rahiyansafz** [nestjs/nest#6784]
![NESTJSFUTURE](https://user-images.githubusercontent.com/70625091/112772144-155b7c80-9051-11eb-9949-31f3b4a45a5e.png)

@kamilmysliwiec you said that there are some bindings. so how do you guaranty the future of nestjs? because we are already loving nest, and it is the best thing that ever happened to us <3 

and we want it to be the best nodejs framework, 
so we want better features, better performance and updates and a clear future vision of nest! 

i hope you understood what was trying to tell,
and i hope you'll say something.

**Comment by kamilmysliwiec** [comment]
Thank you @rahiyansafz!

As for your question, nothing has changed ever since. We still use "Issues" & milestones to keep track of what we have on our radar for the upcoming releases, whether these are small improvements or new, extra features. You can also check out the "Pull requests" tab to see what we/community are currently working. If there's anything you'd like to see in Nest, we suggest creating an issue and we'll definitely consider it. Also, if you're willing to contribute to any of the existing issues, PRs are more than welcome!
