### ISSUE TITLE
BUG: the "ttl" option of CacheModule doesn't work when use with redis

### ISSUE THREAD

**Issue by DevAngsy** [nestjs/nest#6804]
## Current behavior

[Mini Repo: nestjs-bugs](https://github.com/DevAngsy/nestjs-bugs)

As shown in the pictures below, default "ttl" option is 30 seconds. 

- If use redis store and do not use "CacheTTL" decorator, first send a GET request to "http://127.0.0.1:3000/app", then view the "ttl" of cache entry of redis, the value is -1, means no expiration time, so this is a bug.
- If use redis store and use "CacheTTL" decorator to override default "ttl" option, it works properly, cache entry of redis will delete automatically.
- If do not use redis store, regardless of the default "ttl" or "CacheTTL", it works properly too, cache entry will delete automatically.

## Input Code

The CacheModule:
![2021-03-30 21-29-11屏幕截图](https://user-images.githubusercontent.com/27341089/112996753-084ca380-919f-11eb-9a1b-63c4b2221d3c.png)
The Controller:
![2021-03-30 21-29-27屏幕截图](https://user-images.githubusercontent.com/27341089/112996888-2ca88000-919f-11eb-8f44-04cb52e25950.png)
The redis GUI, as you can see, the value of ttl is -1, it's initial value should be 30:
![2021-03-30 21-56-26屏幕截图](https://user-images.githubusercontent.com/27341089/113000880-d3dae680-91a2-11eb-84c4-06a7ab3972b6.png)

## Expected behavior

If don't use "CacheTTL" decorator, sub-library should properly use defualt "ttl".

## Possible Solution

The "cache-manager-ioredis" library accept "option" argument, but value is undefined when use with redis store and do not use 
 "CacheTTL" decorator.

## Environment
<pre><code>
OS Version: Ubuntu 20.04.2 LTS
CPU: Intel® Core™ i5-9600K
NodeJS Version: 14.16.0
Global NPM Version: 7.7.5
Ubuntu Redis Version: V6
</code></pre>

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by DevAngsy** [comment]
I'm so sorry, i'm a newcomer... i cannot position the bug point in code.
I expect you could fix this issue.

**Comment by tonivj5** [comment]
Hey @DevAngsy, I have checked what is happening here and it's a bug of `cache-manager-ioredis` itself (https://github.com/dabroek/node-cache-manager-ioredis/issues/14). A bit of context:

- When cache manager (`CM` from now on) creates ioredis cache manager (`ICM` from now on), [it passes your returned object from `useFactory` to `ICM`](https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/caching.js#L22).
- If `ICM` doesn't receive a `redisInstance` option, it creates a new Redis instance [passing your object](https://github.com/dabroek/node-cache-manager-ioredis/blob/master/index.js#L16). 
- `ioredis` use that object as [its options](https://github.com/luin/ioredis/blob/master/lib/redis/index.ts#L143) (so the `Redis`' options has a `ttl`, `max`, ... property assigned).
- And `ICM` uses the `Redis`' options as [its `storeOptions`](https://github.com/dabroek/node-cache-manager-ioredis/blob/master/index.js#L19). As `ioredis` does a shallow copy of the object you pass, it "works" 😸 
- What is the problem then? When you set a `redisInstance`, [`ICM` doesn't use anymore the rest of options](https://github.com/dabroek/node-cache-manager-ioredis/blob/master/index.js#L7), and that `redisInstance` has not any `ttl` property (or any other from cache options), but `ICM` follows using the options from the `Redis` instance... 
- Why it works when you use `@CacheTTL`? Because [`set`](https://github.com/nestjs/nest/blob/master/packages/common/cache/interceptors/cache.interceptor.ts#L55-L56) is called with an [`options` object](https://github.com/dabroek/node-cache-manager-ioredis/blob/master/index.js#L44), and `ICM` uses it instead of "`storeOptions`".

[`node-cache-manager-redis-store` does the same](https://github.com/dabroek/node-cache-manager-redis-store/blob/master/index.js#L5), but it not allow to pass a redis instance.

What could you do?
- Fork it and fix it (you can copy it and fix it into your own project too, it's a file only)
- Try to get attention to this PR https://github.com/dabroek/node-cache-manager-ioredis/pull/15 or make a better one, that PR only take in count `ttl` but other properties will be missing too.
- Set a `ttl`, `max`, ... to your client or redis options.

**Comment by kamilmysliwiec** [comment]
Thank you @Tony133 🙌  As this doesn't seem to be directly related to Nest, let me close this issue.
