### ISSUE TITLE
Documentation of Core Features

### ISSUE THREAD

**Issue by johncmunson** [nestjs/nest#6872]
It seems a little problematic that core parts of the NestJS public API are just left undocumented.

For example, I was able to learn about the DiscoveryModule and the DiscoveryService by reading [some random blog post](https://itnext.io/advanced-nestjs-techniques-part-1-custom-decorators-aa6d7f85c5b6). These seem like quite useful parts of the framework, especially when your app grows and you need to take architecture, organization, and decoupling more seriously, yet there is absolutely no mention of the DiscoveryModule anywhere in the official docs.

This is perhaps the third or fourth time where I have encountered a scenario like this, which is why I was prompted to create this issue.

Don't get me wrong, the documentation that does exist is very very good. I love how it's broken out into "Fundamentals", "Techniques", plus some additional guides for things like microservices, GraphQL, websockets, etc.

However, what seems to be lacking is a comprehensive _API Reference_. Here are some great examples of what I'm talking about.
- [React](https://reactjs.org/docs/react-api.html)
- [Angular](https://angular.io/api)
- [Express](https://expressjs.com/en/4x/api.html)
- [Next.js](https://nextjs.org/docs/api-reference/cli)

Are there any plans or efforts being made to improve the documentation in this regard?

**Comment by jmcdo29** [comment]
There's an [open pull request in the docs repo to add API docs](https://github.com/nestjs/docs.nestjs.com/pull/413), but it's been stale for a while due to challenges that were ran into. It's something we'd love to provide for the community, especially as it will help with growth. There's more information about what can be done in the PR. Unfortunately, as supporting Nest is not the full time job of any of us, it's hard to dedicate enough time to get an amazing API documentation going, but it is something we're interested in

**Comment by johncmunson** [comment]
Ahh, sorry I didn't see that before opening this issue! Feel free to close. Glad it's on the team's radar. Keep up the great work 👍
