### ISSUE TITLE
Why Nest js?

### ISSUE THREAD

**Issue by Mr-Hqq** [nestjs/nest#693]
Whats Different about nest to another frameworks?
Why we have to use nest.js?

Please say your opinion.

**Comment by chanlito** [comment]
`Typescript`

**Comment by marcus-sa** [comment]
Nest.js leverages what I would call a high quality codebase.
What I really like about it is how familiar it is to the code structure of Angular, aka decorator based (metadata annotation as to what it is called in other languages) and the support of TypeScript.

OFFT:
What I really wish, is that at the beginning Nest.js would've had separate plugins for all the server stuff, so I didn't have to tear it apart myself.

**Comment by Grimscythe1983** [comment]
Type safety in the Node.js world + nice structure + a hefty amount of features out of the box.

**Comment by weeco** [comment]
Beside the given advantages I like that it gives me a clear way on how to do things properly :).

**Comment by roeehershko** [comment]
NestJS is architecture framework.
if you like clean and organized code, this one is the best out there
if you look for frameworks that does everything for you like meteor, this one is not for you.
its flexible and gives you the ability to combine all your favorites npm libraries in organized and clean way
the most important thinks for me in a framework, is the ability to bundle small components and reuse them in a future projects and in NestJS i am able to do it easily and clean

**Comment by jpscorp21** [comment]
La curva de aprender nest.js es bastante comoda para las personas que vienen de angular. Tiene una estructura bastante ordenada que te permite pensar más en el desarrollo que en la infraestructura. Junto a typescript que ofrece un plus muy bueno que te da la posibilidad de trabajar lo mejor del paradigma POO y  Funcional

**Comment by jnst** [comment]
### Pros:

- TypeScript-based web framework
  - Strict type definition is possible
    - If you using just JavaScript you need to guarantee this with test code.
  - Useful decorators
- Module-based framework
  - It makes it easier to externalize general-purpose modules
  - It makes it easier to reuse code in multiple projects
- Supported modules sufficient (In my project I needed the following modules)
  - gRPC
  - WebSocket
- You can use familiar web framework technology from Java era
  - DI (The flexibility of the test code increases because you can replace the DI target)
  - AOP (Interceptor etc)

### Cons:

- High learning cost
  - There are several sample codes, but what I really want is a realworld one project with all the features used.
  - I am currently using it in a production environment, but it took me a month to become satisfactory as a learning cost. (It also includes TypeORM)
- Minimum code required is more than other frameworks
  - When looking for another TypeScript-based framework, there is [stix](https://stixjs.io/) which is truly concise, low learning cost, and high productivity.
    - I decided too use Nest.js because gRPC and WebSocket were necessary in my case.
