### ISSUE TITLE
How do I match another package to nestjs?

### ISSUE THREAD

**Issue by webafra** [nestjs/nest#6960]
I am trying to prepare an application package for use in nestjs but I do not know where to start !?

Is this difficult?
Do I need to change all the package codes?
Is it possible to do this with little knowledge?

I want to use the Lucid package inside Nestjs but I have no idea
I tried many times but I always made a mistake.

https://github.com/adonisjs/lucid

please help me.

**Comment by jmcdo29** [comment]
I've answered this before for you. Lucid **requiress** Adonis to be used. Because of how they've written the package, there's nothing we can do. They would need to re-write the package to be used outside of Adonis for it to be consumed elsewhere. Generally, if you can't use the package in regular Node, you won't be able to use it with Nest.
