### ISSUE TITLE
How to use Nest.js & TypeORM with Webpack HMR ?

### ISSUE THREAD

**Issue by Ttou** [nestjs/nest#711]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

```js
if (module['hot']) {
  module['hot'].accept()
  module['hot'].dispose(() => {
    app.close()
  })
}
```

![wx20180518-180518](https://user-images.githubusercontent.com/4298437/40229206-23666c68-5ac6-11e8-808f-c9e21de4dd71.png)

## Environment

<pre><code>
Nest version: 5.0.0
TypeORM version: 0.2.5
MySQL version: 2.15.0

 
For Tooling issues:
- Node version: 8.11.2  
- Platform:  Mac

Others:

</code></pre>

**Comment by unlight** [comment]
There are several issues here:
- When I was creating issue about [Ability to reinitialize components of module](https://github.com/nestjs/nest/issues/442) I hoped for REAL hot swap! But instead we got changed file typescript recompilation, which does not give performance boost at all (with typescript settings `transpileOnly: true`). Application is still fully reinitialized.
- So you must handle this reinitialization in typeorm and close connection:
```ts
import { getConnection } from 'typeorm';

    if (module.hot) {
        const connection = getConnection();
        if (connection.isConnected) {
            await connection.close();
        }
        module.hot.accept();
        module.hot.dispose(() => {
            app.close();
        });
    }
```
See full example [here](https://github.com/unlight/nest-typescript-starter/blob/ad59f3443f347e668f1d6f6c22f78f01bddcfb89/app/server.ts)
- About import entites (same issue with migration), yes glob pattern `*.ts` will not work, but you can import entites explicitly
```ts
import { Cat } from './cat/cat.entity';
import { User } from './user/user.entity';

@Module({
    imports: [
            entities: [
                Cat, User
            ],
        }),
    ],
})
```
Second option could be webpack require.context feature:
```
const entityContext = require.context('.', true, /\.entity\.ts$/);
entityContext.keys().forEach(entityContext);
```
But I did not test it.

Third option is to use `ts-node` instead of node (which will parse ts files as well) but it's major hit to performance and using webpack hmr aproach does not make sense at all)

**Comment by Ttou** [comment]
@unlight you can't close connection like that, it will report an error when doing some database operation.
![wx20180521-105129](https://user-images.githubusercontent.com/4298437/40288271-f0c8a688-5ce4-11e8-8f97-f94d7e589fa1.png)

**Comment by unlight** [comment]
Your errors says "connection is not established", that's why I'm checking flag `connection.isConnected`.
Anyway it works for me.

**Comment by Ttou** [comment]
@unlight your code will close the connection at the application startup

**Comment by kamilmysliwiec** [comment]
In latest `@nestjs/typeorm@3.1.0` the `keepConnectionAlive` option is available. Set it to true in order to reuse the same connection between rebuilds. I'll update the docs soon
