### ISSUE TITLE
No information in stack trace about which dependency can't be resolved

### ISSUE THREAD

**Issue by pumano** [nestjs/nest#713]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

I try to testing e2e using provided example in documentation, ( I have mongoose module also for database integration) but I got error, and can't figure out, where I have mistake due to no detailed information about dependency which can't be resolved.
```
 "before all" hook:
     Error: Nest can't resolve dependencies of the useFactory (?). Please verify whether [0] argument is available in the current context.
      at Injector.lookupComponentInExports (node_modules/@nestjs/core/injector/injector.js:129:19)
```

## Expected behavior

Good to have detailed info in stack trace about which dependency can't be resolved. (Angular provide detailed info about which dependency can't be resolved)

## Environment

<pre><code>
Nest version: 5.0.0

 
For Tooling issues:
- Node version: 10.1  
- Platform:  Mac 

Others:

</code></pre>

**Comment by shekohex** [comment]
Because we can't, If we know which depancy is, it's name or type, so why then we throwing that error 😅?

All we know about that Depancy that it's live at that index `0` as this message says: `Please verify whether [0] argument is available`.

So back to your issue, could you share more code so we could guide you where the error is ?

**Comment by pumano** [comment]
It's simply does not work. And I can't found problem because I don't have too much info about which dependency is not resolved.
**projects.module.ts**:
```
import { Module } from '@nestjs/common';
import { MongooseModule } from '@nestjs/mongoose';

import { ProjectSchema } from './project.schema';
import { ProjectsController } from './projects.controller';
import { ProjectsService } from './projects.service';

@Module({
  imports: [MongooseModule.forFeature([{ name: 'Project', schema: ProjectSchema }])],
  controllers: [ProjectsController],
  providers: [ProjectsService],
})
export class ProjectsModule { }
```
**projects.e2e-spec.ts**: 
```
import * as request from 'supertest';
import { Test } from '@nestjs/testing';
import { ProjectsModule } from './projects.module';

import { INestApplication } from '@nestjs/common';

describe('Projects', () => {
  let app: INestApplication;

  before(async () => {
    const module = await Test.createTestingModule({
      imports: [ProjectsModule]
    })
      .compile();

    app = module.createNestApplication();
    await app.init();
  });

  it(`/GET projects`, () => {
    return request(app.getHttpServer())
      .get('/api/v1/projects')
      .expect(200);
  });

  after(async () => {
    // await app.close();
  });
});
```

**Comment by kamilmysliwiec** [comment]
This issue is actually a combination of two different ones, #709 and invalid argument which is passed inside `lookupComponentInExports` method. Instead of `useFactory` you should see a more descriptive injection token. I'm on both of them now.

Btw, you cannot instantiate your app due to missing `MongooseModule.forRoot()` call. The `MongooseModule.forFeature()` defines providers that depend on the mongo connection (which is missing).

**Comment by pumano** [comment]
@kamilmysliwiec I also try to import Mongoose module for root in my testing module, but it not solve my problem. Same error message.

**Comment by kamilmysliwiec** [comment]
In `v5.0.1` you should receive a more descriptive error. Let me know if you still face any issue
