### ISSUE TITLE
Classes exported under the same name and aliased are confused as the same token by the dependency injection mechanism

### ISSUE THREAD

**Issue by ericmorand** [nestjs/nest#7158]
## Input Code

Consider the following minimal project:

```ts
// provider1.ts
export class Token {};
```

```ts
// provider2.ts
export class Token {};
```

```ts
// main.module.ts
import {Module} from "@nestjs/common";
import {Token as Token1} from "./provider1";
import {Token as Token2} from "./provider2";

@Module({
    providers: [
        Token1,
        Token2,
        {
            provide: 'foo',
            useFactory: (injectedToken1, injectedToken2) => {
                console.warn(Token1 === Token2); // false, expected
                console.warn(injectedToken1 === injectedToken2); // true, unexpected
                console.warn(injectedToken1 instanceof Token2); // true, unexpected
                console.warn(injectedToken2 instanceof Token2); // true, expected
            },
            inject: [
                Token1,
                Token2
            ]
        }
    ]

})
export class MainModule {}
```

Here, `provider1.ts` and `provider2.ts` both export a class under the same name - `Token`. When imported by the module, they are aliased respectively to `Token1` and `Token2`. These aliases are then used as provider keys.

When both tokens are injected into the `foo` provider factory, both arguments of the factory are strictly equals: they are both the same instance of `Token2`. It means that the dependency injection mechanism instanciate a singleton from `Token2` and then assign this singleton to both the tokens `Token1` and `Token2`.

## Expected behavior

`Token1` and `Token2` are different classes. They are different tokens and are not equal, nor loosely, neither strictly.

It is expected that they are not confused by the dependency injection mechanism of Nest.

## Possible Solution

None.

And this is a big issue because there is no way for a developer to control how a class is exported by a module the application depends on. When two different modules export the same class, it becomes impossible to alias them and use these aliases as provider keys.

Note that this also impacts functions used as factory.

## Environment

Nest version: 7.6.17

**Comment by jmcdo29** [comment]
You can use injection tokens to get around this if you need it. It's not common in my experience, to have two classes with the same name. The reason for the "unexpected" behavior is because both `Token1` and `Token2` have the same `.name` property, which is what Nest uses by default to resolve the injection token. So if you really need functionality like this you can do
```ts
{
	provide: 'Token1',
	useClass: Token1,
},
{
	provide: 'Token2',
	useClass: Token2,
}
```
And now with `@Inject('Token1')` you get the `Token1` class, or with `inject: ['Token1', 'Token2']` your above factory should print out the expected outcomes.

**Comment by ericmorand** [comment]
> It's not common in my experience, to have two classes with the same name.

Being not common is not the issue here. It is a perfectly valid syntax and at no point in the documentation of NestJS it is said that we shouldn't rely on class names as token keys. The whole documentation actually implictely recommends the opposite: using class names as injection tokens.

At the very least, it should be explained that using class names is unpredictable and should be avoided. Or the framework should be fixed to _not_ use the name property of a function, but the function itself as injection token.

**Comment by jmcdo29** [comment]
> The whole documentation actually implictely recommends the opposite: using class names as injection tokens.

Right, class names. Not class _alias_ names. Using class names isn't unpredictable. This is behaving like it is expected to. The syntax may be valid in Typescript, aliasing two classes with the same name is fine and all, but when you look at the injection tokens, what Nest is using, it's the class's name. 

I plan on writing an advanced part of the doc that talks about how the decorators work and the DI system (kind of) works to explain this concept better.

This is also something that has been discussed in the past, about using class instances rather than the names as the injection tokens, you can look through our issues to find references to it.

**Comment by kamilmysliwiec** [comment]
This has been fixed in v8 https://github.com/nestjs/nest/pull/6349 (which I'm hoping to release within ~1 month).

**Comment by ericmorand** [comment]
@kamilmysliwiec

> core: use class references as providers/controllers/injectables keys instead of their names

👍 

Amazing, thanks a lot!
