### ISSUE TITLE
Marble.js as middleware server for Nest.js

### ISSUE THREAD

**Issue by okhomenko** [nestjs/nest#728]
## I'm submitting a...
<pre><code>
[ x] Feature request
</code></pre>

## What is the motivation / use case for changing the behavior?
There is this new node.js framework, that I heard a lot of buzz recently, Marble.js. It's based on observables.

Does it make sense to use it as middleware server for Nest.js? Decided to create feature request, may be there is interest.

**Comment by kamilmysliwiec** [comment]
Hi @okhomenko,
Marble wraps native HTTP server with the RxJS, giving a pretty straightforward way to treat incoming requests like streams, in a very reactive manner. It won't bring any value to Nest though since we completely encapsulate server behind provided architecture's building blocks. What sits underneath doesn't matter 🙂
