### ISSUE TITLE
Global subdomain OR prefix

### ISSUE THREAD

**Issue by dariusj18** [nestjs/nest#7321]
## Is your feature request related to a problem? Please describe.

If I have an api with an endpoint of `mydomain.tld/api` I also want to be able to access it via `api.mydomain.tld`.  In an express app it is easy enough to use the [express-subdomain](https://www.npmjs.com/package/express-subdomain) package and include the routes like 

```
routes = express.Router();

routes.use('endpoint', doStuff);

app.use(subdomain('api', routes));
app.use('/api', routes);
```

But I don't see anywhere in the docs that I could extend the controller registration process to include my own logic.

## Describe the solution you'd like

Some method to extend the controller registration process, to register additional handlers.

**Comment by Tony133** [comment]
Hi @dariusj18, If I understand correctly, would you like to put a global prefix on the endpoints? or would you like a subdomain for the endpoints?

**Comment by dariusj18** [comment]
I want to be able to have all routes on either, but not both.

**Comment by jmcdo29** [comment]
What's the use case of having the API available from the `/api` endpoint and the `api.` subdomain? What does it solve? Seems like you're just opening up to more entrypoints to the server (possible attack vectors) and more maintenance

**Comment by dariusj18** [comment]
Legacy migration.

**Comment by kamilmysliwiec** [comment]
> I want to be able to have all routes on either, but not both.

Wouldn't it be easier to set up a reverse proxy (nginx?) in front of your API which redirects `api.` to `/api` or the other way round?

To answer your question, currently, you can only register a subdomain per-controller (https://docs.nestjs.com/controllers#sub-domain-routing) and the globally registered prefix would apply here as well (unless you explicitly exclude each endpoint that is supposed to be accessible from the subdomain). In v8 (which is supposed to be released in a few days), you should be able to use `RouterModule` to register a prefix per module instead of globally for each route. With that, you could technically split each module into 2 modules in which one registers endpoints without the subdomain (but with the `api` prefix), and another one these endpoints that need `/api`.

Still, even though it's technically doable (definitely easier with v8), I'd rather recommend using a proxy in front.

For further questions, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support).
