### ISSUE TITLE
High Priority module function init

### ISSUE THREAD

**Issue by pragmaticivan** [nestjs/nest#7376]
## Is your feature request related to a problem? Please describe.
I'm looking for a way to have a high priority specialized method in a module that can be called on Injection resolution time.

If possible, even before any library (Ex: express/http) is loaded.

## What is the motivation / use case for changing the behavior?
Trying to call instrumentation clients before libs are loaded from core.
ex: https://github.com/open-telemetry/opentelemetry-js/blob/main/getting-started/traced-example/package.json#L7
`node -r ./tracing.js app.js`

**Comment by pragmaticivan** [comment]
This issue is related to this repo: https://github.com/pragmaticivan/nestjs-otel

Currently trying to fix that issue https://github.com/pragmaticivan/nestjs-otel/issues/42

**Comment by kamilmysliwiec** [comment]
> that can be called on Injection resolution time. If possible, even before any library (Ex: express/http) is loaded.

Could you provide an example (loading/registration flow)? If you want to execute some function before any library is loaded, I'm guessing it must happen even before the `main.ts` file is processed?

**Comment by pragmaticivan** [comment]
Yeah, I'm investigating with opentelemetry team if theere's a way to instrument after stuff care configured.

So far I had this POC: https://github.com/pragmaticivan/express-multer-otel-bug

Someone created a repo to reproduce the issue https://github.com/benitezho/nestjs-otel/tree/main/src

My only fallback right now is to degrade DX on that lib and ask users to configure opentelemetry SDK before application setup.

**Comment by kamilmysliwiec** [comment]
In this case, I'm not sure if there's anything we could do at the framework level to help cover your use-case(?). This issue seems to be unrelated to NestJS itself since adding any additional lifecycle hooks won't help here (you want to configure/load stuff even before the NestJS application instance is created), correct me if I'm wrong @pragmaticivan

**Comment by pragmaticivan** [comment]
It makes sense.
Although I was looking for something like in Rails initializers.
They are config patterns where you can set up anything before any layer other than the common framework is loaded.

**Comment by kamilmysliwiec** [comment]
@pragmaticivan at the end of the day, Nest is just a regular Node.js app (`nest start` simply uses `node` bin to spawn the app). In this case, we might not be able to build any pre-start hooks into the framework itself (even if we decided to wrap `node` bin with our custom executable binary, I suppose we'd just reinvent the wheel since `node` already exposes the `--require` flag)

**Comment by pragmaticivan** [comment]
Yeah, we can close that one. I was just looking for a way to enforce priority on Dependency Injection, the current implementation is working just fine. But for some reason when `@UseInterceptors(FileInterceptor('field'))` is used somewhere, all the instrumentation gets messed up.

**Comment by kamilmysliwiec** [comment]
@pragmaticivan I'm guessing the reason might be the `multer` dependency in this case(?)

**Comment by pragmaticivan** [comment]
@kamilmysliwiec I thought the same but the person who reported the ticket was able to work around by just using a middleware with multer, so it has to do with the FileInterceptor for sure.
