### ISSUE TITLE
Allow deprecated Logger constructor?

### ISSUE THREAD

**Issue by anchan828** [nestjs/nest#7478]
## Feature Request

When many libraries create a Logger instance, they often set a boolean as the second argument.
When I was upgrading my library to v8, most of the errors were due to the change from boolean to `{timestamp?: boolean}` objects. (e.g. @nestjs/terminus has same issue: https://github.com/nestjs/terminus/runs/3018356373?check_suite_focus=true#step:4:62)

Is it possible to deprecate boolean type and allow its use in v8?

## Is your feature request related to a problem? Please describe.

```typescript
// ~v7: ok
// v8: error
const logger = new Logger("Logger", true);
```

## Describe the solution you'd like

I think Logger class can remove the boolean type in v9.

```typescript
// ~v7: ok
// v8: ok (however, add @deprecated tag)
// v9: error?
const logger = new Logger("Logger", true);
```

## What is the motivation / use case for changing the behavior?

Maintain backward compatibility.

**Comment by anchan828** [comment]
Created PR #7480

**Comment by kamilmysliwiec** [comment]
As our goal is to avoid introducing any breaking changes whatsoever, this one was the first public API change since +1 year. Since it's fairly simple and to migrate you could literally use the "Find->Replace" tool, I don't think there's a reason to first flag it as deprecated and then remove it in the next release, given that we'd have to push this back till next major version.
