### ISSUE TITLE
Add a warning when you import a module but you don't use any exported provider.

### ISSUE THREAD

**Issue by Sikora00** [nestjs/nest#7579]
## What is the motivation / use case for changing the behavior?

I'm facing situations when I have to implement one-time actions, like an endpoint for migration. After that I want to remove this functionality. It is easy to remove related service and all its dependencies as IDE mark them as unused, but it is harder to find if modules are still needed to be imported. There could be a waring at an application start  that tells you that you have unused imports.

I see also problems: 

- what if we don't need providers from imported modules but we wanted some actions on those modules init.
- what about controllers, resolvers, event listeners in those modules.

So this feature is just to consideration.

**Comment by jmcdo29** [comment]
This sounds like one of those features that may be cool, but also incredibly difficult to implement. Unless something has changed with how the injectable resolution works, and I don't think it has to this extent, Nest doesn't really look at the modules and scan for the dependencies of the modules in the imports to see if that module is used, but rather it it looks at the providers, figures out what needs to be injected, and scans up(the module's providers, the module's imports' exports, and global providers).

In theory, it might be possible to add a flag to each module to say "yeah, this has been used", but it might be better to delegate this out to a devTool that would allow it to be ran from a CLI or similar context to get a report on what the dependency tree looks like, what imports aren't being used, etc.

**Comment by kamilmysliwiec** [comment]
Technically, importing a module that does not export any provider is perfectly fine given that quite frequently modules are self-sufficient. For instance, think about a module that registers multiple queue consumers OR schedules CRON jobs. Such a module would likely not have any exports. Likewise, often you may have modules in which providers perform some "per-bootstrap" one-time job (for instance, triggered by lifecycle hooks), like seeding the database. Lastly, you can have modules that expose several endpoints to interact with a specific table(s) but since there are no relations (SQL relations), you may not export anything and just encapsulate the business logic within that modules.

Thanks for the suggestion though!

**Comment by tmtron** [comment]
Such a feature would definitely be helpful. After refactoring a large app it can easily happen that we removed the services, but forgot to remove the module import.  
It would totally be okay to get a list that then needs to be checked for exceptions: i.e. for the cases that @kamilmysliwiec listed above.

**Comment by micalevisk** [comment]
@tmtron To me, this should be a third-party tool.

Maybe we could use [`nestjs-spelunker`](https://github.com/jmcdo29/nestjs-spelunker) for that.
