### ISSUE TITLE
Injecting dependencies from the consumer module in my dynamic module fails.

### ISSUE THREAD

**Issue by Adarah** [nestjs/nest#7583]
## Current behavior
Trying to inject dependencies from the consumer in my library module fails.
```
Error: Nest can't resolve dependencies of the CustomGuard (LIB_MODULE_OPTIONS, ?). Please make sure that the argument Reflector at index [1] is available in the LibModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current LibModule?
- If Reflector is exported from a separate @Module, is that module imported within LibModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })
```

## Input Code
This is the minimal reproducible code I could muster.
https://github.com/Adarah/nestjs-repro-repository/tree/main/app

Running `npm run start:dev` in the `app` directory results in the error above.

## Expected behavior
I should be able to use dependencies from the consuming module such as Reflector so I can utilize the metadata for my library. 

## Environment

<pre><code>
Nest version: 8.0.0
 
For Tooling issues:
- Node version: 16.4.0
- Platform:  Linux
</code></pre>

**Comment by micalevisk** [comment]
This bug was introduced in Nest `8.0.0`, I just tested it out.

**Comment by jmcdo29** [comment]
This is due to how Nest's module resolution changed in v8. Now we use stringified versions of classes instead of the class's name string. The implication of this, however, is that it's even more important now that libraries properly mention nest packages as peer dependencies to ensure that one one version of nest ends up getting installed

**Comment by kamilmysliwiec** [comment]
In v8, Nest uses class references as injectable keys (not their class names). To address this issue, follow @jmcdo29 suggestion

> The implication of this, however, is that it's even more important now that libraries properly mention nest packages as peer dependencies to ensure that one one version of nest ends up getting installed

**Comment by Adarah** [comment]
@kamilmysliwiec @jmcdo29 As I understand it, simply moving my Nest `dependencies` in my library to `peerDependencies` should fix the errors, right? I modified the repo with those changes, but the Reflector issue still persists. Could the issue be reopened?

**Comment by micalevisk** [comment]
@Adarah use `constructor(@Inject(Reflector.name) private readonly reflector: Reflector) {}` to fix that

**Comment by kamilmysliwiec** [comment]
Just FYI, using `Reflector.name` can fix this issue for the time being but it may pop up again in the future. You shouldn't use `@Inject(Reflector.name)` even though it works with the current version.

**Comment by Adarah** [comment]
Then what is the most recommended way to fix this problem?

**Comment by kamilmysliwiec** [comment]
Each library/application should use the same copy of `@nestjs/core` and `@nestjs/common` packages (that's why they should be flagged as peer dependencies, not dependencies). 

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
