### ISSUE TITLE
Does NestJS support versioning for GQL ?

### ISSUE THREAD

**Issue by dtuyenle** [nestjs/nest#7647]
Does NestJS support versioning for GQL ?

**Comment by smolinari** [comment]
@dtuyenle - The team usually want just issues or suggestions here in the repo. If you'd like, please ask your question here:

https://discord.gg/nAmbw2Tw

in the `#nestjs-graphql` channel. 

The answer to your question is yes, but it's not because Nest supports versioning directly per se. Versioning GraphQL APIs isn't really a thing (or rather, it shouldn't be), not like with REST. It's more about building flexible APIs without breaking changes. I'll explain better on Discord, if you ask the question there. 

Scott
