### ISSUE TITLE
Nest 8 INestMicroservice.listen not return promise. 

### ISSUE THREAD

**Issue by rhdtl78** [nestjs/nest#7656]
## Describe the regression

INestMicroservice.listen has no arguments, and return promise, But CustomTransportStrategy.listen is still receive callback, and return any.
So webpack compile failed.

## Input Code

```ts
// my-server-strategy.ts
export class MyServerStrategy extends ServerTCP implements CustomTransportStrategy {}

// main.ts
async function bootstrap() {
	const app = await NestFactory.createMicroservice<MicroserviceOptions>(MyNestAppModule, {
		strategy: new MyServerStrategy({
			host: '0.0.0.0',
			port: 3000,
			retryAttempts: 5,
		}),
	});
	/**
	 * this will throw an error below
	 * TS2554: Expected 1 arguments, but got 0.
	 * app.listen().then(() => {
	 *     ^^^^^^^^
	 * TS2339: Property 'then' does not exist on type 'void'.
	 * app.listen().then(() => {
	 *              ^^^^
	 */
	app.listen().then(() => {
		console.log(`microservice is listening`);
	});
}

bootstrap();
```

## Expected behavior/code

it should be return promise like guide. Above code should run properly.

## Environment
<pre><code>
Nest version: 7.5.1 -> 8.0.0

For Tooling issues:
- Node version: 16.4.2
- Platform:  mac OS 11.5

Others:

IDE: IntelliJ IDEA 2021.1.3 Ultimate
package manager: yarn 1.22.0
nest
 -  @nestjs/cli@8.0.0
  -  @nestjs/schematics@^8.0.0
 - @nestjs/common@8.0.0
 - @nestjs/core@8.0.0
 - @nestjs/microservices@8.0.0
 - @nestjs/schematics@8.0.0
 - @nestjs/testing@8.0.0

</code></pre>

**Comment by kamilmysliwiec** [comment]
I wasn't able to reproduce your issue locally.
Please provide a minimum reproduction repository.

**Comment by rhdtl78** [comment]
> I wasn't able to reproduce your issue locally.
> Please provide a minimum reproduction repository.

when create nest project newly, I wasn't able to reproduce either.
I will try to re-install with delete lock file, node_module directory.

**Comment by rhdtl78** [comment]
I can reproduce the error inside of docker container which use NodeJS image tagged as lts.

I change my Dockerfile from 
```Dockerfile
FROM node:lts
```
to 
```Dockerfile
FROM node:16.4.2
```

And no errors throws.

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by rhdtl78** [comment]
sorry...  I can't  provide reproduction.  Owner doesn't want open it.
and clean project has no issue like this. 

you can close this issue. 

thanks for your struggles.

**Comment by ccoeurderoy** [comment]
Hi guys,

I may be wrong, but it looks like there is a little issue in the `CustomTransportStrategy` interface: the `listen` method expects a callback parameter

https://github.com/nestjs/nest/blob/6dbcfb1471575c02d6f2c21869c8263f61427d5f/packages/microservices/interfaces/custom-transport-strategy.interface.ts#L5

Now, with Nest v8, the `INestMicroservice` does not have a callback parameter anymore:

https://github.com/nestjs/nest/blob/6dbcfb1471575c02d6f2c21869c8263f61427d5f/packages/common/interfaces/nest-microservice.interface.ts#L19

Therefore, we cannot call the `listen` method with a callback.

I have created a custom transport for Google PubSub and I cannot upgrade Nest version ([PR link](https://github.com/algoan/nestjs-components/pull/254)) because of these definitions.

```bash
test/GooglePubSubServer.test.ts:40:16 - error TS2554: Expected 0 arguments, but got 1.

 40     app.listen(async () => {
                   ~~~~~~~~~~~~~
 41       expect(server.gcClient.subscriptions.get(SUBSCRIPTION_NAME)).toBeDefined();
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 45       done();
    ~~~~~~~~~~~~~
 46     });
    ~~~~~
```

Is that related to your issue @rhdtl78?

**Comment by ccoeurderoy** [comment]
After digging in the nest-microservice package, I found this:

https://github.com/nestjs/nest/blob/7e641179049c3e761d10d4466eeb4a577ae80358/packages/microservices/nest-microservice.ts#L125-L136

Meaning that the callback method is still called.

Unfortunately, the release note did not mention this breaking change: we cannot have a callback method anymore. It just says that the `listenAsync` method is deprecated.

In my opinion, the `callback` signature is not correct. Indeed, the `listenAsync` method in Nest v7 was returning:

```ts
    return new Promise<void>(resolve => this.server.listen(resolve));
```

I think that the correct signature for `CustomTransportStrategy` listen method could be:

```ts
listen(callback: (error?: Error, info?: unknown) => any): any; 
```

Because of the condition defined in the 129th line:


https://github.com/nestjs/nest/blob/7e641179049c3e761d10d4466eeb4a577ae80358/packages/microservices/nest-microservice.ts#L130-L132

Finally, I had to change my custom transport server `listen` method to accept this new callback method (which can be found in that [pull request](https://github.com/algoan/nestjs-components/pull/254/files#diff-e114c1030e4de14ddec6cf09ae31ba8b2f1dc131b33d4a5036c9d722d121bd3bR62-R68))

**Comment by yoshigev** [comment]
@kamilmysliwiec, have you seen the comments of @ccoeurderoy?

Is there a plan to change the signature of `listen()` of `CustomTransportStrategy`?

BTW, if anyone is interested, the easy way of transforming an async function to callback-oriented style, is using `util.callbackify` method.

Thanks.
