### ISSUE TITLE
@UploadedFile() decorator failing validation if file is not uploaded - need a way to make file upload optional

### ISSUE THREAD

**Issue by naamapps** [nestjs/nest#7721]
## Feature Request
When using the `@UploadedFile()` decorator, it makes the file required for the request and fails validation when not uploading.
We need a way to make the file optional.

## Is your feature request related to a problem? Please describe.
Yes, the problem is stated above.
This is the error when not uploading:
```
{
    "statusCode": 400,
    "message": "Validation failed",
    "error": "Bad Request"
}
```
## Describe the solution you'd like
Maybe pass a bool property to the decorator if it is required or optional?
```
@UploadedFile(true) // required
@UploadedFile(false) // optional
```

## What is the motivation / use case for changing the behavior?
It is good to have an optional file uploading like when updating a user - sometimes the user updates the profile image but sometimes he only updates another field without changing the image.

**Comment by naamapps** [comment]
Sorry for the misunderstanding, it was a problem with one of my global pipes.
The file upload is not mandatory by default.

**Comment by Rapol** [comment]
For future reference, I had the same issue (Error: Multipart: Boundary not found). Multer was throwing an error even when there wasn't any form-data in the request. The problem was the request setting content-type header with multipart/form-data even if there wasnt any data. If that is set, it will try to parse the boundary in the headers.
