### ISSUE TITLE
Cannot create composite primary keys with sequelize 

### ISSUE THREAD

**Issue by medhavi98** [nestjs/nest#7925]
## Bug Report
I have created a nest JS project with sequelize and we have some tables with two primary keys.(composite primary keys). In node JS and sequelize, they have feature to define two primary keys in database model. If I tried with same approach with nestJS, it appears to be identify only first column as primary key. 

## Current behavior

 parent: Error: Duplicate entry '1111346-' for key 'table_name.PRIMARY'

## Input Code
```
@Column
property_id: number;
allowNull: false;
primaryKey:true

@Column
key_id: string;
primaryKey:true

## Expected behavior
Identify both columns as Primary Keys

Nest version: 7.1.3

**Comment by jmcdo29** [comment]
Nest's sequelize package doesn't change any of sequelize's functionality, it just adds a wrapper to create the injection tokens necessary for the dependency injection. 

If you believe this _is_ a problem with Nest, please provide a [minimum reproduction repository](http://minimum-reproduction.wtf). Otherwise, please report this to Sequelize.

Make sure you're also on the latest Nest version. I see you have 7.1.3 in your report, whereas Nest common is on 8.0.6

**Comment by kamilmysliwiec** [comment]
> Nest's sequelize package doesn't change any of sequelize's functionality, it just adds a wrapper to create the injection tokens necessary for the dependency injection.

this ☝️
