### ISSUE TITLE
Injection of HttpAdapterHost behaves differently in a testing module vs application

### ISSUE THREAD

**Issue by Papooch** [nestjs/nest#8076]
## Bug Report
`httpAdapter` inside `HttpAdapterHost` is undefined when injected into a provider factory in a testing module.

## Current behavior
`httpAdapter` inside `HttpAdapterHost` is undefined when injected into a provider factory *in a testing module* using `Test.createTestingModule()`. The same works fine in an app created using `NestFactory.create()`.

This makes the app using the code below untestable. 

## Input Code

```ts
import { Module } from '@nestjs/common';
import { HttpAdapterHost, NestFactory } from '@nestjs/core';
import { Test } from '@nestjs/testing';

@Module({
    providers: [
        {
            provide: 'Test',
            inject: [HttpAdapterHost],
            useFactory: (adapterHost: HttpAdapterHost) => {
                // logs true in app, logs false in testApp
                console.log(!!adapterHost.httpAdapter);
                return 'Test';
            },
        },
    ],
})
class AppModule {}

async function bootstrap() {
    const app = await NestFactory.create(AppModule, { logger: false });
    await app.listen(3000);

    const testFixture = await Test.createTestingModule({
        imports: [AppModule],
    }).compile();
    const testApp = testFixture.createNestApplication();
    await testApp.init();
}
bootstrap();
```
Output
```
true
false
```

## Expected behavior
I would expect the code to work identically in app and test.

## Environment
<pre><code>
 "@nestjs/common": "8.0.6",
 "@nestjs/core": "8.0.6",
 "@nestjs/testing": "8.0.6",
</code></pre>

**Comment by micalevisk** [comment]
[Here's the minimum reproduction repo](https://gitlab.com/micalevisk/nest-issue-8076).

**Comment by micalevisk** [comment]
Perhaps we shouldn't invoke `testingModule.init()` (for this kind of test) but rather

```js
const moduleFixture = await Test.createTestingModule({
    imports: [AppModule],
}).compile()
const testApp = moduleFixture.createNestApplication()
await testApp.init()
```

because the `createNestApplication` method is the one responsible for load the http adapter

https://github.com/nestjs/nest/blob/5974b6fed12dfe3d0846cb48dcf2cb449bde2557/packages/testing/testing-module.ts#L31-L35

---

This looks like something related to providers resolution because when calling `testApp.init()` the default `HttAdapterHost` is done. As you could see [here](https://gitlab.com/micalevisk/nest-issue-8076) using this code:

```ts
class AppModule implements OnModuleInit {
  constructor(private readonly adapterHost: HttpAdapterHost) {}
  onModuleInit(): void {
    console.info({
      context: 'onModuleInit',
      'Has `httpAdapterHost.httpAdapter`?': !!this.adapterHost.httpAdapter,
    });
  }
}
```

**Comment by Papooch** [comment]
> Perhaps we shouldn't invoke testingModule.init() (for this kind of test) but rather

You are right, the code in the OP was wrong and I wouldn't expect it to work. (I fixed it now)

But as you can see from the repro, if you change the init code, the HttpAdapterHost is still empty in the "Test" provider. I guess it makes sense because the providers are resolved before the init() phase (right?), but I think this is still a bug because if anyone used this technique, their app would work but it would break in tests...

In my use case I can work around that by injecting the HttpAdapterHost into the module, so I guess it would be enought to add a warning to the docs that HttpAdapterHost shouldn't be injected in providers.

**Comment by micalevisk** [comment]
> I guess it makes sense because the providers are resolved before the init() phase (right?), but I think this is still a bug because if anyone used this technique, their app would work but it would break in tests...

I'm with you.  
If it works with `NestFactory.create()` I expect it to work with `moduleFixture.createNestApplication()` as well

**Comment by kamilmysliwiec** [comment]
There's nothing we can do on our side to fix this issue (it's the limitation of the current API).

```typescript
const moduleFixture = await Test.createTestingModule({
    imports: [AppModule],
}).compile()
```

This ^ initializes the DI tree & container -> resolves all providers. That means `adapterHost.httpAdapter` will be undefined at that time.

Calling `testFixture.createNestApplication();` later on is already too late (modules graph has been already constructed). If your need `httpAdapter` to be available within your tests, you must use `NestFactory.create()` directly (using this method in your tests is acceptable - not against best practices) instead of the `Test.createTestingModule`.
