### ISSUE TITLE
Using instanceof blocks possibility of extending default types in separate packages

### ISSUE THREAD

**Issue by lukeromanowicz** [nestjs/nest#8164]
## Current behavior
We are not able to extend types, that are used in source code in conjunction with `instanceof`, and keep it in a separate package. It's useful when having multiple services that share some of the code (which could be exported to a common package). In the given example, the prototype of a class from a 'common' package will be defined in a different node_modules, so `instanceof` will always be false.

![image](https://user-images.githubusercontent.com/46789227/135114124-a3413140-eb21-4eb3-904e-e85a548bc7e2.png)

## Input Code

```ts
// @company/common
export class ExtendedRpcException extends RpcException {
  constructor(data: ErrorWithAdditionalDetails) {
    const metadata = new Metadata();
    metadata.set('details', JSON.stringify(data));

    super({
      message: data.message,
      code: status.INTERNAL,
      metadata,
    });
  }
}

```

https://github.com/nestjs/nest/blob/9d0551ff25c5085703bcebfa7ff3b6952869e794/packages/microservices/exceptions/base-rpc-exception-filter.ts#L15
This `instanceof` will always be false because `RpcException` I am extending in _@company/common_ is in a different node_modules than the code where I intend to use it.

## Expected behavior
I can freely extend built-in types and store/use them wherever I want.

## Possible Solution
Ducktyping?

## Environment

Irrelevant to the issue

**Comment by jmcdo29** [comment]
In the `@company/company` package, are you using the `@nestjs/*` packages as `peerDependencies`? This is something down at the Typescript level that if you have two instances of the same package, the `ClassAFromPackagev1 instanceof ClassAFromPackagev2` check will return `false` even though it's technically the same class. The same happens when a package uses `dependencies` instead of `peerDependencies` because the dep package is installed then twice
