### ISSUE TITLE
Update from @nestjs/platform-express 8.0.10 to 8.0.11 has breaking change

### ISSUE THREAD

**Issue by nicod-pc** [nestjs/nest#8254]
### Did you read the migration guide?

- [ ] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### NestJS version

8.0.10 -> 8.0.11

### Describe the regression

Yesterday this commit causes an Errors in the code of lib users: https://github.com/nestjs/nest/commit/14fc5de6cf52042c82b85fcd27138bfc42730c73#diff-0f9d4c88c1f368780a6f8402b499bd55c191fbbb46435b3d087c6cad9d55b9ca

The Problem with that is, that now in the middleware instead of the `use` method the `post` or `get` or `patch` or ... Method is called. That breaks custom Middleware classes, like the `IamApiGatewayHeaderMiddleware` I have given in the code section.

### Input code

```ts
export class IamApiGatewayHeaderMiddleware implements NestMiddleware {
  use(
    req: Request & { apiGateway?: { event: APIGatewayProxyEventBase<AuthorizerContextData> } },
    res: Response,
    next: () => void
  ): any {
   // do something
    next();
  }
}
```

### Expected behavior

This breaking changes only happen with mayor releases like 8.x to 9.x.

**Comment by iwt-nduesing** [comment]
Another example is the LoggerMiddleware that also just has a use method: https://docs.nestjs.com/middleware

**Comment by kamilmysliwiec** [comment]
This commit https://github.com/nestjs/nest/commit/14fc5de6cf52042c82b85fcd27138bfc42730c73#diff-0f9d4c88c1f368780a6f8402b499bd55c191fbbb46435b3d087c6cad9d55b9ca reverts a breaking change introduced in 8.0.5. 

In v7 and v8 till 8.0.5, we used `get`, `post`, etc. methods instead of `use` and we reverted back to this behavior in 8.0.11 (to avoid introducing a breaking change without bumping to a new major release). 

This change does not break custom middleware classes. `NestMiddleware#use` != `router.use` (there's no relation between these two methods)
