### ISSUE TITLE
Ability to put app in Maintenance Mode ?

### ISSUE THREAD

**Issue by rakeshlanjewar** [nestjs/nest#8258]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Sometimes we need to put the application in maintenance mode if there is any bug or prevent users from accessing the website.

I find this feature very useful. And can add some magic to the nest.

I am aware that it will make the application a little bit slower due to some extra work. Or we can find an alternate solution like database.

### Describe the solution you'd like

A similar feature has been implemented in Laravel with the help of CLI.

### Teachability, documentation, adoption, migration strategy

For more information:-

[https://laravel.com/docs/8.x/configuration#maintenance-mode](https://laravel.com/docs/8.x/configuration#maintenance-mode)

[https://blog.devgenius.io/laravel-maintenance-mode-a2875028977d](https://blog.devgenius.io/laravel-maintenance-mode-a2875028977d)

### What is the motivation / use case for changing the behavior?

.

**Comment by micalevisk** [comment]
@rakeshlanjewar I'm not familiar with Lavavel. Can you please elaborate how the interface of this feature could be? Maybe this can be developed by the community

**Comment by rakeshlanjewar** [comment]
1.  We will have to add a command to nestjs CLI (Optional)

`down [app]                           Take application down`

2. The above command will add a file named `down` to `dist/[app]`. (Optional user can add a down file manually in the dist directory)
3. One interceptor will be there and it will check if the file exists in the current directory then it will show the app is in maintenance mode.
4. We will activate/ register the interceptor by calling.
`app.enableMaintainanceMode();`


This similar approach is implemented here, [https://blog.devgenius.io/laravel-maintenance-mode-a2875028977d](https://blog.devgenius.io/laravel-maintenance-mode-a2875028977d)


`May the NestJS be with you`

**Comment by jmcdo29** [comment]
Something that makes this difficult, is that Nest's CLI is mostly a code gen tool along with an auto recompile/restart tool. It's not actually used to run the server in production mode. All you need there is `node dist/main` and it's started. Nest actually suggests you _don't_ use the `nest start` outside of development, because it's an unneeded dependency and it adds extra size to your final deployment, that's why it's a devDependency to begin with.

I think that a `MaintenanceInterceptor` sounds like an interesting idea, and it could absolutely be implemented as a third party package that gets conditionally added to the server via an environment config, but I don't think I see the need for Nest to implement this, and certainly don't see it being easily feasible in the Nest CLI. 

I'll let @kamilmysliwiec have the final say here, but my vote is that the interceptor be made into a third party package and documented on how to conditionally bind it

**Comment by kamilmysliwiec** [comment]
> I think that a MaintenanceInterceptor sounds like an interesting idea, and it could absolutely be implemented as a third party package that gets conditionally added to the server via an environment config, but I don't think I see the need for Nest to implement this, and certainly don't see it being easily feasible in the Nest CLI.

Agree with everything Jay wrote above.
