### ISSUE TITLE
"EADDRINUSE :::#port" while saving

### ISSUE THREAD

**Issue by aleskozina** [nestjs/nest#826]
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

`npm run start:dev` starts as expected the watcher and compiles the changes. After a while (i assume, if you save to frequently in short time) the watcher (nodemon) raises the error `EADDRINUSE`. After restarting the server, the error persists. I have to change the port in the main file.

## Expected behavior
Well, the watcher should not throw this error :-)

## Minimal reproduction of the problem with instructions
* run `npm run start:dev`
* make changes
* save
* server restarts

do two saves quickly and you should get the error.

## What is the motivation / use case for changing the behavior?
Proper testing environment

## Environment
<pre><code>
Nest version: 5.0.1
 
For Tooling issues:
- Node version: 8.11.3 (LTS)
- Platform:  OSX: 10.13.5

</code></pre>

**Comment by kapv89** [comment]
I have also faced this bug. However, I'd suggest that instead of changing the port each time you face EADDRINUSE error, you should kill the process that is currently binding to the old port. Because if you don't do so, you'd be left with a zombie nestjs process for each time you change the port, which is never a good thing to have.

On Ubuntu, I'd do the following:
- `lsof -i tcp:3000` -- this gives you the process id listening
- `kill -9 <processId>`

Since OSX is also a "nix", the above commands should work on it too.

**Comment by unlight** [comment]
What repository are you using?
What is watch program under the hood: nodemon, nodedev, webpack?

**Comment by aleskozina** [comment]
@kapv89 I have figured this out by myself, too. It was too annoying to change the port in the rest-client, too.

@unlight 
#1 What exactly too you mean? Im using the latest nest project as base (created via nest-cli). No special configs. 
#2 Well, i think its nodemon but this configuration also comes from nest. If you are interested in config files, i assume you can just hook into the nest repository. Hopefully this answers your question.

kr
Ales

**Comment by kamilmysliwiec** [comment]
I don't this is related to the Nest package. Consider reporting this issue in the appropriate repository (nodemon?)

**Comment by zverbeta** [comment]
[https://github.com/remy/nodemon/issues/1435#issuecomment-441975473](url)
