### ISSUE TITLE
[Microservices] Event handlers called multiple times depending of modules configuration

### ISSUE THREAD

**Issue by dariomncs** [nestjs/nest#8314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In next@7 the event handler was registered and called once. But upgrading to next@8 is called several times depending of the modules configuration.

I guess is related with the new feature of handling multiple events handlers https://github.com/nestjs/nest/commit/b711019660b0245544c8173a8940a93b4a280e38 and sometimes on complex setups, iterating over the modules calls the addHandler multiple times chaining the same logic.

### Minimum reproduction code

https://gist.github.com/dario1985/f364a0cfda0ea771dc15a4fe3b395626

### Steps to reproduce

I attached a test case with an example. I could not reproduce the exact scenario as in our app we have much more modules and some of them are dynamic.

### Expected behavior

The `hello` handler should be called just one.

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.0.11

### Packages versions

"@nestjs/common": "^8.0.11",
"@nestjs/core": "^8.0.11",
"@nestjs/microservices": "^8.0.11",

### Node.js version

15

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by dario1985** [comment]
In my specific case, the controller with the `@EventPattern` decorator, is present only in one module. 
But this module is imported in several others, and the handler is called 3 times.

I'm trying to figure out if is a problem of the scan or some edge case with the module imports, but when the listeners are registered, iterating over the modules in `MicroservicesModule.setupListeners`, the same module appears several time with different refs, and so the controller function is registred multiple times.

As workaround I reverted the `addHandler` to the previous implementation (just set without chaining multiple handlers).

**Comment by dario1985** [comment]
Thank you for the clarification about dynamic modules, now is much more clear!

Even is an expected behavior is a bit strange IMO, as when I use decorators over a controller method (and so I'm not _imperatively_ using the `addHandler`) I intend to bind a specific pattern to a function in this controller. 
So if you define `Controller1.handler1` and `Controller2.handler2` you expect to run once each of them.

**Comment by kamilmysliwiec** [comment]
The code snippet you provided is a perfect example of what's currently wrong with your modules. `forRoot()` and `forFeature()` returns two different modules and the fact that they use the same "host module" (`FooModule` class) doesn't change anything. This is the expected behavior.

As mentioned above, please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
