### ISSUE TITLE
Not every query parameter is a string.

### ISSUE THREAD

**Issue by rizchaerul** [nestjs/nest#8433]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When i make a request with multiple query paramters that have the same name, for example:

localhost:3000/test?q=test1&q=test2&q=test3
![image](https://user-images.githubusercontent.com/72289631/138683292-7bb692b5-fdea-4c08-be4e-53add2fb8e0b.png)

The type of test variable isn't a string. Even though in the docs it says that 

"note that ParseStringPipe is not needed because, as mentioned earlier, every path parameter and query parameter comes over the network as a string by default" (https://docs.nestjs.com/techniques/validation#explicit-conversion)

### Minimum reproduction code

https://github.com/rizchaerul/bug

### Steps to reproduce

1. yarn install (don't use pnpm, it'll cause error in this project)
2. yarn start:dev
3. GET request  to localhost:3000?q=test1&q=test2

### Expected behavior

I expected every query parameters type to be a string. Just like the docs says in https://docs.nestjs.com/techniques/validation#explicit-conversion

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.1

### Packages versions

"@nestjs/common": "^8.1.1",
"@nestjs/config": "^1.0.2",
"@nestjs/core": "^8.1.1",
"@nestjs/jwt": "^8.0.0",
"@nestjs/passport": "^8.0.1",
"@nestjs/platform-fastify": "^8.1.1",

### Node.js version

14.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by GauBen** [comment]
Hey there, this issue is more important than it seems, nest apps are vulnerable to type confusion:

```ts
@Controller()
export class AppController {
  @Get('/test')
  getHome(@Query('param') param = '') {
    if (param.length < 2) return 'At least 2 chars'
    console.log(param[0], param[1])
  }
}
```

- `?param=Hello` prints `H e`, that's ok
- `?param[0]=Hello&param[1]=World` prints `Hello World`, not a big deal, same types
- `?param[0][0]=Hello&param[0][1]=World&param[1][0]=2D&param[1][1]=Array` prints `[ 'Hello', 'World' ] [ '2D', 'Array' ]`, that's absolutely not ok

I'm not sure what's the best way to deal with this issue:
- Add a `ParseStringPipe` and make it the default for `@Query`
- Add a `ParseStringPipe` but not set as default 
- Do nothing and give the responsibility to developers

Sidenote: it might be interesting to make `ParseArrayPipe` only allow one-dimensional arrays too, for the same reason.

-----

Verbose workaround, for people concerned by this issue (as mentioned above):

- Enable [auto validation](https://docs.nestjs.com/techniques/validation#auto-validation) or use `@Query(new ValidationPipe())`
- Use DTOs

```ts
class Params {
  @IsString()
  param!: string
}

@Controller()
export class AppController {
  @Get('/test')
  getHome(@Query() {param}: Params) {
    if (param.length < 2) return 'At least 2 chars'
    console.log(param[0], param[1])
  }
}
```

**Comment by micalevisk** [comment]
btw @GauBen the issue you've described is actually the expected behavior. If you didn't add any sort of parsing&validation step (via `ValidationPipe`, for example), the type of that parameter (`string`) will not be taking in count when parsing query parameters.
