### ISSUE TITLE
ArgumentsHost Microservices can't getHandler and getClass

### ISSUE THREAD

**Issue by pergerk** [nestjs/nest#8477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello, I am trying to getClass and getHandler under rpc but functions are undefined? 
And I doing it wrong or do we have any case to solve this ?

const rpc = host.switchToRpc();
const ctx = rpc.getContext<ExecutionContext>();
console.log('host.getType()', host.getType());
console.log('ctx.getClass fn', ctx.getClass);
console.log('ctx.getHandler fn', ctx.getHandler); 
ctx.getClass and ctx.getHandler are undefined under rpc scope

### Minimum reproduction code

https://github.com/pergerk/microservices

### Steps to reproduce

npm i 
npm run start:dev gw & npm run start:dev service1 & npm run start:dev service2
curl http://localhost:3000/service1

### Expected behavior

 const ctx = rpc.getContext<ExecutionContext>();
should return name of class ctx.getClass().name 
should return name of handler ctx.getHandler().name

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.1.2

### Packages versions

    "@grpc/grpc-js": "^1.4.2",
    "@grpc/proto-loader": "^0.6.6",
    "@nestjs/common": "^8.1.2",
    "@nestjs/core": "^8.1.2",
    "@nestjs/microservices": "^8.1.2",
    "@nestjs/platform-express": "^8.1.2",
    "@nestjs/swagger": "^5.0.0",
    "class-transformer": "^0.4.0",
    "class-validator": "^0.13.1",

### Node.js version

v16.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

[Nest] 89073  - 31.10.2021, 05:59:43     LOG [NestMicroservice] Nest microservice successfully started +12ms
callone called
host.getType() rpc
ctx.getClass fn undefined
ctx.getHandler fn undefined
filtered instance rpc Error in service 1

**Comment by jmcdo29** [comment]
An [ArgumentHost](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/features/arguments-host.interface.ts#L60) has never been able to get the class or handler, because `ArgumentHost` is used in an ExceptionFilter where there may not be a matching class or route handler (404s and such). Only the [ExecutionContext](https://github.com/nestjs/nest/blob/master/packages/common/interfaces/features/execution-context.interface.ts) has the `getClass()` and `getHandler()` methods. And the `ExecutionContext` is different than the `host.switchToRcp().getContext()` return object.
