### ISSUE TITLE
validatorPackage parameter in ValidationPipeOptions not working

### ISSUE THREAD

**Issue by johncmunson** [nestjs/nest#8838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description
The `validatorPackage` parameter appears to be a mechanism for opting out of class-validator and using your own validation strategy. However, the very simple example below illustrates that `validatorPackage` is not functioning correctly (or at all).

The example is setup to return an array of errors, `[{ property: 'value' }]`, 100% of the time. Anytime the endpoint is hit, it _should_ fail validations. However, it does not fail. Even you explicitly throw an error, it does not fail.

Furthermore, placing a log statement inside of the `validate` method indicates that the custom validator isn't even executing at all.

### Minimum Reproduction
![image](https://user-images.githubusercontent.com/19480078/146834791-35dbb270-7bff-4412-9cf9-26570ca4e767.png)

### Interfaces provided by Nest
![image](https://user-images.githubusercontent.com/19480078/146835532-555e4db3-2773-4e9a-bd29-aca21a9ae4ee.png)
![image](https://user-images.githubusercontent.com/19480078/146835281-a7470174-efdf-4b54-9356-54b5cba26083.png)

### Minimum reproduction code

https://github.com

### Steps to reproduce

1. Create a Post endpoint that accesses the body using @Body decorator
2. Provide an instance of ValidationPipe to the body decorator
3. Pass a custom validator to the validation pipe using the `validatorPackage` property

### Expected behavior

Using the `validatorPackage` parameter should influence the behavior of how validations are run. Currently, it has absolutely no effect whatsoever. The code does not execute.

If I'm correct, then hopefully the existence of `validatorPackage` is an indication that the Nest team is going to start allowing more options for validation instead of forcing everyone to use the lousy class-validator.

Regardless of what the true purpose of `validatorPackage` actually is, it stands to reason that using it should at least do something or produce a noticeable effect. As it stands, it seems like dead code.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.4

### Packages versions

- `@nestjs/core` - 8.2.4
- `@nestjs/common` - 8.2.4

### Node.js version

12.22.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf). This way we can clone, run, and see the problem immediately. Thank you

**Comment by micalevisk** [comment]
![image](https://user-images.githubusercontent.com/13461315/146850657-001ba737-1239-433b-a8fe-ed7b607eae2e.png)

the above shows that `options.validatorPackage` will be used instead of `class-validator`.

> `validate` method indicates that the custom validator isn't even executing at all.

And below you can see `validate` being called

https://github.com/nestjs/nest/blob/52381b0fba39ecf64bda5bae4c2cf8fc348130e7/packages/common/pipes/validation.pipe.ts#L209

This is why you need to provide a reproduction repo @johncmunson :)

**Comment by johncmunson** [comment]
Will try to get a minimal reproduction repo put together sometime tomorrow. If it's been a couple days and I haven't put one together yet, feel free to close the issue :)

**Comment by johncmunson** [comment]
Here is the reproduction repo demonstrating the issue. Simply fire up the app and send a Post request to localhost:3000. You will see that `validatorPackage` has zero impact on the functionality of validations or the endpoint.  
https://github.com/johncmunson/validator-package

**Comment by jmcdo29** [comment]
Change your `PayloadDto` from a `type` to a `class` and it will fire as expected. This is due to how Nest determines if the pipe should run fully or not based on the metadata found in the parameter type

**Comment by micalevisk** [comment]
@johncmunson read the hints on this page: https://docs.nestjs.com/techniques/validation#auto-validation

**Comment by micalevisk** [comment]
and is how the builtin `ValidationPipe` works. See

https://github.com/nestjs/nest/blob/775a34853a2ab97c38e021c96c6a4ed2de7815fb/packages/common/pipes/validation.pipe.ts#L162-L169

on above `metadata.metatype` will be `Object` when we use interfaces ([here's](https://youtu.be/UtbUCzdJ7b4?t=515) a good explanation of Kamil about this behavior).

Thus, `toValidate` will return `false` below, making `!this.toValidate(metadata) === true`

https://github.com/nestjs/nest/blob/775a34853a2ab97c38e021c96c6a4ed2de7815fb/packages/common/pipes/validation.pipe.ts#L96-L106

That's why the pipe end up returning `value` (L105) instead of calling
