### ISSUE TITLE
Unable to access cronjobs inside unit tests

### ISSUE THREAD

**Issue by behzadmoradi** [nestjs/nest#9308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Following the docs, I used cronjobs as in a service which works just fine; the problem though is that inside unit tests, I have no access to the a cron by name or to the list of all cronjobs.

### Minimum reproduction code

https://github.com/behzadmoradi/nestjs-cron-issue

### Steps to reproduce

npm run test

### Expected behavior

I actually need to have access to cronjobs inside unit tests to be able to run them manually then add some assertions (Like checking Redis etc.)

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/schedule

### NestJS version

8

### Packages versions

```json

```

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
I guess you should create fake doubles for all dependencies of `AppService`, if you are writing an unit test for it. Then you could make that `this.schedulerRegistry.getCronJob` return whatever you want in order to exercise the `AppService#showByName` method

Look at this repo: https://github.com/jmcdo29/testing-nestjs

And this lib: https://www.npmjs.com/package/@golevelup/ts-jest

And this another one will help you on creating mocks conditionally: https://www.npmjs.com/package/jest-when

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
