### ISSUE TITLE
Generating Entities for either Typeorm or mongoose

### ISSUE THREAD

**Issue by KoesterJannik** [nestjs/nest#9390]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I found myself spending alot of time writing entities for my database.
I use typeorm with repositories.
It would be amazing to let the cli generate the models too.(I have this idea from Ruby on Rails(rails generate scaffold)

### Describe the solution you'd like

For example:

nest g resource users:
RestApi->CRUD entry points->select either typeorm or mongoose->specify your fields(for e.g.) username:string:unique email:string etc.

If the user chooses to generate crud points, we can generate a full working crud route.

If you want something like this , i would work on it and make a pull request.

You have some more ideas maybe?

Thank you!

### Teachability, documentation, adoption, migration strategy

People can use it to save a lot of time working on other stuff.

### What is the motivation / use case for changing the behavior?

I have seen this in ruby on rails and it saves so much time and makes it easy to use it(you cannot go wrong)

**Comment by micalevisk** [comment]
btw this was discussed on Discord: https://discord.com/channels/520622812742811698/819061892861526016/951652066969944095

To me, the community could implement such feature either under some IDE extension (like [NestJS files](https://marketplace.visualstudio.com/items?itemName=AbhijoyBasak.nestjs-files)) or some Angular schematics (because you can extend it to use in your project)
