### ISSUE TITLE
@Injectable() being ignored when instantiating ClientProxy Object in constructor.

### ISSUE THREAD

**Issue by ParichayDidwania** [nestjs/nest#9414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am new to Nestjs and was experimenting around with @Injectable().

Currently, I am Injecting an instance of ClientProxy in the constructor of service class along with another custom class called Test. I have explicitly removed @Injectable() from the AppService Class. I have a PrintTestId() function which logs the value of a member variable of Test Class from the instantiated Object. This function is then called from the AppController Class.

1. When i call that specific api, NO error is shown and member variable is printed with the default value. 
2. When i call that specific api but remove the argument Injecting the ClientProxy variable, the error shows up.

```
import { Inject, Injectable } from '@nestjs/common';
import { ClientProxy } from '@nestjs/microservices';
import { Test } from './test';

//@Injectable()
export class AppService {
  constructor(@Inject('ANALYTICS') private analyticsClient : ClientProxy, public test: Test){}
  printTestId(): void {
    console.log(this.test.id); // Working
  }
}
```

### Minimum reproduction code

https://github.com/ParichayDidwania/nestjs-bug

### Steps to reproduce

1. instantiate a ClientProxy variable inside the constructor of AppService Class
2. instantiate a custom dependency class and remove @Injectable() from AppService Class
3. access any member of the dependency class using the instantiated Object inside AppService 

### Expected behavior

Irrespective of what is instantiated inside the constructor of AppService Class, it should still check for @Injectable() decorator and throw an error.

### Package

- [ ] I don't know. Or some 3rd-party package
- [X] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [X] <code>@nestjs/microservices</code>
- [X] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.3

### Packages versions
```
"dependencies": {
    "@nestjs/common": "^8.4.3",
    "@nestjs/core": "^8.4.3",
    "@nestjs/microservices": "^8.4.3",
    "@nestjs/platform-express": "^8.4.3",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
```
### Node.js version

14.17.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
Something to note is that the `@Injectable()` decorator serves two purposes: 

1) it provides a scope if one is passed. If no scope is passed, then the `default` (singleton) scope is used
2) it forces Typescript to emit metadata about the class. Now, if there are other decorators in the class (like the `@Inject()` in the constructor) then this `@Injectable()` is actually superfluous because Typescript will already emit the metadata as is. If you remove that `@Inject()` though, and the `@Injectable()` typescript will not know to emit the metadata for the class. We can't reliably throw an error about missing metadata for a provider though, because custom providers don't have that metadata: e.g.

```ts
{
	provide: 'SOME_METADATALESS_PROVIDER,
  	useValue: 'I have no metadata :)'
}
```
or
```ts
{
	provide: 'ANOTHER_PROVIDER_WITHOUT_METADATA',
	useFactory: () => new ClassWithoutMetadata()
}
```

Because of this, we can't easily throw an error when there is no `@Injectable()`, and the best we can really do is just instantiate the class (if it is a class) and let the internals of that class be `undefined` (as that's how JavaScript works)

**Comment by ParichayDidwania** [comment]
i am a bit of noob with nestjs here so can you explain why injecting a provider inside the class constructor makes the class Injectable too ?

**Comment by jmcdo29** [comment]
There's two parts to this answer as well.

1) You've used the `@Inject()` decorator, which tells Typescript to emit the metadata (metadata that Nest then reads). This is constructor `design:paramtypes` metadata, which is from the `reflect-metadata` package and not specifically something Nest sets, just something it is reading here

2) You have your `AppService` in the `providers` array, which tells Nest "Hey, I'm going to want to make this class available to the module. When another class inside this module needs it, it has access". Because the `AppController` injects the `AppService` Nest finds the `AppService` in the `AppModule` context, reads its metadata and creates the instance of `AppService` (after creating its dependencies) and then passes the instance on to `AppController`.

**Comment by ParichayDidwania** [comment]
@jmcdo29 Thanks for the explaination. I only have 2 doubts now
1. Is it the case with @Inject() or any decorator

2. Is it the case only when instantiating using Decorator in constructor or anywhere in the class.

**Comment by jmcdo29** [comment]
Any decorator will make Typescript emit the decorator metadata.

Not sure I understand question 2. Nest will inject any dependencies it is able to read. Class properties decorated with `@Inject()` and constructor parameters that have resolvable metadata.

**Comment by ParichayDidwania** [comment]
@jmcdo29 In 2nd question i meant, if i were to use a decorator inside a member function of the class instead of constructor, will metadata for that class still be emitted?

**Comment by jmcdo29** [comment]
Just class and constructor parameter decorators. You can check this [typescript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAtgUygCxAEwCINALhgWSVU2xACcBDKcmAXhgAooKyBzJPCsATwBoYADmRAC80MgEswrGAB8YEbnABGIADb802CJIHUyeAArCBCMlG5YIwXfoCUdAHwwtwHRL3kAdADcKagFcEGAB+EJgAsC0AMykENAAoUEhYYDUKCAgsXBgAYXTM7PIqGnomFnYoB1pnZjYkBKSCiBgAMRAQGABvBJhBAOU1CWAYaI66GAByMZBJhIBfRoABNIys0ia1mAAhFm6YXphk8QDgfQYhCT8oYLIECjRwNW5Rjrx2kAcuxcPlPfpJn8yJMANyNPpLRAodBFQ7AfxqXZkBhfQ59O5QAJkMAwFASCBeIFgvqLH5AA) for a quick look at the emitted metadata.

For further support, please use our [Discord](https://discord.gg/nestjs) server.

**Comment by ParichayDidwania** [comment]
Thanks a lot for clearing my doubts!
