### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by guyulmaz** [nestjs/nest#943]
Hello,
is it possible to have a "project monorepo" for enterprise environment,
As explained in
https://www.youtube.com/watch?v=q4XmAy6_ucw
So one monorepo for nestjs server apps, web apps, nativescript apps, shared libs...
All will share same node modules directory, same versions...

**Comment by ThomRick** [comment]
Hey @guyulmaz !

Nice question ! The answer is in my opinion : yes if the team needs it and can handle it !
Be careful about the CI / CD hooks for example ! ;-)

**Comment by BrunnerLivio** [comment]
Yes it is possible atleast in the backend. Frontend development is not possible (yet?) with NestJS (Angular is the way to go). I've created with the project [lxdhub](https://github.com/Roche/lxdhub) a monorepo with NestJS. For example my package `@lxdhub/db` contains a Nest module, which is used by the packages `@lxdhub/api` and `@lxdhub/dbsync`.

It can get quite hard at some points and it uses a lot of computer power to develop with it. VSCode gets really slow because of the complex module resolution sometimes.

**Comment by xmlking** [comment]
Other example based on #nx workspace 
https://github.com/xmlking/ngx-starter-kit

**Comment by BrunnerLivio** [comment]
Started monorepo starter for NestJS. Feel free to check it out and leave some feedback
https://github.com/BrunnerLivio/nestjs-monorepo-starter/blob/master/README.md

**Comment by marcus-sa** [comment]
You should use https://nrwl.io/nx if in this case it's an Angular & Nest app

**Comment by duro** [comment]
@BrunnerLivio I'm running into problems specifically with nest in a monorepo structure. I've been deving in this structure for some time now, but only just started running into issues when trying to add nest to the repo.

We break our workspace up into two workspaces, one called `packages` where shared libraries go, and another workspace called `services` which usually end up depending on a few things from `packages`.

The problem I am running into is that when something from `packages` depends on @nest libs, and the service also depends on @nest libs, I end up with a them installed twice. I've even ensured that they are using the same versions, but I still end up with a version in the root node_modules, and another in the services node_modules.

This ends up causing issues with including providers from a package into a service, as that package's DI resolver can't find things like the Request, etc.

Any insight on this?

**Comment by kamilmysliwiec** [comment]
@duro define them as `peerDependencies`, not `dependencies`

**Comment by ThomRick** [comment]
If it can help :

Left package.json is user-service application and the right is the database-lib one.

<img width="1678" alt="Capture d’écran 2019-05-10 à 09 35 33" src="https://user-images.githubusercontent.com/7125222/57510473-3acd2900-7307-11e9-9250-d01d8f0ec8be.png">

**Comment by duro** [comment]
@kamilmysliwiec, @ThomRick: thanks, I was able to get it working. I had been doing the approach you guys mentioned, but for some reason it wasn't working. Perhaps something went wrong with my yarn.lock. After a few cleans and re-installs it was resolved.

That said, this approach seems to essentially lock all packages and services to a single version of Nest, especially in development. Since the dev deps get installed working locally, if a new one is created that installs a new version, that will cause a break working locally.

Have you guys ran into this, any suggestions on how to keep this sane in the long run?

**Comment by kamilmysliwiec** [comment]
Just incase others find this thread.

We have announced official [Monorepo support](https://trilon.io/blog/announcing-nestjs-monorepos-and-new-commands) (full article) to create additional Applications or Libraries all within a single monorepo workspace.
