### ISSUE TITLE
ParseArrayPipe

### ISSUE THREAD

**Issue by alisterlf** [nestjs/nest#9443]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The ParseArrayPipe doesn't validate a empty array

### Describe the solution you'd like

ParseArrayPipe should have a `minItems` option in ParseArrayOptions

### Teachability, documentation, adoption, migration strategy

```typescript
export interface ParseArrayOptions
  extends Omit<
    ValidationPipeOptions,
    'transform' | 'validateCustomDecorators' | 'exceptionFactory'
  > {
  items?: Type<unknown>;
  separator?: string;
  optional?: boolean;
  exceptionFactory?: (error: any) => any;
  minItems?: number;
}
```

### What is the motivation / use case for changing the behavior?

I have a endpoint that receives a list of items and a need to validate that the list have at least one valid item

**Comment by micalevisk** [comment]
To me, that the `ParseArrayPipe` should only do the parsing of an string to an array. If we add this `minItems`, someone may ask for `maxItems` just because why not? and so on. Then we end up making it a full-featured pipe and I _think_ it wasn't designed for that. Also, you could extend it to fullfill your needs (that's why the class `ParseArrayPipe` has `protected` members instead of `private`).
