### ISSUE TITLE
nest build produces different output depending on presence of build artifacts for monorepo dependencies

### ISSUE THREAD

**Issue by NiGhTTraX** [nestjs/nest#9577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

`nest build` will produce different code when a dependent package that's aliased inside `tsconfig.paths` has build output, versus when everything is clean.

### Minimum reproduction code

https://github.com/NiGhTTraX/ts-monorepo

### Steps to reproduce

1. `pnpm i`
2. `cd packages/foo && pnpm run build`
3. `cd examples/nestjs && pnpm run build`
4. Observe the contents of `examples/nestjs/dist/examples/nestjs/src/app.service.js` w.r.t. to the import for `@nighttrax/foo`.

If you do step 2 above the import will be:

```js
const foo_1 = require("@nighttrax/foo");
```

If you omit step 2, or run `pnpm run clean` then it will be:

```js
const foo_1 = require("../../../packages/foo/src");
```

### Expected behavior

Since the tsconfig contains path aliases, I would expect `nest build` to produce the `../../packages/foo/src` import.

### Package

- [X] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.2.6

### Packages versions

```json
  "dependencies": {
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@nighttrax/foo": "*",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.0.0"
  },
  "devDependencies": {
    "@nestjs/cli": "^8.0.0",
    "@types/express": "^4.17.11",
    "@types/node": "^16.0.0",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3"
  }
```

### Node.js version

14.8.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

I don't use Nest's monorepo mode (`monorepo: true`), but use path aliases as described at https://github.com/NiGhTTraX/ts-monorepo. This discovery was made while investigating https://github.com/NiGhTTraX/ts-monorepo/issues/241.

**Comment by jmcdo29** [comment]
I believe this has to do with how pnpm workspaces work along with how Nest is making use of `tsconfig-paths` under the hood in the `build` method. Essentially, if `require.resolve(package)` fails, then it will move on to using `tsconfig-paths` to properly resolve the import path. However, in a pnpm workspace, the built package is symlinked into the `node_modules` so when `require.resolve('@nighttrax/foo') is called, after steps 2 above is ran, then it comes back with an actual package, and Nest leaves the import alone.

[Here's the hook into tsconfig-paths](https://github.com/nestjs/nest-cli/blob/master/lib/compiler/hooks/tsconfig-paths.hook.ts). This runs right before Typescript's compiler does, so that we correct whatever paths we need to.

[And here's an issue around discussing why we prefer packages in the `node_modules` if `require.resolve()` works](https://github.com/nestjs/nest-cli/issues/838)
