### ISSUE TITLE
nestjs/core@8.4.1 breaks :param in globalPrefix

### ISSUE THREAD

**Issue by minju-s** [nestjs/nest#9776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When setting a parameter in `app.setGlobalPrefix(':prefix')` it is only available in a controller and not in a middleware.
In version 8.4.0 it works in the middleware too. You can test it if you set 8.4.0 manually in the package.json.

### Minimum reproduction code

https://github.com/minju-s/nestjs-global-prefix-test

### Steps to reproduce

1. `npm ci`
2. `npm start`
3. goto `http://localhost:3000/test/app`
4. console outputs `undefined`

### Expected behavior

1. `npm ci`
2. `npm start`
3. goto `http://localhost:3000/test/app`
4. console outputs `test`

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [X] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [ ] Other (see below)

### NestJS version

8.4.1

### Packages versions

```json
"@nestjs/core": "8.4.1"
```

### Node.js version

16.15.1

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by minju-s** [comment]
The problematic code stems from the middleware-module.ts file of this commit https://github.com/nestjs/nest/pull/9332/commits/1ae72e1fdb338a6e00ac0ca19615602a91edc5bd.
The condition `['*', '/*', '(.*)', '/(.*)'].includes(path)` in line 279 evaluates to `true` as the path is `/*`.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by hayawata3626** [comment]
@kamilmysliwiec 
Nice to meet you.
I don't know which part of the code to modify, but I'd like to do it when I have time.

**Comment by CodyTseng** [comment]
In my humble opinion, the problem is that the meaning of `.forRoutes({ path: '*', method: RequestMethod.ALL });` is defferent before and after the commit https://github.com/nestjs/nest/commit/1ae72e1fdb338a6e00ac0ca19615602a91edc5bd.

Before this commit, the effect is equivalent to `.use('${globalPrefix}/*', MiddlewareFn)`.

After this commit, the effect is equivalent to `.use('*', MiddlewareFn)`. This is to solve https://github.com/nestjs/nest/issues/9124.

So if the golbal prefix contains `:param`, It will cause the two versions to have different results. I propose to add an `isGlobal` option instead of `path: '*'` to implement global middleware.

**Comment by pratik-codes** [comment]
Has anyone picked it up can I try to give it a shot?

**Comment by micalevisk** [comment]
@pratik-codes 

![image](https://user-images.githubusercontent.com/13461315/208306707-360952b2-df78-4b72-a294-8fb9523e3f5f.png)

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/nest/pull/10390
