### ISSUE TITLE
Add support to bun

### ISSUE THREAD

**Issue by lackovic** [nestjs/nest#9923]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No issue.

### Describe the solution you'd like

I would like nest to add support to [bun](https://bun.sh/).

Currently installing the CLI on Ubuntu 22.04 WSL with bun works:

```
$ bun i -g @nestjs/cli
bun add v0.1.3
 installed @nestjs/cli@9.0.0 with binaries:
  - nest
 245 packages installed [3.20s]

$ bun -version
0.1.3
I am not sure how to use nest CLI though:
``` 

But when trying to use the CLI I get the following error:

```
$ nest new project-name
/usr/bin/env: ‘node’: No such file or directory
```

### Teachability, documentation, adoption, migration strategy

Users will be able to use bun instead of node.

### What is the motivation / use case for changing the behavior?

Bun is a new JavaScript runtime, more performant than Node and Deno, with a native bundler, transpiler, task runner and npm client built-in.

**Comment by jmcdo29** [comment]
Even if we got the CLI working with bun, bun can't yet run a NestJS server due to packages Nest uses (like the `repl`), so the point is currently moot. I've been keeping an eye on bun and will test it again once more functionalities are added to it. For now, you _can_ run `bun run start:dev`, but that is pretty much just gonna tell bun to run `nest` in a `node` shell and have `nest` call to the `typescript` compiler without any of the touted benefits bun says it has.

**Comment by micalevisk** [comment]
ins't this the same as [_add support to Deno_ requests](https://github.com/nestjs/nest/issues?q=is%3Aissue+sort%3Aupdated-desc+deno+is%3Aclosed)

**Comment by jadbox** [comment]
Note that Bun can tun compiled /dist/ nest.js applications now as of 0.8.

**Comment by redeemefy** [comment]
> Note that Bun can run compiled /dist/ nest.js applications now as of 0.8.

Is there any documentation on your statement?
