### ISSUE TITLE
Cannot register cron job "ClassName@methodName" because it is defined in a non static provider

### ISSUE THREAD

**Issue by kuriel-trivu** [nestjs/nest#9953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

WARN [Scheduler] Cannot register cron job "ClassNameJob@methodName" because it is defined in a non static provider.

This class is throwing a WARN.

``` typescript
import { Injectable } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
// other imports

@Injectable()
export class ClassNameJob {
  constructor(private readonly xxxService: XxxService) {
  }
  @Cron(CronConstants.AT_EVERY_2TH_MINUTE)
  async methodName(userId?: number) {
       // ... code
  }
}
```

ClassNameJob is imported into providers of app.module.ts

### Minimum reproduction code

provided code

### Expected behavior

class to be registered into scheduler service

### Package

- [ ] I don't know. Or some 3rd-party package
- [ ] <code>@nestjs/common</code>
- [ ] <code>@nestjs/core</code>
- [ ] <code>@nestjs/microservices</code>
- [ ] <code>@nestjs/platform-express</code>
- [ ] <code>@nestjs/platform-fastify</code>
- [ ] <code>@nestjs/platform-socket.io</code>
- [ ] <code>@nestjs/platform-ws</code>
- [ ] <code>@nestjs/testing</code>
- [ ] <code>@nestjs/websockets</code>
- [X] Other (see below)

### Other package

@nestjs/schedule

### NestJS version

8.4.7

### Packages versions

```json
    "@nestjs/common": "8.4.7",
    "@nestjs/core": "8.4.7",
    "@nestjs/jwt": "8.0.1",
    "@nestjs/passport": "8.2.2",
    "@nestjs/platform-express": "8.4.7",
    "@nestjs/platform-socket.io": "8.4.7",
    "@nestjs/schedule": "2.0.1",
    "@nestjs/serve-static": "2.2.2",
    "@nestjs/websockets": "8.4.7",
    "cache-manager": "^4.0.1",
    "class-transformer": "0.4.0",
    "class-validator": "0.13.1",
    "crypto": "1.0.1",
    "dotenv": "6.2.0",
    "express-useragent": "^1.0.15",
    "faker": "5.5.3",
    "hbs": "4.1.2",
    "i18n-js": "3.5.1",
    "lodash": "4.17.21",
    "moment-timezone": "0.5.27",
    "passport": "0.4.1",
    "passport-jwt": "4.0.0",
    "passport-local": "1.0.0",
    "pg": "8.7.1",
    "qs": "6.10.1",
    "randomstring": "1.2.1",
    "reflect-metadata": "0.1.13",
    "rxjs": "7.4.0",
    "sequelize": "6.6.2",
    "sequelize-typescript": "2.1.0",
    "sharp": "^0.30.6",
    "socket.io": "4.2.0",
    "socket.io-client": "2.0.4",
    "typescript": "4.3.5"
```

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction).

[Why Reproductions are Required](https://antfu.me/posts/why-reproductions-are-required).

**Comment by kuriel-trivu** [comment]
I rolled back to nestjs 8.1.2 and it works again.

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by kamilmysliwiec** [comment]
I'll reopen this issue once you provide a minimum reproduction repository, as requested above

**Comment by arinanto** [comment]
> I rolled back to nestjs 8.1.2 and it works again.

Is rolling back the only option? I'm also have this issue and can't found anything about it on documentation. Searching online just keep me coming back to this issue.

**Comment by micalevisk** [comment]
@arinanto if you share us a _minimum_ reproduction of it, I'll spend some time debugging it :smile_cat:

**Comment by arinanto** [comment]
> @arinanto if you share us a _minimum_ reproduction of it, I'll spend some time debugging it 😸

I'll keep this in mind, I'm in a middle of something now. Will notify if/when I made minimum reproduction.

**Comment by piotr-mamenas** [comment]
Please reopen. @kamilmysliwiec 

This happens if the task service class have dependencies injected into constructor which are injected in a non-static scope. You can reproduce it by placing a decorator like:

```
@Injectable({
  scope: Scope.REQUEST,
})
```

Above any of the providers classes of the service that contains the cron job methods. 

If at least one dependency is Scope.REQUEST, this error will appear. I backtracked the code in nestjs/schedule and found out that this is thrown regardless of the CRON method (Inverval, Cron, Timeout all have the same issue)

Services scoped to request cannot be injected into a running task because there is no HTTP request in this context so the error is correct but should be more descriptive to suggest the user that if he has any Scope.REQUEST dependencies, he/she should change it.

**Comment by micalevisk** [comment]
btw [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by piotr-mamenas** [comment]
I did the whole analysis and the reproduction is there. Not sure what you mean.

Reproduction:
Decorate XxxService with Injectable decorator with scope: Scope.REQUEST. 

```
@Injectable({
  scope: Scope.REQUEST,
})
```

BOOM: Error. Remove parameter scope: Scope.REQUEST. BOOM, No error. Can be done on any codebase. What more would you need?

The improvement is as simple as changing the error message, so that it suggests the dev to check his Injectable decorators for the dependencies injected into XxxService, instead of just bluntly throwing an error message without context:
https://github.com/nestjs/schedule/blob/37b79bc227e50594d6f29e65d81dbf06928310f9/lib/schedule.explorer.ts#L90

That's a free PR right there.

**Comment by jmcdo29** [comment]
> What more would you need?

Did you even read any of the linked we've added? First like of https://minimum-reproduction.wtf

> A minimum reproduction repository is a git repository that can be shared publicly (doesn’t expose private business logic), shows the problem you’re running into, and has the fewest dependencies installed possible. It also has the steps in place for how to replicate the error you’re running into. This is easiest to add to the README, but honestly you can add it wherever, a text file even.

We do appreciate the discovery already done, and that you've found that this is specifically causing the error, that's great. But having a git repo ready to test against is one of the best things you can provide when helping out a bug report, because it provides an explicit test case to work against and possibly to even add into the test cases so it's now codified and protected against.

**Comment by kuriel-trivu** [comment]
> btw [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

https://github.com/kuriel-trivu/nestjs-job-bug

**Comment by kamilmysliwiec** [comment]
This is the expected behavior. 
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
